In [228]:
# from google.colab import drive
# drive.mount('/content/drive')

In [229]:
# # navigate to root directory of current file in order to access other files relatively
# %cd /content/drive/MyDrive/Colab\ Notebooks/thesis-writing-1/eda-signal-classifier

In [230]:
# !pip install PyWavelets

In [231]:
import datetime
import math
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import zipfile
import requests

from utilities.loaders import charge_raw_data, download_dataset

from utilities.preprocessors import (
    which_element,
    find_begin_end,)

from utilities.visualizers import (
    view_time_frame,
    view_wavelet_coeffs,
    analyze,
    data_split_metric_values,
    view_value_frequency,
    multi_class_heatmap,
    view_metric_values,
    view_classified_labels,
    view_label_freq,
    disp_cat_feat,
    plot_all_features,
    describe_col,
    ModelResults,
    view_all_splits_results)

from utilities.feature_extractors import (
    concur_extract_features_from_all,
    extract_features_per_hour,
    load_wavelet_data,
    restructure_wavelets,
    compute_features,
    interpolate_signals,
    butter_lowpass_filter,
    get_time_frequency,
    rejoin_data,)

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Downloading dataset

If your project requires downloading a larger file, then you may run into issues using the steps above when you try to load the entire file into memory. To overcome those issues, you can download large files in a streaming fashion to avoid reading the content of large responses all at once

In [232]:
# download_dataset("https://prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com/w8fxrg4pv5-2.zip")

# Loading dataset

In [233]:
# # Extract data from zip file
# with zipfile.ZipFile('./data/Electrodermal Activity artifact correction BEnchmark (EDABE)/EDABE dataset.zip', 'r') as zip_ref:
#     zip_ref.extractall('./data/Electrodermal Activity artifact correction BEnchmark (EDABE)')

In [234]:
# ahixac_eda_df_128hz = pd.read_csv('./data/Electrodermal Activity artifact correction BEnchmark (EDABE)/Train/ahixac_expert1.csv', sep=';')
# ahixac_eda_df_128hz

In [235]:
# ahixac_eda_df_128hz.columns = ['time', 'raw_signal', 'clean_signal', 'label', 'auto_signal', 'pred_art', 'post_proc_pred_art']

In [236]:
# start_time = ahixac_eda_df_128hz.iloc[0]['time']
# start_time

In [237]:
# ahixac_eda_df_128hz.set_index(pd.date_range(start=start_time, periods=ahixac_eda_df_128hz.shape[0], freq=get_time_frequency(128)), inplace=True)
# ahixac_eda_df_128hz

# Downsampling 128hz signals to 16hz

In [238]:
# ahixac_eda_df_16hz = interpolate_signals(ahixac_eda_df_128hz, sample_rate=128, start_time=start_time, target_hz=16)
# ahixac_eda_df_16hz

# Low-pass filtering raw 128hz and 16hz signals

In [239]:
# ahixac_eda_df_128hz['filtered_signal'] = butter_lowpass_filter(ahixac_eda_df_128hz['raw_signal'], cutoff=1.0, samp_freq=128, order=6)
# ahixac_eda_df_16hz['filtered_signal'] = butter_lowpass_filter(ahixac_eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)

In [240]:
# ahixac_eda_df_128hz

In [241]:
# ahixac_eda_df_128hz.iloc[63]

In [242]:
# timestamp_list = ahixac_eda_df_128hz.index.tolist()[::64]
# timestamp_list

In [243]:
# timestamp_list[-1].timestamp()

In [244]:
# ahixac_eda_df_16hz

In [245]:
# ahixac_eda_df_16hz[:8]

In [246]:
# view_time_frame(ahixac_eda_df_128hz, samp_freq=128, cols_to_use=['raw_signal', 'filtered_signal'], img_title='subject ahixac 128hz time frame')
# view_time_frame(ahixac_eda_df_16hz, samp_freq=16, cols_to_use=['raw_signal', 'filtered_signal'], img_title='subject ahixac 16hz time frame')

# Iterate through signals per hour

In [247]:
# data_128hz = extract_features_per_hour(ahixac_eda_df_128hz, hertz=128, window_size=0.5, verbose=True)
# data_128hz

In [248]:
# data_16hz = extract_features_per_hour(ahixac_eda_df_16hz, hertz=16, window_size=0.5, verbose=True)
# data_16hz

#### if we had a 128hz dataset with derived timestamps that increase every 0.5s such as this [0.0, 0.5, 1.0, 1.5, ..., 6506.0] then our segments would be:
```
[0.0, 0.5)
[0.5, 1.0)
[1.0, 1.5)
...
[6504.5, 6506.0)
```

#### 832830 / 64 is 13012.96875 or when "`math.ceil()`ed" is 13013

In [249]:
# math.ceil(13012.96875), math.floor(13012.96875)

In [250]:
# for feature_segments, labels in data_128hz:
#     print(labels.value_counts())

#### here in the first hour of our data the number of artifacts out of all 7200 0.5s segments is 716 or roughly 9.9% of our data, and the number of non-artifacts out of all 7200 0.5s segments is 6484 or roughly 90% of our data

#### For the second hour of our data the number of artifacts out of all 5813 0.5s segments is 208 or roughly 3.58% of our data, and the number of non-artifacts out of all 5813 0.5s segments is 5605 or roughly 96.42% of our data

In [251]:
# for feature_segments, labels in data_16hz:
#     print(labels.value_counts())

#### Here the reason why we have almost the same number of artifact and non-artifact labels to the 128hz data is because we interpolated our 128hz data to 16hz thus losing some of our labels

In [252]:
# ahixac_eda_data = rejoin_data(data_128hz, data_16hz)
# ahixac_eda_data

#### concatenating calculated features from 128hz and 16hz data of the first hour

In [253]:
# ahixac_eda_data[0].columns

# Now we ought to do these for all subjects

# scanning train folder

In [254]:
train_files = os.listdir('./data/Electrodermal Activity artifact correction BEnchmark (EDABE)/Train/')
train_files

['ahixac_expert1.csv',
 'akakip_expert2.csv',
 'aqamom_expert2.csv',
 'aretez_expert1.csv',
 'asifex_expert2.csv',
 'axeyoh_expert2.csv',
 'efawep_expert2.csv',
 'egemow_expert2.csv',
 'ejofeq_expert2.csv',
 'erecij_expert1.csv',
 'esirur_expert1.csv',
 'ewehov_expert2.csv',
 'exozef_expert2.csv',
 'idagah_expert2.csv',
 'ihikay_expert1.csv',
 'ihinot_expert1.csv',
 'imocac_expert2.csv',
 'iqiyat_expert2.csv',
 'obujoh_expert2.csv',
 'ohayeh_expert1.csv',
 'ohufow_expert1.csv',
 'ojotew_expert1.csv',
 'onivuk_expert1.csv',
 'opunad_expert1.csv',
 'otecab_expert2.csv',
 'otuqom_expert1.csv',
 'owegud_expert2.csv',
 'oxisux_expert1.csv',
 'tchgij_expert2.csv',
 'ufoyek_expert2.csv',
 'uqozew_expert1.csv',
 'urogif_expert1.csv',
 'uzefow_expert1.csv']

# Concurrently read each .csv file and use functions that will spit out the features

In [255]:
# train_eda_data = concur_extract_features_from_all('./data/Electrodermal Activity artifact correction BEnchmark (EDABE)/Train/', train_files)
# train_eda_data

#### Above code takes about 204 minutes or 3 hrs and 20 minutes to run

In [256]:
# # save each feature dataframe as a .csv file in the folder created earlier with the same names
# for subject_name, (feature_segments, labels) in train_eda_data:
#     feature_segments.to_csv(f'./data/Artifact Detection Data/train/{subject_name}_features.csv')
#     labels.to_csv(f'./data/Artifact Detection Data/train/{subject_name}_labels.csv')

In [257]:
test_files = os.listdir('./data/Electrodermal Activity artifact correction BEnchmark (EDABE)/Test/')
test_files

['afegip_expert1.csv',
 'ajeric_expert2.csv',
 'ekamis_expert2.csv',
 'iguted_expert1.csv',
 'inefoh_expert1.csv',
 'otafeh_expert1.csv',
 'oxused_expert2.csv',
 'pqbqpr_expert2.csv',
 'uhepah_expert1.csv',
 'ukudab_expert2.csv']

In [258]:
test_eda_data = concur_extract_features_from_all('./data/Electrodermal Activity artifact correction BEnchmark (EDABE)/Test/', test_files)
test_eda_data

In [259]:
# save each feature dataframe as a .csv file in the folder created earlier with the same names
for subject_name, (feature_segments, labels)  in test_eda_data:
    feature_segments.to_csv(f'./data/Artifact Detection Data/test/{subject_name}_features.csv')
    labels.to_csv(f'./data/Artifact Detection Data/test/{subject_name}_labels.csv')

# testing outlier datapoint removal i.e. rows with purely zeros

In [260]:
ahixac_features = pd.read_csv(f'./data/Artifact Detection Data/train/ahixac_expert1_features.csv', index_col=0)
ahixac_features

,raw_128hz_max,raw_128hz_min,raw_128hz_amp,raw_128hz_median,raw_128hz_std,raw_128hz_range,raw_128hz_shannon_entropy,raw_128hz_1d_max,raw_128hz_1d_min,raw_128hz_1d_amp,...,first_4thofa_sec_mean,second_4thofa_sec_mean,first_4thofa_sec_std,second_4thofa_sec_std,first_4thofa_sec_median,second_4thofa_sec_median,first_4thofa_sec_range,second_4thofa_sec_range,first_4thofa_sec_n_coeffs_above_zero,second_4thofa_sec_n_coeffs_above_zero
0,0.000222,0.000000,0.000118,0.000222,1.107831e-04,0.000222,0.691193,0.000111,0.000000,0.000059,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
1,0.000222,0.000222,0.000222,0.000222,5.421011e-20,0.000000,0.000000,0.000111,0.000111,0.000111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
2,0.000222,0.000222,0.000222,0.000222,5.421011e-20,0.000000,0.000000,0.000111,0.000111,0.000111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
3,0.000222,0.000222,0.000222,0.000222,5.421011e-20,0.000000,0.000000,0.000111,0.000111,0.000111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
4,0.000222,0.000222,0.000222,0.000222,5.421011e-20,0.000000,0.000000,0.000111,0.000111,0.000111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13008,2.726007,2.673260,2.695696,2.692308,1.377132e-02,0.052747,3.285635,1.363004,1.336630,1.347900,...,0.002590,0.004029,0.000733,0.000518,0.002590,0.004029,0.001036,0.000733,2.0,2.0
13009,2.733333,2.668864,2.698558,2.696703,1.484814e-02,0.064469,3.265055,1.366667,1.334432,1.349524,...,0.002590,0.005128,0.002198,0.006216,0.002590,0.005128,0.003108,0.008791,2.0,2.0
13010,2.714286,2.624908,2.664309,2.665201,1.988022e-02,0.089377,3.503325,1.357143,1.312454,1.331758,...,0.020721,0.019780,0.019048,0.008288,0.020721,0.019780,0.026937,0.011722,2.0,2.0
13011,2.693773,2.570696,2.616277,2.610256,2.893902e-02,0.123077,3.671302,1.346886,1.285348,1.307582,...,0.011915,0.028205,0.009524,0.024347,0.011915,0.028205,0.013469,0.034432,2.0,2.0
13012,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0

#### recall axis 1 is the x axis and axis 0 is the y axis

In [268]:
non_zero_rows = (ahixac_features != 0).any(axis=1)
non_zero_rows

0         True
1         True
2         True
3         True
4         True
         ...
13008     True
13009     True
13010     True
13011     True
13012    False
Length: 13013, dtype: bool

In [269]:
ahixac_features.index[~non_zero_rows]

Index([7199, 13012], dtype='int64')

In [270]:
ahixac_features[non_zero_rows]

,raw_128hz_max,raw_128hz_min,raw_128hz_amp,raw_128hz_median,raw_128hz_std,raw_128hz_range,raw_128hz_shannon_entropy,raw_128hz_1d_max,raw_128hz_1d_min,raw_128hz_1d_amp,...,first_4thofa_sec_mean,second_4thofa_sec_mean,first_4thofa_sec_std,second_4thofa_sec_std,first_4thofa_sec_median,second_4thofa_sec_median,first_4thofa_sec_range,second_4thofa_sec_range,first_4thofa_sec_n_coeffs_above_zero,second_4thofa_sec_n_coeffs_above_zero
0,0.000222,0.000000,0.000118,0.000222,1.107831e-04,0.000222,0.691193,0.000111,0.000000,0.000059,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
1,0.000222,0.000222,0.000222,0.000222,5.421011e-20,0.000000,0.000000,0.000111,0.000111,0.000111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
2,0.000222,0.000222,0.000222,0.000222,5.421011e-20,0.000000,0.000000,0.000111,0.000111,0.000111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
3,0.000222,0.000222,0.000222,0.000222,5.421011e-20,0.000000,0.000000,0.000111,0.000111,0.000111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
4,0.000222,0.000222,0.000222,0.000222,5.421011e-20,0.000000,0.000000,0.000111,0.000111,0.000111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13007,2.708425,2.613187,2.656571,2.657875,2.243813e-02,0.095238,3.533161,1.353480,1.306593,1.328339,...,0.008806,0.017216,0.003663,0.001554,0.008806,0.017216,0.005180,0.002198,2.0,2.0
13008,2.726007,2.673260,2.695696,2.692308,1.377132e-02,0.052747,3.285635,1.363004,1.336630,1.347900,...,0.002590,0.004029,0.000733,0.000518,0.002590,0.004029,0.001036,0.000733,2.0,2.0
13009,2.733333,2.668864,2.698558,2.696703,1.484814e-02,0.064469,3.265055,1.366667,1.334432,1.349524,...,0.002590,0.005128,0.002198,0.006216,0.002590,0.005128,0.003108,0.008791,2.0,2.0
13010,2.714286,2.624908,2.664309,2.665201,1.988022e-02,0.089377,3.503325,1.357143,1.312454,1.331758,...,0.020721,0.019780,0.019048,0.008288,0.020721,0.019780,0.026937,0.011722,2.0,2.0
13011,2.693773,2.570696,2.616277,2.610256,2.893902e-02,0.123077,3.671302,1.346886,1.285348,1.307582,...,0.011915,0.028205,0.009524,0.024347,0.011915,0.028205,0.013469,0.034432,2.0,2.0

In [263]:
non_zero_rows_alt = ~(ahixac_features == 0).all(axis=1)
non_zero_rows_alt

0         True
1         True
2         True
3         True
4         True
         ...
13008     True
13009     True
13010     True
13011     True
13012    False
Length: 13013, dtype: bool

In [264]:
import re

# what I want is to individually open all the feature segment files as well as their corresponding label files
for train_subject_name in train_files:
    train_subject_name = re.sub(r".csv", "", train_subject_name)
    subject_features = pd.read_csv(f'./data/Artifact Detection Data/train/{train_subject_name}_features.csv', index_col=0)
    subject_labels = pd.read_csv(f'./data/Artifact Detection Data/train/{train_subject_name}_labels.csv', index_col=0)

    # allow modifications to the dataframe here i.e.
    # removing rows with purely 0.0 values for every feature/column
    # as these outliers can negatively impact the training of the 
    # ml model
    non_zero_rows = (subject_features != 0).any(axis=1)

    # keep only the rows that are non zero rows
    # this goes also for rows in the subjects labels
    subject_features[non_zero_rows].to_csv(f'./data/Artifact Detection Data/train/{train_subject_name}_features.csv')
    subject_labels[non_zero_rows].to_csv(f'./data/Artifact Detection Data/train/{train_subject_name}_labels.csv')

In [265]:
# # what I want is to individually open all the feature segment files as well as their corresponding label files
# for test_subject_name in test_files:
#     test_subject_name = re.sub(r".csv", "", test_subject_name)
#     subject_features = pd.read_csv(f'./data/Artifact Detection Data/test/{test_subject_name}_features.csv', index_col=0)
#     subject_labels = pd.read_csv(f'./data/Artifact Detection Data/test/{test_subject_name}_labels.csv', index_col=0)

#     # allow modifications to the dataframe here i.e.
#     # removing rows with purely 0.0 values for every feature/column
#     # as these outliers can negatively impact the testing of the 
#     # ml model
#     non_zero_rows = (subject_features != 0).any(axis=1)

#     # keep only the rows that are non zero rows
#     # this goes also for rows in the subjects labels
#     subject_features[non_zero_rows].to_csv(f'./data/Artifact Detection Data/test/{test_subject_name}_features.csv')
#     subject_labels[non_zero_rows].to_csv(f'./data/Artifact Detection Data/test/{test_subject_name}_labels.csv')

In [266]:
# # once notebook reaches end remove data to clear space
# os.remove('./data/EDABE dataset.zip')
# os.remove('./data/Electrodermal Activity artifact correction BEnchmark (EDABE)')