In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

In [2]:
# # navigate to root directory of current file in order to access other files relatively
# %cd /content/drive/MyDrive/Colab\ Notebooks/thesis-writing-1/eda-signal-classifier

In [3]:
# !pip install PyWavelets

In [4]:
import datetime
import math
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import zipfile
import requests

from utilities.loaders import charge_raw_data, download_dataset

from utilities.preprocessors import (
    which_element,
    find_begin_end,)

from utilities.visualizers import (
    view_time_frame,
    view_wavelet_coeffs,
    analyze,
    data_split_metric_values,
    view_value_frequency,
    multi_class_heatmap,
    view_metric_values,
    view_classified_labels,
    view_label_freq,
    disp_cat_feat,
    plot_all_features,
    describe_col,
    ModelResults,
    view_all_splits_results)

from utilities.feature_extractors import (
    concur_extract_features_from_all,
    extract_features_per_hour,
    load_wavelet_data,
    restructure_wavelets,
    compute_features,
    interpolate_signals,
    butter_lowpass_filter,
    get_time_frequency,
    rejoin_data,)

%load_ext autoreload
%autoreload 2

# Downloading dataset

If your project requires downloading a larger file, then you may run into issues using the steps above when you try to load the entire file into memory. To overcome those issues, you can download large files in a streaming fashion to avoid reading the content of large responses all at once

In [5]:
# download_dataset("https://prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com/w8fxrg4pv5-2.zip")

# Loading dataset

In [6]:
# # Extract data from zip file
# with zipfile.ZipFile('./data/Electrodermal Activity artifact correction BEnchmark (EDABE)/EDABE dataset.zip', 'r') as zip_ref:
#     zip_ref.extractall('./data/Electrodermal Activity artifact correction BEnchmark (EDABE)')

In [7]:
# ahixac_eda_df_128hz = pd.read_csv('./data/Electrodermal Activity artifact correction BEnchmark (EDABE)/Train/ahixac_expert1.csv', sep=';')
# ahixac_eda_df_128hz

In [8]:
# ahixac_eda_df_128hz.columns = ['time', 'raw_signal', 'clean_signal', 'label', 'auto_signal', 'pred_art', 'post_proc_pred_art']

In [9]:
# start_time = ahixac_eda_df_128hz.iloc[0]['time']
# start_time

In [10]:
# ahixac_eda_df_128hz.set_index(pd.date_range(start=start_time, periods=ahixac_eda_df_128hz.shape[0], freq=get_time_frequency(128)), inplace=True)
# ahixac_eda_df_128hz

# Downsampling 128hz signals to 16hz

In [11]:
# ahixac_eda_df_16hz = interpolate_signals(ahixac_eda_df_128hz, sample_rate=128, start_time=start_time, target_hz=16)
# ahixac_eda_df_16hz

# Low-pass filtering raw 128hz and 16hz signals

In [12]:
# ahixac_eda_df_128hz['filtered_signal'] = butter_lowpass_filter(ahixac_eda_df_128hz['raw_signal'], cutoff=1.0, samp_freq=128, order=6)
# ahixac_eda_df_16hz['filtered_signal'] = butter_lowpass_filter(ahixac_eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)

In [13]:
# ahixac_eda_df_128hz

In [14]:
# ahixac_eda_df_128hz.iloc[63]

In [15]:
# timestamp_list = ahixac_eda_df_128hz.index.tolist()[::64]
# timestamp_list

In [16]:
# timestamp_list[-1].timestamp()

In [17]:
# ahixac_eda_df_16hz

In [18]:
# ahixac_eda_df_16hz[:8]

In [19]:
# view_time_frame(ahixac_eda_df_128hz, samp_freq=128, cols_to_use=['raw_signal', 'filtered_signal'], img_title='subject ahixac 128hz time frame')
# view_time_frame(ahixac_eda_df_16hz, samp_freq=16, cols_to_use=['raw_signal', 'filtered_signal'], img_title='subject ahixac 16hz time frame')

# Iterate through signals per hour

In [20]:
# data_128hz = extract_features_per_hour(ahixac_eda_df_128hz, hertz=128, window_size=0.5, verbose=True)
# data_128hz

In [21]:
# data_16hz = extract_features_per_hour(ahixac_eda_df_16hz, hertz=16, window_size=0.5, verbose=True)
# data_16hz

#### if we had a 128hz dataset with derived timestamps that increase every 0.5s such as this [0.0, 0.5, 1.0, 1.5, ..., 6506.0] then our segments would be:
```
[0.0, 0.5)
[0.5, 1.0)
[1.0, 1.5)
...
[6504.5, 6506.0)
```

#### 832830 / 64 is 13012.96875 or when "`math.ceil()`ed" is 13013

In [22]:
# math.ceil(13012.96875), math.floor(13012.96875)

In [23]:
# for feature_segments, labels in data_128hz:
#     print(labels.value_counts())

#### here in the first hour of our data the number of artifacts out of all 7200 0.5s segments is 716 or roughly 9.9% of our data, and the number of non-artifacts out of all 7200 0.5s segments is 6484 or roughly 90% of our data

#### For the second hour of our data the number of artifacts out of all 5813 0.5s segments is 208 or roughly 3.58% of our data, and the number of non-artifacts out of all 5813 0.5s segments is 5605 or roughly 96.42% of our data

In [24]:
# for feature_segments, labels in data_16hz:
#     print(labels.value_counts())

#### Here the reason why we have almost the same number of artifact and non-artifact labels to the 128hz data is because we interpolated our 128hz data to 16hz thus losing some of our labels

In [25]:
# ahixac_eda_data = rejoin_data(data_128hz, data_16hz)
# ahixac_eda_data

#### concatenating calculated features from 128hz and 16hz data of the first hour

In [26]:
# ahixac_eda_data[0].columns

# Now we ought to do these for all subjects

# scanning train folder

In [27]:
train_files = os.listdir('./data/Electrodermal Activity artifact correction BEnchmark (EDABE)/Train/')
train_files

['ahixac_expert1.csv',
 'akakip_expert2.csv',
 'aqamom_expert2.csv',
 'aretez_expert1.csv',
 'asifex_expert2.csv',
 'axeyoh_expert2.csv',
 'efawep_expert2.csv',
 'egemow_expert2.csv',
 'ejofeq_expert2.csv',
 'erecij_expert1.csv',
 'esirur_expert1.csv',
 'ewehov_expert2.csv',
 'exozef_expert2.csv',
 'idagah_expert2.csv',
 'ihikay_expert1.csv',
 'ihinot_expert1.csv',
 'imocac_expert2.csv',
 'iqiyat_expert2.csv',
 'obujoh_expert2.csv',
 'ohayeh_expert1.csv',
 'ohufow_expert1.csv',
 'ojotew_expert1.csv',
 'onivuk_expert1.csv',
 'opunad_expert1.csv',
 'otecab_expert2.csv',
 'otuqom_expert1.csv',
 'owegud_expert2.csv',
 'oxisux_expert1.csv',
 'tchgij_expert2.csv',
 'ufoyek_expert2.csv',
 'uqozew_expert1.csv',
 'urogif_expert1.csv',
 'uzefow_expert1.csv']

# Concurrently read each .csv file and use functions that will spit out the features

In [28]:
train_eda_data = concur_extract_features_from_all('./data/Electrodermal Activity artifact correction BEnchmark (EDABE)/Train/', train_files)
train_eda_data

               time  raw_signal  clean_signal  label  auto_signal  pred_art  \
0          0.000000    0.000000      0.106924    0.0     0.000000       0.0
1          0.007812    0.000000      0.106547    0.0     0.000000       0.0
2          0.015625    0.000000      0.106172    0.0     0.000000       0.0
3          0.023438    0.000000      0.105797    0.0     0.000000       0.0
4          0.031250    0.000000      0.105422    0.0     0.000000       0.0
...             ...         ...           ...    ...          ...       ...
801817  6264.195312    3.042491      2.815892    1.0     3.042491       0.0
801818  6264.203125    3.041026      2.814221    1.0     3.041026       0.0
801819  6264.210938    3.041026      2.812547    1.0     3.041026       0.0
801820  6264.218750    3.042491      2.810869    1.0     3.042491       0.0
801821  6264.226562    3.042491      2.809187    0.0     3.042491       0.0

        post_proc_pred_art
0                      0.0
1                      0.0
2                      0.0
3                      0.0
4                      0.0
...                    ...
801817                 0.0
801818                 0.0
801819                 0.0
801820                 0.0
801821                 0.0

[801822 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
               time  raw_signal  clean_signal  label  auto_signal  pred_art  \
0          0.000000    1.038762      1.038762    0.0     1.038762       0.0
1          0.007812    1.038762      1.038762    0.0     1.038762       0.0
2          0.015625    1.038762      1.038762    0.0     1.038762       0.0
3          0.023438    1.038762      1.038762    0.0     1.038762       0.0
4          0.031250    1.038762      1.038762    0.0     1.038762       0.0
...             ...         ...           ...    ...          ...       ...
782178  6110.765625    0.006882      0.006882    0.0     0.006882       0.0
782179  6110.773438    0.006882      0.006882    0.0     0.006882       0.0
782180  6110.781250    0.006882      0.006882    0.0     0.006882       0.0
782181  6110.789062    0.006882      0.006882    0.0     0.006882       0.0
782182  6110.796875    0.006882      0.006882    0.0     0.006882       0.0

        post_proc_pred_art
0                      0.0
1                      0.0
2                      0.0
3                      0.0
4                      0.0
...                    ...
782178                 0.0
782179                 0.0
782180                 0.0
782181                 0.0
782182                 0.0

[782183 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
               time  raw_signal  clean_signal  label  auto_signal  pred_art  \
0          0.000000    0.000000     -0.091119    0.0     0.000000       0.0
1          0.007812    0.000000     -0.091119    0.0     0.000000       0.0
2          0.015625    0.000000     -0.091119    0.0     0.000000       0.0
3          0.023438    0.000000     -0.091119    0.0     0.000000       0.0
4          0.031250    0.000000     -0.091119    0.0     0.000000       0.0
...             ...         ...           ...    ...          ...       ...
672481  5253.757812   11.377009     11.377009    0.0    11.377009       0.0
672482  5253.765625   11.397430     11.397430    0.0    11.397430       0.0
672483  5253.773438   11.412745     11.412745    0.0    11.412745       0.0
672484  5253.781250   11.433166     11.433166    0.0    11.433166       0.0
672485  5253.789062   11.448482     11.448482    0.0    11.448482       0.0

        post_proc_pred_art
0                      0.0
1                      0.0
2                      0.0
3                      0.0
4                      0.0
...                    ...
672481                 0.0
672482                 0.0
672483                 0.0
672484                 0.0
672485                 0.0

[672486 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000    0.000000     -0.091119    0.0 -1.301043e-18       1.0
1          0.007812    0.000000     -0.091119    0.0  3.879923e-05       1.0
2          0.015625    0.000000     -0.091119    0.0  7.742305e-05       1.0
3          0.023438    0.000000     -0.091119    0.0  1.158718e-04       1.0
4          0.031250    0.000000     -0.091119    0.0  1.541460e-04       1.0
...             ...         ...           ...    ...           ...       ...
833927  6515.054688    9.202180      9.202180    0.0  9.202180e+00       0.0
833928  6515.062500    9.197075      9.197075    0.0  9.197075e+00       0.0
833929  6515.070312    9.202180      9.202180    0.0  9.202180e+00       0.0
833930  6515.078125    9.197075      9.197075    0.0  9.197075e+00       0.0
833931  6515.085938    9.197075      9.197075    0.0  9.197075e+00       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
833927                 0.0
833928                 0.0
833929                 0.0
833930                 0.0
833931                 0.0

[833932 rows x 7 columns]
               time  raw_signal  clean_signal  label  auto_signal  pred_art  \
0          0.000000    0.000000     -0.127567    0.0     0.000000       0.0
1          0.007812    0.000000     -0.127567    0.0     0.000000       0.0
2          0.015625    0.000000     -0.127567    0.0     0.000000       0.0
3          0.023438    0.000000     -0.127567    0.0     0.000000       0.0
4          0.031250    0.000000     -0.127567    0.0     0.000000       0.0
...             ...         ...           ...    ...          ...       ...
755305  5900.820312    3.259341      3.259341    0.0     3.259341       0.0
755306  5900.828125    3.273993      3.273993    0.0     3.273993       0.0
755307  5900.835938    3.271062      3.271062    0.0     3.271062       0.0
755308  5900.843750    3.266667      3.266667    0.0     3.266667       0.0
755309  5900.851562    3.268132      3.268132    0.0     3.268132       0.0

        post_proc_pred_art
0                      0.0
1                      0.0
2                      0.0
3                      0.0
4                      0.0
...                    ...
755305                 0.0
755306                 0.0
755307                 0.0
755308                 0.0
755309                 0.0

[755310 rows x 7 columns]
               time  raw_signal  clean_signal  label  auto_signal  pred_art  \
0          0.000000    1.949957      1.949957    0.0     1.949957       0.0
1          0.007812    1.949957      1.949957    0.0     1.949957       0.0
2          0.015625    1.949957      1.949957    0.0     1.949957       0.0
3          0.023438    1.949957      1.949957    0.0     1.949957       0.0
4          0.031250    1.949957      1.949957    0.0     1.949957       0.0
...             ...         ...           ...    ...          ...       ...
749769  5857.570312    0.000222      0.000222    0.0     0.000222       0.0
749770  5857.578125    0.000222      0.000222    0.0     0.000222       0.0
749771  5857.585938    0.000222      0.000222    0.0     0.000222       0.0
749772  5857.593750    0.000222      0.000222    0.0     0.000222       0.0
749773  5857.601562    0.000222      0.000222    0.0     0.000222       0.0

        post_proc_pred_art
0                      0.0
1                      0.0
2                      0.0
3                      0.0
4                      0.0
...                    ...
749769                 0.0
749770                 0.0
749771                 0.0
749772                 0.0
749773                 0.0

[749774 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000    0.000000     -0.164015    0.0  2.106994e-20       1.0
1          0.007812    0.000000     -0.164015    0.0  1.879714e-06       1.0
2          0.015625    0.000000     -0.164015    0.0  3.656027e-06       1.0
3          0.023438    0.000000     -0.164015    0.0  5.370973e-06       1.0
4          0.031250    0.000000     -0.164015    0.0  7.062509e-06       1.0
...             ...         ...           ...    ...           ...       ...
770809  6021.945312    5.214994      5.214994    0.0  5.214994e+00       0.0
770810  6021.953125    5.209889      5.209889    0.0  5.209889e+00       0.0
770811  6021.960938    5.209889      5.209889    0.0  5.209889e+00       0.0
770812  6021.968750    5.204784      5.204784    0.0  5.204784e+00       0.0
770813  6021.976562    5.204784      5.204784    0.0  5.204784e+00       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
770809                 0.0
770810                 0.0
770811                 0.0
770812                 0.0
770813                 0.0

[770814 rows x 7 columns]
calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000    0.000000     -0.164015    0.0  2.106994e-20       1.0
1          0.007812    0.000000     -0.164015    0.0  1.879714e-06       1.0
2          0.015625    0.000000     -0.164015    0.0  3.656027e-06       1.0
3          0.023438    0.000000     -0.164015    0.0  5.370973e-06       1.0
4          0.031250    0.000000     -0.164015    0.0  7.062509e-06       1.0
...             ...         ...           ...    ...           ...       ...
732049  5719.132812    5.189468      5.189468    0.0  5.189468e+00       0.0
732050  5719.140625    5.163942      5.163942    0.0  5.163942e+00       0.0
732051  5719.148438    5.148626      5.148626    0.0  5.148626e+00       0.0
732052  5719.156250    5.128205      5.128205    0.0  5.128205e+00       0.0
732053  5719.164062    5.179257      5.179257    0.0  5.179257e+00       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
732049                 0.0
732050                 0.0
732051                 0.0
732052                 0.0
732053                 0.0

[732054 rows x 7 columns]
               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000    0.000000     -0.091119    0.0 -4.206704e-17       1.0
1          0.007812    0.000000     -0.091119    0.0  4.270972e-05       1.0
2          0.015625    0.000000     -0.091119    0.0  8.537705e-05       1.0
3          0.023438    0.000000     -0.091119    0.0  1.280020e-04       1.0
4          0.031250    0.000000     -0.091119    0.0  1.705848e-04       1.0
...             ...         ...           ...    ...           ...       ...
725623  5668.929688    1.914286      1.914286    0.0  1.914286e+00       0.0
725624  5668.937500    1.912821      1.912821    0.0  1.912821e+00       0.0
725625  5668.945312    1.914286      1.914286    0.0  1.914286e+00       0.0
725626  5668.953125    1.912821      1.912821    0.0  1.912821e+00       0.0
725627  5668.960938    1.914286      1.914286    0.0  1.914286e+00       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
725623                 0.0
725624                 0.0
725625                 0.0
725626                 0.0
725627                 0.0

[725628 rows x 7 columns]
               time  raw_signal  clean_signal  label  auto_signal  pred_art  \
0          0.000000    0.000000     -0.200463    0.0     0.000000       0.0
1          0.007812    0.000000     -0.200463    0.0     0.000000       0.0
2          0.015625    0.000000     -0.200463    0.0     0.000000       0.0
3          0.023438    0.000000     -0.200463    0.0     0.000000       0.0
4          0.031250    0.000000     -0.200463    0.0     0.000000       0.0
...             ...         ...           ...    ...          ...       ...
809569  6324.757812    1.914286      1.914286    0.0     1.914286       0.0
809570  6324.765625    1.918681      1.918681    0.0     1.918681       0.0
809571  6324.773438    1.928938      1.928938    0.0     1.928938       0.0
809572  6324.781250    1.924542      1.924542    0.0     1.924542       0.0
809573  6324.789062    1.923077      1.923077    0.0     1.923077       0.0

        post_proc_pred_art
0                      0.0
1                      0.0
2                      0.0
3                      0.0
4                      0.0
...                    ...
809569                 0.0
809570                 0.0
809571                 0.0
809572                 0.0
809573                 0.0

[809574 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000    0.000000     -0.164015    0.0  2.106994e-20       1.0
1          0.007812    0.000000     -0.127567    0.0  1.879714e-06       1.0
2          0.015625    0.000000     -0.127567    0.0  3.656027e-06       1.0
3          0.023438    0.000000     -0.127567    0.0  5.370973e-06       1.0
4          0.031250    0.000000     -0.127567    0.0  7.062509e-06       1.0
...             ...         ...           ...    ...           ...       ...
832825  6506.445312    2.591209      2.591209    0.0  2.591209e+00       0.0
832826  6506.453125    2.585348      2.585348    0.0  2.585348e+00       0.0
832827  6506.460938    2.602930      2.602930    0.0  2.602930e+00       0.0
832828  6506.468750    2.570696      2.570696    0.0  2.570696e+00       0.0
832829  6506.476562    2.589744      2.589744    0.0  2.589744e+00       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
832825                 0.0
832826                 0.0
832827                 0.0
832828                 0.0
832829                 0.0

[832830 rows x 7 columns]
               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000    0.000000     -0.127567    0.0  2.106994e-20       1.0
1          0.007812    0.000000     -0.127567    0.0  1.879714e-06       1.0
2          0.015625    0.000000     -0.127567    0.0  3.656027e-06       1.0
3          0.023438    0.000000     -0.127567    0.0  5.370973e-06       1.0
4          0.031250    0.000000     -0.127567    0.0  7.062509e-06       1.0
...             ...         ...           ...    ...           ...       ...
902593  7051.507812    0.000222      0.000222    0.0  2.220002e-04       0.0
902594  7051.515625    0.003774      0.003774    0.0  3.774004e-03       0.0
902595  7051.523438    0.000222      0.000222    0.0  2.220002e-04       0.0
902596  7051.531250    0.000222      0.000222    0.0  2.220002e-04       0.0
902597  7051.539062    0.000222      0.000222    0.0  2.220002e-04       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
902593                 0.0
902594                 0.0
902595                 0.0
902596                 0.0
902597                 0.0

[902598 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.004662                 0.003297
1970-01-01 00:00:00.187500                0.000000                 0.002509
1970-01-01 00:00:00.250000                0.000000                 0.000444
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.001036                 0.000733
1970-01-01 00:59:59.750000                0.001036                 0.000733
1970-01-01 00:59:59.812500                0.001036                 0.000733
1970-01-01 00:59:59.875000                0.000000                 0.001465
1970-01-01 00:59:59.937500                0.000000                 0.000000

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.006993
1970-01-01 00:00:00.187500                0.001774
1970-01-01 00:00:00.250000                0.000314
...                                            ...
1970-01-01 00:59:59.687500                0.003108
1970-01-01 00:59:59.750000                0.002072
1970-01-01 00:59:59.812500                0.002072
1970-01-01 00:59:59.875000                0.001036
1970-01-01 00:59:59.937500                0.002072

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.004662                 0.003297
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.001036                 0.000733
1970-01-01 00:59:59.875000                0.000000                 0.001465
1970-01-01 00:59:59.906250                0.000000                 0.000000
1970-01-01 00:59:59.937500                0.000000                 0.000000
1970-01-01 00:59:59.968750                0.000000                 0.000000

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
1970-01-01 00:00:00.187500                0.000000                 0.000222
1970-01-01 00:00:00.250000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.009324                 0.004396
1970-01-01 00:59:59.750000                0.010361                 0.002930
1970-01-01 00:59:59.812500                0.010361                 0.003663
1970-01-01 00:59:59.875000                0.009324                 0.003663
1970-01-01 00:59:59.937500                0.010361                 0.007326

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000157
1970-01-01 00:00:00.250000                0.000000
...                                            ...
1970-01-01 00:59:59.687500                0.007770
1970-01-01 00:59:59.750000                0.006216
1970-01-01 00:59:59.812500                0.004144
1970-01-01 00:59:59.875000                0.004144
1970-01-01 00:59:59.937500                0.006734

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.008288                 0.002198
1970-01-01 00:59:59.875000                0.009324                 0.000733
1970-01-01 00:59:59.906250                0.009324                 0.003663
1970-01-01 00:59:59.937500                0.009324                 0.000733
1970-01-01 00:59:59.968750                0.010361                 0.007326

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.028762                 0.020338
1970-01-01 00:00:00.187500                0.001036                 0.002930
1970-01-01 00:00:00.250000                0.002072                 0.007326
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.008288                 0.009524
1970-01-01 00:59:59.750000                0.008288                 0.005861
1970-01-01 00:59:59.812500                0.013469                 0.004396
1970-01-01 00:59:59.875000                0.008288                 0.010256
1970-01-01 00:59:59.937500                0.008288                 0.010256

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.042625
1970-01-01 00:00:00.187500                0.003626
1970-01-01 00:00:00.250000                0.005180
...                                            ...
1970-01-01 00:59:59.687500                0.000518
1970-01-01 00:59:59.750000                0.001036
1970-01-01 00:59:59.812500                0.007770
1970-01-01 00:59:59.875000                0.002072
1970-01-01 00:59:59.937500                0.004662

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.028762                 0.020338
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.007252                 0.004396
1970-01-01 00:59:59.875000                0.008288                 0.010256
1970-01-01 00:59:59.906250                0.007252                 0.008791
1970-01-01 00:59:59.937500                0.006216                 0.006593
1970-01-01 00:59:59.968750                0.008288                 0.010256

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.006056                 0.004282
1970-01-01 00:00:00.187500                0.000314                 0.003441
1970-01-01 00:00:00.250000                0.000314                 0.000666
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.003610                 0.010210
1970-01-01 00:59:59.750000                0.003610                 0.010210
1970-01-01 00:59:59.812500                0.003610                 0.007658
1970-01-01 00:59:59.875000                0.000000                 0.010210
1970-01-01 00:59:59.937500                0.000000                 0.010210

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.009084
1970-01-01 00:00:00.187500                0.002433
1970-01-01 00:00:00.250000                0.001413
...                                            ...
1970-01-01 00:59:59.687500                0.012635
1970-01-01 00:59:59.750000                0.014440
1970-01-01 00:59:59.812500                0.012635
1970-01-01 00:59:59.875000                0.014440
1970-01-01 00:59:59.937500                0.014440

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.006056                 0.004282
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.003610                 0.007658
1970-01-01 00:59:59.875000                0.000000                 0.010210
1970-01-01 00:59:59.906250                0.000000                 0.010210
1970-01-01 00:59:59.937500                0.000000                 0.010210
1970-01-01 00:59:59.968750                0.000000                 0.010210

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.004662                 0.003297
1970-01-01 00:00:00.187500                0.000000                 0.002953
1970-01-01 00:00:00.250000                0.000314                 0.000888
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.003610                 0.002553
1970-01-01 00:59:59.750000                0.003610                 0.002553
1970-01-01 00:59:59.812500                0.003610                 0.002553
1970-01-01 00:59:59.875000                0.003610                 0.015316
1970-01-01 00:59:59.937500                0.010830                 0.020421

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.006993
1970-01-01 00:00:00.187500                0.002088
1970-01-01 00:00:00.250000                0.000628
...                                            ...
1970-01-01 00:59:59.687500                0.001805
1970-01-01 00:59:59.750000                0.001805
1970-01-01 00:59:59.812500                0.005415
1970-01-01 00:59:59.875000                0.027075
1970-01-01 00:59:59.937500                0.064979

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.004662                 0.003297
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.000000                 0.000000
1970-01-01 00:59:59.875000                0.003610                 0.007658
1970-01-01 00:59:59.906250                0.003610                 0.015316
1970-01-01 00:59:59.937500                0.010830                 0.020421
1970-01-01 00:59:59.968750                0.010830                 0.020421

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
1970-01-01 00:00:00.187500                0.000000                 0.000222
1970-01-01 00:00:00.250000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.013469                 0.002930
1970-01-01 00:59:59.750000                0.012433                 0.007326
1970-01-01 00:59:59.812500                0.010361                 0.002930
1970-01-01 00:59:59.875000                0.011397                 0.005128
1970-01-01 00:59:59.937500                0.011397                 0.004396

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000157
1970-01-01 00:00:00.250000                0.000000
...                                            ...
1970-01-01 00:59:59.687500                0.008288
1970-01-01 00:59:59.750000                0.006734
1970-01-01 00:59:59.812500                0.020203
1970-01-01 00:59:59.875000                0.001554
1970-01-01 00:59:59.937500                0.009843

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.005180                 0.002930
1970-01-01 00:59:59.875000                0.004144                 0.004396
1970-01-01 00:59:59.906250                0.011397                 0.005128
1970-01-01 00:59:59.937500                0.011397                 0.004396
1970-01-01 00:59:59.968750                0.011397                 0.003663

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
1970-01-01 00:00:00.187500                0.000000                 0.000222
1970-01-01 00:00:00.250000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.013469                 0.010989
1970-01-01 00:59:59.750000                0.013469                 0.004396
1970-01-01 00:59:59.812500                0.014505                 0.005861
1970-01-01 00:59:59.875000                0.013469                 0.007326
1970-01-01 00:59:59.937500                0.014505                 0.008791

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000157
1970-01-01 00:00:00.250000                0.000000
...                                            ...
1970-01-01 00:59:59.687500                0.005180
1970-01-01 00:59:59.750000                0.001554
1970-01-01 00:59:59.812500                0.014505
1970-01-01 00:59:59.875000                0.005180
1970-01-01 00:59:59.937500                0.006216

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.014505                 0.004396
1970-01-01 00:59:59.875000                0.013469                 0.007326
1970-01-01 00:59:59.906250                0.001036                 0.002930
1970-01-01 00:59:59.937500                0.014505                 0.004396
1970-01-01 00:59:59.968750                0.011397                 0.008791

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.004662                 0.003297
1970-01-01 00:00:00.187500                0.000000                 0.001177
1970-01-01 00:00:00.250000                0.000628                 0.002442
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.000314                 0.000222
1970-01-01 00:59:59.750000                0.000314                 0.000222
1970-01-01 00:59:59.812500                0.000000                 0.000000
1970-01-01 00:59:59.875000                0.000314                 0.000222
1970-01-01 00:59:59.937500                0.000314                 0.000444

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.006993
1970-01-01 00:00:00.187500                0.000832
1970-01-01 00:00:00.250000                0.002355
...                                            ...
1970-01-01 00:59:59.687500                0.000471
1970-01-01 00:59:59.750000                0.000157
1970-01-01 00:59:59.812500                0.000000
1970-01-01 00:59:59.875000                0.000000
1970-01-01 00:59:59.937500                0.000000

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.004662                 0.003297
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.000000                 0.000000
1970-01-01 00:59:59.875000                0.000314                 0.000222
1970-01-01 00:59:59.906250                0.000314                 0.000222
1970-01-01 00:59:59.937500                0.000000                 0.000444
1970-01-01 00:59:59.968750                0.000314                 0.000000

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
1970-01-01 00:00:00.187500                0.000000                 0.000222
1970-01-01 00:00:00.250000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.008288                 0.005128
1970-01-01 00:59:59.750000                0.008288                 0.004396
1970-01-01 00:59:59.812500                0.010361                 0.009524
1970-01-01 00:59:59.875000                0.012433                 0.008791
1970-01-01 00:59:59.937500                0.010361                 0.009524

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000157
1970-01-01 00:00:00.250000                0.000000
...                                            ...
1970-01-01 00:59:59.687500                0.001036
1970-01-01 00:59:59.750000                0.000518
1970-01-01 00:59:59.812500                0.003626
1970-01-01 00:59:59.875000                0.000000
1970-01-01 00:59:59.937500                0.003108

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.010361                 0.009524
1970-01-01 00:59:59.875000                0.012433                 0.008791
1970-01-01 00:59:59.906250                0.010361                 0.008791
1970-01-01 00:59:59.937500                0.004144                 0.002198
1970-01-01 00:59:59.968750                0.010361                 0.009524

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
1970-01-01 00:00:00.187500                0.000000                 0.000222
1970-01-01 00:00:00.250000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.006216                 0.013187
1970-01-01 00:59:59.750000                0.004144                 0.013187
1970-01-01 00:59:59.812500                0.004144                 0.019780
1970-01-01 00:59:59.875000                0.036262                 0.010989
1970-01-01 00:59:59.937500                0.005180                 0.010989

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000157
1970-01-01 00:00:00.250000                0.000000
...                                            ...
1970-01-01 00:59:59.687500                0.000518
1970-01-01 00:59:59.750000                0.003626
1970-01-01 00:59:59.812500                0.011397
1970-01-01 00:59:59.875000                0.008806
1970-01-01 00:59:59.937500                0.008288

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.003108                 0.013919
1970-01-01 00:59:59.875000                0.007252                 0.008791
1970-01-01 00:59:59.906250                0.036262                 0.010989
1970-01-01 00:59:59.937500                0.004144                 0.002198
1970-01-01 00:59:59.968750                0.005180                 0.010989

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.005698                 0.004029
1970-01-01 00:00:00.187500                0.000000                 0.003263
1970-01-01 00:00:00.250000                0.000314                 0.000222
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.000000                 0.000000
1970-01-01 00:59:59.750000                0.003610                 0.002553
1970-01-01 00:59:59.812500                0.003610                 0.002553
1970-01-01 00:59:59.875000                0.000000                 0.000000
1970-01-01 00:59:59.937500                0.003610                 0.005105

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.008547
1970-01-01 00:00:00.187500                0.002308
1970-01-01 00:00:00.250000                0.000471
...                                            ...
1970-01-01 00:59:59.687500                0.007220
1970-01-01 00:59:59.750000                0.005415
1970-01-01 00:59:59.812500                0.009025
1970-01-01 00:59:59.875000                0.007220
1970-01-01 00:59:59.937500                0.007220

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.005698                 0.004029
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.003610                 0.002553
1970-01-01 00:59:59.875000                0.000000                 0.000000
1970-01-01 00:59:59.906250                0.000000                 0.000000
1970-01-01 00:59:59.937500                0.003610                 0.005105
1970-01-01 00:59:59.968750                0.000000                 0.000000

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
1970-01-01 00:00:00.187500                0.000314                 0.000444
1970-01-01 00:00:00.250000                0.001256                 0.000888
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.002072                 0.006593
1970-01-01 00:59:59.750000                0.003108                 0.009524
1970-01-01 00:59:59.812500                0.002072                 0.008059
1970-01-01 00:59:59.875000                0.004144                 0.003663
1970-01-01 00:59:59.937500                0.002072                 0.007326

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000314
1970-01-01 00:00:00.250000                0.000628
...                                            ...
1970-01-01 00:59:59.687500                0.001554
1970-01-01 00:59:59.750000                0.008288
1970-01-01 00:59:59.812500                0.000518
1970-01-01 00:59:59.875000                0.004144
1970-01-01 00:59:59.937500                0.001554

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.002072                 0.008059
1970-01-01 00:59:59.875000                0.004144                 0.003663
1970-01-01 00:59:59.906250                0.004144                 0.002198
1970-01-01 00:59:59.937500                0.002072                 0.007326
1970-01-01 00:59:59.968750                0.001036                 0.005128

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 01:27:33 to 1970-01-01 01:27:33.500000 for index 3306
calculating features from 672384 to 672447 for index 3306
processed hour 1 - start: 460800 | end: 672486
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                 0.00361                 0.002553
1970-01-01 01:00:00.062500                 0.00361                 0.002553
1970-01-01 01:00:00.125000                 0.00361                 0.002553
1970-01-01 01:00:00.187500                 0.00361                 0.005105
1970-01-01 01:00:00.250000                 0.00361                 0.002553
...                                            ...                      ...
1970-01-01 01:27:33.500000                 0.01083                 0.015316
1970-01-01 01:27:33.562500                 0.01805                 0.038289
1970-01-01 01:27:33.625000                 0.02166                 0.045947
1970-01-01 01:27:33.687500                 0.02888                 0.051052
1970-01-01 01:27:33.750000                 0.01805                 0.040842

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000            9.024860e-03
1970-01-01 01:00:00.062500            5.414916e-03
1970-01-01 01:00:00.125000            1.804972e-03
1970-01-01 01:00:00.187500            3.552714e-15
1970-01-01 01:00:00.250000            1.804972e-03
...                                            ...
1970-01-01 01:27:33.500000            3.429447e-02
1970-01-01 01:27:33.562500            7.400385e-02
1970-01-01 01:27:33.625000            1.281530e-01
1970-01-01 01:27:33.687500            1.227381e-01
1970-01-01 01:27:33.750000            7.941877e-02

[26461 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                 0.00361                 0.002553
1970-01-01 01:00:00.031250                 0.00000                 0.000000
1970-01-01 01:00:00.062500                 0.00361                 0.000000
1970-01-01 01:00:00.093750                 0.00361                 0.002553
1970-01-01 01:00:00.125000                 0.00361                 0.002553
...                                            ...                      ...
1970-01-01 01:27:33.656250                 0.02166                 0.045947
1970-01-01 01:27:33.687500                 0.01805                 0.051052
1970-01-01 01:27:33.718750                 0.02888                 0.045947
1970-01-01 01:27:33.750000                 0.01805                 0.040842
1970-01-01 01:27:33.781250                 0.01083                 0.000000

[52922 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:34:28 to 1970-01-01 01:34:28.500000 for index 4136
calculating features from 725504 to 725567 for index 4136
processed hour 1 - start: 460800 | end: 725628
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.000314                 0.000222
1970-01-01 01:00:00.062500                0.000314                 0.000222
1970-01-01 01:00:00.125000                0.000628                 0.000444
1970-01-01 01:00:00.187500                0.000314                 0.000222
1970-01-01 01:00:00.250000                0.000314                 0.000444
...                                            ...                      ...
1970-01-01 01:34:28.687500                0.001036                 0.000733
1970-01-01 01:34:28.750000                0.001036                 0.000000
1970-01-01 01:34:28.812500                0.001036                 0.000733
1970-01-01 01:34:28.875000                0.001036                 0.000733
1970-01-01 01:34:28.937500                0.001036                 0.000000

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.000314
1970-01-01 01:00:00.062500                0.000157
1970-01-01 01:00:00.125000                0.000157
1970-01-01 01:00:00.187500                0.000314
1970-01-01 01:00:00.250000                0.000157
...                                            ...
1970-01-01 01:34:28.687500                0.000518
1970-01-01 01:34:28.750000                0.000000
1970-01-01 01:34:28.812500                0.002072
1970-01-01 01:34:28.875000                0.000000
1970-01-01 01:34:28.937500                0.000000

[33104 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.000314                 0.000222
1970-01-01 01:00:00.031250                0.000314                 0.000222
1970-01-01 01:00:00.062500                0.000314                 0.000222
1970-01-01 01:00:00.093750                0.000000                 0.000000
1970-01-01 01:00:00.125000                0.000628                 0.000444
...                                            ...                      ...
1970-01-01 01:34:28.843750                0.001036                 0.000733
1970-01-01 01:34:28.875000                0.001036                 0.000733
1970-01-01 01:34:28.906250                0.001036                 0.000733
1970-01-01 01:34:28.937500                0.001036                 0.000000
1970-01-01 01:34:28.968750                0.000000                 0.000000

[66208 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:35:18.500000 to 1970-01-01 01:35:19 for index 4237
calculating features from 731968 to 732031 for index 4237
processed hour 1 - start: 460800 | end: 732054
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.011397                 0.004396
1970-01-01 01:00:00.062500                0.011397                 0.004396
1970-01-01 01:00:00.125000                0.011397                 0.005128
1970-01-01 01:00:00.187500                0.017613                 0.000733
1970-01-01 01:00:00.250000                0.011397                 0.007326
...                                            ...                      ...
1970-01-01 01:35:18.875000                0.028880                 0.012763
1970-01-01 01:35:18.937500                0.036099                 0.007658
1970-01-01 01:35:19.000000                0.032489                 0.015316
1970-01-01 01:35:19.062500                0.036099                 0.007658
1970-01-01 01:35:19.125000                0.039709                 0.005105

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.005698
1970-01-01 01:00:00.062500                0.012433
1970-01-01 01:00:00.125000                0.004662
1970-01-01 01:00:00.187500                0.016059
1970-01-01 01:00:00.250000                0.016577
...                                            ...
1970-01-01 01:35:18.875000                0.032489
1970-01-01 01:35:18.937500                0.014440
1970-01-01 01:35:19.000000                0.007220
1970-01-01 01:35:19.062500                0.012635
1970-01-01 01:35:19.125000                0.007220

[33907 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.010361                 0.003663
1970-01-01 01:00:00.031250                0.011397                 0.004396
1970-01-01 01:00:00.062500                0.011397                 0.002930
1970-01-01 01:00:00.093750                0.008288                 0.004396
1970-01-01 01:00:00.125000                0.003108                 0.001465
...                                            ...                      ...
1970-01-01 01:35:19.031250                0.032489                 0.005105
1970-01-01 01:35:19.062500                0.032489                 0.005105
1970-01-01 01:35:19.093750                0.036099                 0.007658
1970-01-01 01:35:19.125000                0.039709                 0.005105
1970-01-01 01:35:19.156250                0.036099                 0.000000

[67814 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:37:37 to 1970-01-01 01:37:37.500000 for index 4514
calculating features from 749696 to 749759 for index 4514
processed hour 1 - start: 460800 | end: 749774
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.008288                 0.007326
1970-01-01 01:00:00.062500                0.007252                 0.016117
1970-01-01 01:00:00.125000                0.012433                 0.007326
1970-01-01 01:00:00.187500                0.006216                 0.010989
1970-01-01 01:00:00.250000                0.006216                 0.009524
...                                            ...                      ...
1970-01-01 01:37:37.312500                0.000000                 0.000000
1970-01-01 01:37:37.375000                0.000000                 0.000000
1970-01-01 01:37:37.437500                0.000000                 0.000000
1970-01-01 01:37:37.500000                0.000000                 0.000000
1970-01-01 01:37:37.562500                0.000000                 0.000000

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.005698
1970-01-01 01:00:00.062500                0.001554
1970-01-01 01:00:00.125000                0.003108
1970-01-01 01:00:00.187500                0.001554
1970-01-01 01:00:00.250000                0.003108
...                                            ...
1970-01-01 01:37:37.312500                0.000000
1970-01-01 01:37:37.375000                0.000000
1970-01-01 01:37:37.437500                0.000000
1970-01-01 01:37:37.500000                0.000000
1970-01-01 01:37:37.562500                0.000000

[36122 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.008288                 0.007326
1970-01-01 01:00:00.031250                0.006216                 0.006593
1970-01-01 01:00:00.062500                0.007252                 0.010989
1970-01-01 01:00:00.093750                0.004144                 0.016117
1970-01-01 01:00:00.125000                0.008288                 0.007326
...                                            ...                      ...
1970-01-01 01:37:37.468750                0.000000                 0.000000
1970-01-01 01:37:37.500000                0.000000                 0.000000
1970-01-01 01:37:37.531250                0.000000                 0.000000
1970-01-01 01:37:37.562500                0.000000                 0.000000
1970-01-01 01:37:37.593750                0.000000                 0.000000

[72244 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:38:20 to 1970-01-01 01:38:20.500000 for index 4600
calculating features from 755200 to 755263 for index 4600
processed hour 1 - start: 460800 | end: 755310
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.007252                 0.013187
1970-01-01 01:00:00.062500                0.007252                 0.002930
1970-01-01 01:00:00.125000                0.008288                 0.002198
1970-01-01 01:00:00.187500                0.005180                 0.007326
1970-01-01 01:00:00.250000                0.014505                 0.019780
...                                            ...                      ...
1970-01-01 01:38:20.562500                0.007252                 0.008791
1970-01-01 01:38:20.625000                0.011397                 0.010256
1970-01-01 01:38:20.687500                0.004144                 0.010989
1970-01-01 01:38:20.750000                0.007252                 0.005861
1970-01-01 01:38:20.812500                0.007252                 0.008059

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.000518
1970-01-01 01:00:00.062500                0.026937
1970-01-01 01:00:00.125000                0.038334
1970-01-01 01:00:00.187500                0.003108
1970-01-01 01:00:00.250000                0.014505
...                                            ...
1970-01-01 01:38:20.562500                0.006734
1970-01-01 01:38:20.625000                0.009843
1970-01-01 01:38:20.687500                0.002072
1970-01-01 01:38:20.750000                0.003108
1970-01-01 01:38:20.812500                0.001554

[36814 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.003108                 0.013187
1970-01-01 01:00:00.031250                0.007252                 0.008059
1970-01-01 01:00:00.062500                0.007252                 0.002930
1970-01-01 01:00:00.093750                0.007252                 0.002930
1970-01-01 01:00:00.125000                0.008288                 0.002198
...                                            ...                      ...
1970-01-01 01:38:20.718750                0.004144                 0.010989
1970-01-01 01:38:20.750000                0.007252                 0.004396
1970-01-01 01:38:20.781250                0.003108                 0.005861
1970-01-01 01:38:20.812500                0.007252                 0.008059
1970-01-01 01:38:20.843750                0.001036                 0.000000

[73628 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:40:21 to 1970-01-01 01:40:21.500000 for index 4842
calculating features from 770688 to 770751 for index 4842
processed hour 1 - start: 460800 | end: 770814
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.015541                 0.007326
1970-01-01 01:00:00.062500                0.013469                 0.005128
1970-01-01 01:00:00.125000                0.002072                 0.005861
1970-01-01 01:00:00.187500                0.012433                 0.005861
1970-01-01 01:00:00.250000                0.012433                 0.005861
...                                            ...                      ...
1970-01-01 01:40:21.687500                0.003610                 0.005105
1970-01-01 01:40:21.750000                0.007220                 0.005105
1970-01-01 01:40:21.812500                0.003610                 0.005105
1970-01-01 01:40:21.875000                0.003610                 0.005105
1970-01-01 01:40:21.937500                0.003610                 0.002553

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.003108
1970-01-01 01:00:00.062500                0.002590
1970-01-01 01:00:00.125000                0.003626
1970-01-01 01:00:00.187500                0.006734
1970-01-01 01:00:00.250000                0.000518
...                                            ...
1970-01-01 01:40:21.687500                0.012635
1970-01-01 01:40:21.750000                0.007220
1970-01-01 01:40:21.812500                0.009025
1970-01-01 01:40:21.875000                0.010830
1970-01-01 01:40:21.937500                0.009025

[38752 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.014505                 0.007326
1970-01-01 01:00:00.031250                0.015541                 0.004396
1970-01-01 01:00:00.062500                0.013469                 0.004396
1970-01-01 01:00:00.093750                0.013469                 0.005128
1970-01-01 01:00:00.125000                0.002072                 0.002198
...                                            ...                      ...
1970-01-01 01:40:21.843750                0.000000                 0.005105
1970-01-01 01:40:21.875000                0.003610                 0.005105
1970-01-01 01:40:21.906250                0.003610                 0.000000
1970-01-01 01:40:21.937500                0.003610                 0.002553
1970-01-01 01:40:21.968750                0.000000                 0.000000

[77504 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:41:50 to 1970-01-01 01:41:50.500000 for index 5020
calculating features from 782080 to 782143 for index 5020
processed hour 1 - start: 460800 | end: 782183
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.003610                 0.007658
1970-01-01 01:00:00.062500                0.000000                 0.010210
1970-01-01 01:00:00.125000                0.003610                 0.007658
1970-01-01 01:00:00.187500                0.003610                 0.007658
1970-01-01 01:00:00.250000                0.003610                 0.007658
...                                            ...                      ...
1970-01-01 01:41:50.500000                0.000314                 0.000222
1970-01-01 01:41:50.562500                0.000314                 0.000222
1970-01-01 01:41:50.625000                0.000314                 0.000222
1970-01-01 01:41:50.687500                0.000314                 0.000222
1970-01-01 01:41:50.750000                0.000000                 0.000000

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.014440
1970-01-01 01:00:00.062500                0.010830
1970-01-01 01:00:00.125000                0.010830
1970-01-01 01:00:00.187500                0.009025
1970-01-01 01:00:00.250000                0.007220
...                                            ...
1970-01-01 01:41:50.500000                0.000157
1970-01-01 01:41:50.562500                0.000157
1970-01-01 01:41:50.625000                0.000157
1970-01-01 01:41:50.687500                0.000157
1970-01-01 01:41:50.750000                0.000000

[40173 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.003610                 0.007658
1970-01-01 01:00:00.031250                0.003610                 0.007658
1970-01-01 01:00:00.062500                0.000000                 0.010210
1970-01-01 01:00:00.093750                0.000000                 0.005105
1970-01-01 01:00:00.125000                0.003610                 0.007658
...                                            ...                      ...
1970-01-01 01:41:50.656250                0.000314                 0.000222
1970-01-01 01:41:50.687500                0.000000                 0.000000
1970-01-01 01:41:50.718750                0.000314                 0.000222
1970-01-01 01:41:50.750000                0.000000                 0.000000
1970-01-01 01:41:50.781250                0.000000                 0.000000

[80346 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:44:23.500000 to 1970-01-01 01:44:24 for index 5327
calculating features from 801728 to 801791 for index 5327
processed hour 1 - start: 460800 | end: 801822
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.001036                 0.000000
1970-01-01 01:00:00.062500                0.001036                 0.002198
1970-01-01 01:00:00.125000                0.001036                 0.000733
1970-01-01 01:00:00.187500                0.001036                 0.000733
1970-01-01 01:00:00.250000                0.001036                 0.000733
...                                            ...                      ...
1970-01-01 01:44:23.937500                0.003108                 0.010989
1970-01-01 01:44:24.000000                0.001036                 0.001465
1970-01-01 01:44:24.062500                0.000000                 0.000000
1970-01-01 01:44:24.125000                0.001036                 0.001465
1970-01-01 01:44:24.187500                0.001036                 0.000733

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.001036
1970-01-01 01:00:00.062500                0.003626
1970-01-01 01:00:00.125000                0.000000
1970-01-01 01:00:00.187500                0.001036
1970-01-01 01:00:00.250000                0.000518
...                                            ...
1970-01-01 01:44:23.937500                0.017095
1970-01-01 01:44:24.000000                0.002590
1970-01-01 01:44:24.062500                0.002072
1970-01-01 01:44:24.125000                0.001554
1970-01-01 01:44:24.187500                0.001554

[42628 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.000000                 0.000000
1970-01-01 01:00:00.031250                0.001036                 0.000000
1970-01-01 01:00:00.062500                0.001036                 0.002198
1970-01-01 01:00:00.093750                0.001036                 0.000000
1970-01-01 01:00:00.125000                0.001036                 0.000733
...                                            ...                      ...
1970-01-01 01:44:24.093750                0.000000                 0.000000
1970-01-01 01:44:24.125000                0.001036                 0.000733
1970-01-01 01:44:24.156250                0.000000                 0.001465
1970-01-01 01:44:24.187500                0.001036                 0.000733
1970-01-01 01:44:24.218750                0.000000                 0.000000

[85256 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:45:24 to 1970-01-01 01:45:24.500000 for index 5448
calculating features from 809472 to 809535 for index 5448
processed hour 1 - start: 460800 | end: 809574
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.002072                 0.007326
1970-01-01 01:00:00.062500                0.003108                 0.004396
1970-01-01 01:00:00.125000                0.001036                 0.001465
1970-01-01 01:00:00.187500                0.001036                 0.005861
1970-01-01 01:00:00.250000                0.003108                 0.002198
...                                            ...                      ...
1970-01-01 01:45:24.500000                0.011397                 0.001465
1970-01-01 01:45:24.562500                0.010361                 0.004396
1970-01-01 01:45:24.625000                0.011397                 0.004396
1970-01-01 01:45:24.687500                0.011397                 0.011722
1970-01-01 01:45:24.750000                0.007252                 0.010989

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.002072
1970-01-01 01:00:00.062500                0.005180
1970-01-01 01:00:00.125000                0.005698
1970-01-01 01:00:00.187500                0.003626
1970-01-01 01:00:00.250000                0.007770
...                                            ...
1970-01-01 01:45:24.500000                0.002590
1970-01-01 01:45:24.562500                0.005180
1970-01-01 01:45:24.625000                0.002072
1970-01-01 01:45:24.687500                0.004662
1970-01-01 01:45:24.750000                0.007770

[43597 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.000000                 0.004396
1970-01-01 01:00:00.031250                0.002072                 0.007326
1970-01-01 01:00:00.062500                0.000000                 0.004396
1970-01-01 01:00:00.093750                0.003108                 0.004396
1970-01-01 01:00:00.125000                0.001036                 0.001465
...                                            ...                      ...
1970-01-01 01:45:24.656250                0.011397                 0.001465
1970-01-01 01:45:24.687500                0.011397                 0.000733
1970-01-01 01:45:24.718750                0.011397                 0.011722
1970-01-01 01:45:24.750000                0.007252                 0.010989
1970-01-01 01:45:24.781250                0.001036                 0.000000

[87194 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:48:34.500000 to 1970-01-01 01:48:35 for index 5829
calculating features from 833856 to 833919 for index 5829
processed hour 1 - start: 460800 | end: 833932
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                 0.00361                 0.012763
1970-01-01 01:00:00.062500                 0.00361                 0.010210
1970-01-01 01:00:00.125000                 0.01444                 0.030631
1970-01-01 01:00:00.187500                 0.01083                 0.022974
1970-01-01 01:00:00.250000                 0.00722                 0.007658
...                                            ...                      ...
1970-01-01 01:48:34.812500                 0.01444                 0.017868
1970-01-01 01:48:34.875000                 0.00722                 0.015316
1970-01-01 01:48:34.937500                 0.00722                 0.005105
1970-01-01 01:48:35.000000                 0.00361                 0.002553
1970-01-01 01:48:35.062500                 0.00361                 0.002553

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.028880
1970-01-01 01:00:00.062500                0.032489
1970-01-01 01:00:00.125000                0.095664
1970-01-01 01:00:00.187500                0.083029
1970-01-01 01:00:00.250000                0.009025
...                                            ...
1970-01-01 01:48:34.812500                0.072199
1970-01-01 01:48:34.875000                0.021660
1970-01-01 01:48:34.937500                0.009025
1970-01-01 01:48:35.000000                0.005415
1970-01-01 01:48:35.062500                0.000000

[46642 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                 0.00361                 0.012763
1970-01-01 01:00:00.031250                 0.00361                 0.012763
1970-01-01 01:00:00.062500                 0.00000                 0.010210
1970-01-01 01:00:00.093750                 0.00361                 0.010210
1970-01-01 01:00:00.125000                 0.01444                 0.030631
...                                            ...                      ...
1970-01-01 01:48:34.968750                 0.00722                 0.002553
1970-01-01 01:48:35.000000                 0.00361                 0.000000
1970-01-01 01:48:35.031250                 0.00361                 0.002553
1970-01-01 01:48:35.062500                 0.00361                 0.002553
1970-01-01 01:48:35.093750                 0.00000                 0.000000

[93284 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:48:25.500000 to 1970-01-01 01:48:26 for index 5811
calculating features from 832704 to 832767 for index 5811
processed hour 1 - start: 460800 | end: 832830
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.012433                 0.011722
1970-01-01 01:00:00.062500                0.010361                 0.011722
1970-01-01 01:00:00.125000                0.010361                 0.010256
1970-01-01 01:00:00.187500                0.011397                 0.008791
1970-01-01 01:00:00.250000                0.010361                 0.010256
...                                            ...                      ...
1970-01-01 01:48:26.187500                0.017613                 0.013187
1970-01-01 01:48:26.250000                0.018649                 0.032234
1970-01-01 01:48:26.312500                0.016577                 0.011722
1970-01-01 01:48:26.375000                0.014505                 0.010256
1970-01-01 01:48:26.437500                0.013469                 0.009524

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.005180
1970-01-01 01:00:00.062500                0.001554
1970-01-01 01:00:00.125000                0.002590
1970-01-01 01:00:00.187500                0.000518
1970-01-01 01:00:00.250000                0.002072
...                                            ...
1970-01-01 01:48:26.187500                0.004662
1970-01-01 01:48:26.250000                0.030564
1970-01-01 01:48:26.312500                0.005698
1970-01-01 01:48:26.375000                0.011915
1970-01-01 01:48:26.437500                0.012951

[46504 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.012433                 0.011722
1970-01-01 01:00:00.031250                0.007252                 0.002930
1970-01-01 01:00:00.062500                0.009324                 0.008059
1970-01-01 01:00:00.093750                0.010361                 0.011722
1970-01-01 01:00:00.125000                0.008288                 0.010256
...                                            ...                      ...
1970-01-01 01:48:26.343750                0.009324                 0.002198
1970-01-01 01:48:26.375000                0.014505                 0.010256
1970-01-01 01:48:26.406250                0.011397                 0.005128
1970-01-01 01:48:26.437500                0.012433                 0.009524
1970-01-01 01:48:26.468750                0.013469                 0.000000

[93008 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:57:31 to 1970-01-01 01:57:31.500000 for index 6902
calculating features from 902528 to 902591 for index 6902
processed hour 1 - start: 460800 | end: 902598
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.010361                 0.002930
1970-01-01 01:00:00.062500                0.007252                 0.007326
1970-01-01 01:00:00.125000                0.011397                 0.001465
1970-01-01 01:00:00.187500                0.012433                 0.005861
1970-01-01 01:00:00.250000                0.013469                 0.003663
...                                            ...                      ...
1970-01-01 01:57:31.250000                0.003140                 0.001776
1970-01-01 01:57:31.312500                0.004081                 0.001776
1970-01-01 01:57:31.375000                0.003767                 0.002220
1970-01-01 01:57:31.437500                0.004081                 0.001998
1970-01-01 01:57:31.500000                0.003140                 0.000444

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.004662
1970-01-01 01:00:00.062500                0.002072
1970-01-01 01:00:00.125000                0.000000
1970-01-01 01:00:00.187500                0.007252
1970-01-01 01:00:00.250000                0.003108
...                                            ...
1970-01-01 01:57:31.250000                0.001570
1970-01-01 01:57:31.312500                0.001884
1970-01-01 01:57:31.375000                0.000942
1970-01-01 01:57:31.437500                0.001570
1970-01-01 01:57:31.500000                0.002826

[55225 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.010361                 0.002930
1970-01-01 01:00:00.031250                0.009324                 0.002198
1970-01-01 01:00:00.062500                0.005180                 0.004396
1970-01-01 01:00:00.093750                0.007252                 0.007326
1970-01-01 01:00:00.125000                0.011397                 0.001465
...                                            ...                      ...
1970-01-01 01:57:31.406250                0.003767                 0.002220
1970-01-01 01:57:31.437500                0.004081                 0.001554
1970-01-01 01:57:31.468750                0.002826                 0.001998
1970-01-01 01:57:31.500000                0.003140                 0.000444
1970-01-01 01:57:31.531250                0.000000                 0.000000

[110450 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.005698                0.004029
1970-01-01 00:00:00.500               0.000314                0.000888
1970-01-01 00:00:01.000               0.000628                0.000888
1970-01-01 00:00:01.500               0.002198                0.003774
1970-01-01 00:00:02.000               0.000628                0.002220
...                                        ...                     ...
1970-01-01 00:59:57.500               0.003610                0.005105
1970-01-01 00:59:58.000               0.003610                0.005105
1970-01-01 00:59:58.500               0.010830                0.025526
1970-01-01 00:59:59.000               0.003610                0.002553
1970-01-01 00:59:59.500               0.007220                0.020421

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.013320
1970-01-01 00:00:00.500               0.000157
1970-01-01 00:00:01.000               0.001727
1970-01-01 00:00:01.500               0.002041
1970-01-01 00:00:02.000               0.000314
...                                        ...
1970-01-01 00:59:57.500               0.000000
1970-01-01 00:59:58.000               0.007220
1970-01-01 00:59:58.500               0.055954
1970-01-01 00:59:59.000               0.005415
1970-01-01 00:59:59.500               0.057759

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.005698                0.004029
1970-01-01 00:00:00.250               0.000314                0.000222
1970-01-01 00:00:00.500               0.000000                0.000888
1970-01-01 00:00:00.750               0.000314                0.000666
1970-01-01 00:00:01.000               0.000314                0.000888
...                                        ...                     ...
1970-01-01 00:59:58.750               0.010830                0.025526
1970-01-01 00:59:59.000               0.000000                0.000000
1970-01-01 00:59:59.250               0.003610                0.002553
1970-01-01 00:59:59.500               0.007220                0.020421
1970-01-01 00:59:59.750               0.007220                0.020421

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.004662                0.003297
1970-01-01 00:00:00.500               0.002826                0.000888
1970-01-01 00:00:01.000               0.000942                0.001332
1970-01-01 00:00:01.500               0.001570                0.001332
1970-01-01 00:00:02.000               0.000628                0.000444
...                                        ...                     ...
1970-01-01 00:59:57.500               0.000314                0.000000
1970-01-01 00:59:58.000               0.000314                0.000222
1970-01-01 00:59:58.500               0.000314                0.001332
1970-01-01 00:59:59.000               0.000314                0.000222
1970-01-01 00:59:59.500               0.000314                0.000888

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.008500
1970-01-01 00:00:00.500               0.000471
1970-01-01 00:00:01.000               0.000785
1970-01-01 00:00:01.500               0.001570
1970-01-01 00:00:02.000               0.000314
...                                        ...
1970-01-01 00:59:57.500               0.000314
1970-01-01 00:59:58.000               0.000471
1970-01-01 00:59:58.500               0.000942
1970-01-01 00:59:59.000               0.001570
1970-01-01 00:59:59.500               0.000000

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.004662                0.003297
1970-01-01 00:00:00.250               0.001884                0.001998
1970-01-01 00:00:00.500               0.002826                0.000888
1970-01-01 00:00:00.750               0.000942                0.000666
1970-01-01 00:00:01.000               0.000314                0.001332
...                                        ...                     ...
1970-01-01 00:59:58.750               0.000000                0.000444
1970-01-01 00:59:59.000               0.000314                0.000222
1970-01-01 00:59:59.250               0.000314                0.000222
1970-01-01 00:59:59.500               0.000314                0.000888
1970-01-01 00:59:59.750               0.000314                0.000000

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
1970-01-01 00:00:01.500               0.000000                0.000000
1970-01-01 00:00:02.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:57.500               0.014505                0.013919
1970-01-01 00:59:58.000               0.009324                0.012454
1970-01-01 00:59:58.500               0.016577                0.010989
1970-01-01 00:59:59.000               0.016577                0.007326
1970-01-01 00:59:59.500               0.009324                0.025641

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.000314
1970-01-01 00:00:00.500               0.000000
1970-01-01 00:00:01.000               0.000000
1970-01-01 00:00:01.500               0.000000
1970-01-01 00:00:02.000               0.000000
...                                        ...
1970-01-01 00:59:57.500               0.035226
1970-01-01 00:59:58.000               0.001036
1970-01-01 00:59:58.500               0.036780
1970-01-01 00:59:59.000               0.001036
1970-01-01 00:59:59.500               0.053357

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.250               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.004144                0.010989
1970-01-01 00:59:59.000               0.016577                0.007326
1970-01-01 00:59:59.250               0.007252                0.001465
1970-01-01 00:59:59.500               0.006216                0.002930
1970-01-01 00:59:59.750               0.009324                0.025641

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.109933                0.058861
1970-01-01 00:00:00.500               0.005180                0.003663
1970-01-01 00:00:01.000               0.001036                0.002198
1970-01-01 00:00:01.500               0.001036                0.002198
1970-01-01 00:00:02.000               0.002072                0.002930
...                                        ...                     ...
1970-01-01 00:59:57.500               0.005180                0.013919
1970-01-01 00:59:58.000               0.004144                0.013919
1970-01-01 00:59:58.500               0.004144                0.002930
1970-01-01 00:59:59.000               0.002072                0.004396
1970-01-01 00:59:59.500               0.005180                0.005861

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.013895
1970-01-01 00:00:00.500               0.005698
1970-01-01 00:00:01.000               0.012951
1970-01-01 00:00:01.500               0.006216
1970-01-01 00:00:02.000               0.009843
...                                        ...
1970-01-01 00:59:57.500               0.031082
1970-01-01 00:59:58.000               0.039888
1970-01-01 00:59:58.500               0.006216
1970-01-01 00:59:59.000               0.006216
1970-01-01 00:59:59.500               0.016577

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.109933                0.058861
1970-01-01 00:00:00.250               0.006216                0.001465
1970-01-01 00:00:00.500               0.005180                0.002930
1970-01-01 00:00:00.750               0.003108                0.003663
1970-01-01 00:00:01.000               0.001036                0.002198
...                                        ...                     ...
1970-01-01 00:59:58.750               0.001036                0.001465
1970-01-01 00:59:59.000               0.001036                0.000000
1970-01-01 00:59:59.250               0.002072                0.004396
1970-01-01 00:59:59.500               0.005180                0.005861
1970-01-01 00:59:59.750               0.005180                0.002930

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
1970-01-01 00:00:01.500               0.000000                0.000000
1970-01-01 00:00:02.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:57.500               0.011397                0.010256
1970-01-01 00:59:58.000               0.013469                0.006593
1970-01-01 00:59:58.500               0.002072                0.004396
1970-01-01 00:59:59.000               0.054911                0.016850
1970-01-01 00:59:59.500               0.012433                0.030037

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.000314
1970-01-01 00:00:00.500               0.000000
1970-01-01 00:00:01.000               0.000000
1970-01-01 00:00:01.500               0.000000
1970-01-01 00:00:02.000               0.000000
...                                        ...
1970-01-01 00:59:57.500               0.002590
1970-01-01 00:59:58.000               0.005180
1970-01-01 00:59:58.500               0.010361
1970-01-01 00:59:59.000               0.174575
1970-01-01 00:59:59.500               0.034190

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.250               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.002072                0.004396
1970-01-01 00:59:59.000               0.010361                0.005861
1970-01-01 00:59:59.250               0.054911                0.016850
1970-01-01 00:59:59.500               0.012433                0.010989
1970-01-01 00:59:59.750               0.007252                0.030037

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
1970-01-01 00:00:01.500               0.000000                0.000000
1970-01-01 00:00:02.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:57.500               0.004144                0.008791
1970-01-01 00:59:58.000               0.007252                0.002930
1970-01-01 00:59:58.500               0.004144                0.009524
1970-01-01 00:59:59.000               0.004144                0.006593
1970-01-01 00:59:59.500               0.002072                0.001465

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.000314
1970-01-01 00:00:00.500               0.000000
1970-01-01 00:00:01.000               0.000000
1970-01-01 00:00:01.500               0.000000
1970-01-01 00:00:02.000               0.000000
...                                        ...
1970-01-01 00:59:57.500               0.009843
1970-01-01 00:59:58.000               0.018649
1970-01-01 00:59:58.500               0.009843
1970-01-01 00:59:59.000               0.001554
1970-01-01 00:59:59.500               0.001036

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.250               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.004144                0.005861
1970-01-01 00:59:59.000               0.004144                0.004396
1970-01-01 00:59:59.250               0.003108                0.006593
1970-01-01 00:59:59.500               0.002072                0.000000
1970-01-01 00:59:59.750               0.002072                0.001465

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.137070                0.092641
1970-01-01 00:00:00.500               0.001256                0.002442
1970-01-01 00:00:01.000               0.000314                0.001332
1970-01-01 00:00:01.500               0.000314                0.000666
1970-01-01 00:00:02.000               0.000314                0.000666
...                                        ...                     ...
1970-01-01 00:59:57.500               0.003610                0.012763
1970-01-01 00:59:58.000               0.003610                0.010210
1970-01-01 00:59:58.500               0.003610                0.010210
1970-01-01 00:59:59.000               0.007220                0.007658
1970-01-01 00:59:59.500               0.014440                0.035737

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.050661
1970-01-01 00:00:00.500               0.005965
1970-01-01 00:00:01.000               0.002355
1970-01-01 00:00:01.500               0.000471
1970-01-01 00:00:02.000               0.001256
...                                        ...
1970-01-01 00:59:57.500               0.030685
1970-01-01 00:59:58.000               0.025270
1970-01-01 00:59:58.500               0.019855
1970-01-01 00:59:59.000               0.003610
1970-01-01 00:59:59.500               0.088444

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.137070                0.092641
1970-01-01 00:00:00.250               0.001256                0.002442
1970-01-01 00:00:00.500               0.001256                0.002442
1970-01-01 00:00:00.750               0.000628                0.001998
1970-01-01 00:00:01.000               0.000314                0.001332
...                                        ...                     ...
1970-01-01 00:59:58.750               0.003610                0.010210
1970-01-01 00:59:59.000               0.003610                0.007658
1970-01-01 00:59:59.250               0.007220                0.007658
1970-01-01 00:59:59.500               0.010830                0.022974
1970-01-01 00:59:59.750               0.014440                0.035737

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.004662                0.003297
1970-01-01 00:00:00.500               0.000314                0.000222
1970-01-01 00:00:01.000               0.000314                0.000444
1970-01-01 00:00:01.500               0.000314                0.000444
1970-01-01 00:00:02.000               0.001256                0.000444
...                                        ...                     ...
1970-01-01 00:59:57.500               0.002072                0.005128
1970-01-01 00:59:58.000               0.003108                0.002198
1970-01-01 00:59:58.500               0.005180                0.011722
1970-01-01 00:59:59.000               0.008288                0.011722
1970-01-01 00:59:59.500               0.003108                0.006593

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.009913
1970-01-01 00:00:00.500               0.000157
1970-01-01 00:00:01.000               0.000314
1970-01-01 00:00:01.500               0.000942
1970-01-01 00:00:02.000               0.000785
...                                        ...
1970-01-01 00:59:57.500               0.009843
1970-01-01 00:59:58.000               0.007252
1970-01-01 00:59:58.500               0.002590
1970-01-01 00:59:59.000               0.025901
1970-01-01 00:59:59.500               0.016577

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.004662                0.003297
1970-01-01 00:00:00.250               0.000314                0.000444
1970-01-01 00:00:00.500               0.000314                0.000222
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000444
...                                        ...                     ...
1970-01-01 00:59:58.750               0.002072                0.008059
1970-01-01 00:59:59.000               0.003108                0.008791
1970-01-01 00:59:59.250               0.008288                0.011722
1970-01-01 00:59:59.500               0.003108                0.006593
1970-01-01 00:59:59.750               0.002072                0.005128

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.001256                0.000888
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
1970-01-01 00:00:01.500               0.001256                0.000888
1970-01-01 00:00:02.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:57.500               0.003108                0.001465
1970-01-01 00:59:58.000               0.001036                0.002198
1970-01-01 00:59:58.500               0.001036                0.002198
1970-01-01 00:59:59.000               0.004144                0.006593
1970-01-01 00:59:59.500               0.005180                0.009524

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.000942
1970-01-01 00:00:00.500               0.000000
1970-01-01 00:00:01.000               0.000000
1970-01-01 00:00:01.500               0.000628
1970-01-01 00:00:02.000               0.000000
...                                        ...
1970-01-01 00:59:57.500               0.004662
1970-01-01 00:59:58.000               0.000518
1970-01-01 00:59:58.500               0.003626
1970-01-01 00:59:59.000               0.002590
1970-01-01 00:59:59.500               0.023311

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.250               0.001256                0.000888
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.000000                0.000000
1970-01-01 00:59:59.000               0.004144                0.002930
1970-01-01 00:59:59.250               0.002072                0.006593
1970-01-01 00:59:59.500               0.002072                0.009524
1970-01-01 00:59:59.750               0.005180                0.007326

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.004662                0.003297
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
1970-01-01 00:00:01.500               0.000000                0.000000
1970-01-01 00:00:02.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:57.500               0.003610                0.015316
1970-01-01 00:59:58.000               0.003610                0.005105
1970-01-01 00:59:58.500               0.000000                0.000000
1970-01-01 00:59:59.000               0.003610                0.002553
1970-01-01 00:59:59.500               0.036099                0.030631

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.012111
1970-01-01 00:00:00.500               0.000000
1970-01-01 00:00:01.000               0.000000
1970-01-01 00:00:01.500               0.000000
1970-01-01 00:00:02.000               0.000000
...                                        ...
1970-01-01 00:59:57.500               0.007220
1970-01-01 00:59:58.000               0.012635
1970-01-01 00:59:58.500               0.007220
1970-01-01 00:59:59.000               0.001805
1970-01-01 00:59:59.500               0.048734

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.004662                0.003297
1970-01-01 00:00:00.250               0.000628                0.000444
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.000000                0.000000
1970-01-01 00:59:59.000               0.003610                0.002553
1970-01-01 00:59:59.250               0.000000                0.000000
1970-01-01 00:59:59.500               0.021660                0.007658
1970-01-01 00:59:59.750               0.036099                0.030631

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
1970-01-01 00:00:01.500               0.000000                0.000000
1970-01-01 00:00:02.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:57.500               0.002072                0.000733
1970-01-01 00:59:58.000               0.001036                0.000733
1970-01-01 00:59:58.500               0.006216                0.000733
1970-01-01 00:59:59.000               0.001036                0.000733
1970-01-01 00:59:59.500               0.000000                0.001465

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.000314
1970-01-01 00:00:00.500               0.000000
1970-01-01 00:00:01.000               0.000000
1970-01-01 00:00:01.500               0.000000
1970-01-01 00:00:02.000               0.000000
...                                        ...
1970-01-01 00:59:57.500               0.002072
1970-01-01 00:59:58.000               0.003108
1970-01-01 00:59:58.500               0.003108
1970-01-01 00:59:59.000               0.000518
1970-01-01 00:59:59.500               0.001036

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.250               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.001036                0.000733
1970-01-01 00:59:59.000               0.001036                0.000000
1970-01-01 00:59:59.250               0.001036                0.000733
1970-01-01 00:59:59.500               0.000000                0.001465
1970-01-01 00:59:59.750               0.000000                0.000000

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 01:27:33 to 1970-01-01 01:27:33.500000 for index 3306
calculating features from 84048 to 84055 for index 3306
processed hour 1 - start: 57600 | end: 84061
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.007220                0.015316
1970-01-01 01:00:00.500               0.003610                0.002553
1970-01-01 01:00:01.000               0.003610                0.012763
1970-01-01 01:00:01.500               0.003610                0.010210
1970-01-01 01:00:02.000               0.003610                0.005105
...                                        ...                     ...
1970-01-01 01:27:31.500               0.018050                0.051052
1970-01-01 01:27:32.000               0.021660                0.035737
1970-01-01 01:27:32.500               0.028880                0.084236
1970-01-01 01:27:33.000               0.191327                0.119973
1970-01-01 01:27:33.500               0.133568                0.224630

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.025270
1970-01-01 01:00:00.500               0.007220
1970-01-01 01:00:01.000               0.028880
1970-01-01 01:00:01.500               0.027075
1970-01-01 01:00:02.000               0.014440
...                                        ...
1970-01-01 01:27:31.500               0.129958
1970-01-01 01:27:32.000               0.019855
1970-01-01 01:27:32.500               0.223817
1970-01-01 01:27:33.000               0.032489
1970-01-01 01:27:33.500               0.588421

[3308 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.007220                0.015316
1970-01-01 01:00:00.250               0.003610                0.005105
1970-01-01 01:00:00.500               0.003610                0.002553
1970-01-01 01:00:00.750               0.003610                0.002553
1970-01-01 01:00:01.000               0.003610                0.007658
...                                        ...                     ...
1970-01-01 01:27:32.750               0.028880                0.038289
1970-01-01 01:27:33.000               0.039709                0.053605
1970-01-01 01:27:33.250               0.191327                0.119973
1970-01-01 01:27:33.500               0.133568                0.224630
1970-01-01 01:27:33.750               0.000000                0.000000

[6616 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000    0.000000     -0.200463    0.0  2.106994e-20       1.0
1          0.007812    0.000000     -0.200463    0.0  1.879714e-06       1.0
2          0.015625    0.000000     -0.200463    0.0  3.656027e-06       1.0
3          0.023438    0.000000     -0.200463    0.0  5.370973e-06       1.0
4          0.031250    0.000000     -0.200463    0.0  7.062509e-06       1.0
...             ...         ...           ...    ...           ...       ...
778459  6081.710938    1.502564      1.502564    0.0  1.502564e+00       0.0
778460  6081.718750    1.499634      1.499634    0.0  1.499634e+00       0.0
778461  6081.726562    1.499634      1.499634    0.0  1.499634e+00       0.0
778462  6081.734375    1.505495      1.505495    0.0  1.505495e+00       0.0
778463  6081.742188    1.511355      1.511355    0.0  1.511355e+00       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
778459                 0.0
778460                 0.0
778461                 0.0
778462                 0.0
778463                 0.0

[778464 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
1970-01-01 00:00:01.500               0.000000                0.000000
1970-01-01 00:00:02.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:57.500               0.005180                0.003663
1970-01-01 00:59:58.000               0.005180                0.003663
1970-01-01 00:59:58.500               0.010361                0.011722
1970-01-01 00:59:59.000               0.000000                0.001465
1970-01-01 00:59:59.500               0.008288                0.001465

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.000314
1970-01-01 00:00:00.500               0.000000
1970-01-01 00:00:01.000               0.000000
1970-01-01 00:00:01.500               0.000000
1970-01-01 00:00:02.000               0.000000
...                                        ...
1970-01-01 00:59:57.500               0.002072
1970-01-01 00:59:58.000               0.002590
1970-01-01 00:59:58.500               0.002590
1970-01-01 00:59:59.000               0.001036
1970-01-01 00:59:59.500               0.007770

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.250               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.001036                0.000733
1970-01-01 00:59:59.000               0.000000                0.001465
1970-01-01 00:59:59.250               0.000000                0.000000
1970-01-01 00:59:59.500               0.008288                0.001465
1970-01-01 00:59:59.750               0.001036                0.000733

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 01:34:28 to 1970-01-01 01:34:28.500000 for index 4136
calculating features from 90688 to 90695 for index 4136
processed hour 1 - start: 57600 | end: 90704
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.000628                0.000222
1970-01-01 01:00:00.500               0.000628                0.000444
1970-01-01 01:00:01.000               0.000628                0.000444
1970-01-01 01:00:01.500               0.000628                0.000222
1970-01-01 01:00:02.000               0.000628                0.000444
...                                        ...                     ...
1970-01-01 01:34:26.500               0.005180                0.013187
1970-01-01 01:34:27.000               0.005180                0.010256
1970-01-01 01:34:27.500               0.011397                0.006593
1970-01-01 01:34:28.000               0.001036                0.000000
1970-01-01 01:34:28.500               0.001036                0.000733

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.000314
1970-01-01 01:00:00.500               0.000785
1970-01-01 01:00:01.000               0.000471
1970-01-01 01:00:01.500               0.000471
1970-01-01 01:00:02.000               0.000314
...                                        ...
1970-01-01 01:34:26.500               0.009843
1970-01-01 01:34:27.000               0.023829
1970-01-01 01:34:27.500               0.014505
1970-01-01 01:34:28.000               0.001036
1970-01-01 01:34:28.500               0.001554

[4138 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.000628                0.000222
1970-01-01 01:00:00.250               0.000628                0.000222
1970-01-01 01:00:00.500               0.000628                0.000444
1970-01-01 01:00:00.750               0.000628                0.000222
1970-01-01 01:00:01.000               0.000628                0.000222
...                                        ...                     ...
1970-01-01 01:34:27.750               0.005180                0.006593
1970-01-01 01:34:28.000               0.001036                0.000000
1970-01-01 01:34:28.250               0.000000                0.000000
1970-01-01 01:34:28.500               0.001036                0.000733
1970-01-01 01:34:28.750               0.000000                0.000000

[8276 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label  auto_signal  pred_art  \
0          0.000000    1.184553      1.184553    0.0     1.184553       0.0
1          0.007812    1.184553      1.184553    0.0     1.184553       0.0
2          0.015625    1.184553      1.184553    0.0     1.184553       0.0
3          0.023438    1.184553      1.184553    0.0     1.184553       0.0
4          0.031250    1.184553      1.184553    0.0     1.184553       0.0
...             ...         ...           ...    ...          ...       ...
756466  5909.890625    5.914411      5.914411    0.0     5.914411       0.0
756467  5909.898438    5.914411      5.914411    0.0     5.914411       0.0
756468  5909.906250    5.919516      5.919516    0.0     5.919516       0.0
756469  5909.914062    5.919516      5.919516    0.0     5.919516       0.0
756470  5909.921875    5.914411      5.914411    0.0     5.914411       0.0

        post_proc_pred_art
0                      0.0
1                      0.0
2                      0.0
3                      0.0
4                      0.0
...                    ...
756466                 0.0
756467                 0.0
756468                 0.0
756469                 0.0
756470                 0.0

[756471 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 01:35:18.500000 to 1970-01-01 01:35:19 for index 4237
calculating features from 91496 to 91503 for index 4237
processed hour 1 - start: 57600 | end: 91507
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.014505                0.035897
1970-01-01 01:00:00.500               0.004144                0.018315
1970-01-01 01:00:01.000               0.008288                0.004396
1970-01-01 01:00:01.500               0.012433                0.017582
1970-01-01 01:00:02.000               0.005180                0.009524
...                                        ...                     ...
1970-01-01 01:35:17.000               0.007220                0.030631
1970-01-01 01:35:17.500               0.010830                0.007658
1970-01-01 01:35:18.000               0.043319                0.063815
1970-01-01 01:35:18.500               0.025270                0.045947
1970-01-01 01:35:19.000               0.014440                0.030631

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.091173
1970-01-01 01:00:00.500               0.043514
1970-01-01 01:00:01.000               0.007770
1970-01-01 01:00:01.500               0.023829
1970-01-01 01:00:02.000               0.027973
...                                        ...
1970-01-01 01:35:17.000               0.068589
1970-01-01 01:35:17.500               0.046929
1970-01-01 01:35:18.000               0.151618
1970-01-01 01:35:18.500               0.124543
1970-01-01 01:35:19.000               0.000000

[4239 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.012433                0.028571
1970-01-01 01:00:00.250               0.014505                0.035897
1970-01-01 01:00:00.500               0.004144                0.018315
1970-01-01 01:00:00.750               0.002072                0.013919
1970-01-01 01:00:01.000               0.007252                0.002198
...                                        ...                     ...
1970-01-01 01:35:18.250               0.043319                0.063815
1970-01-01 01:35:18.500               0.014440                0.038289
1970-01-01 01:35:18.750               0.025270                0.045947
1970-01-01 01:35:19.000               0.014440                0.030631
1970-01-01 01:35:19.250               0.000000                0.000000

[8478 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000    0.000000     -0.091119    0.0  2.168404e-18       1.0
1          0.007812    0.000000     -0.091119    0.0  4.942970e-05       1.0
2          0.015625    0.000000     -0.091119    0.0  9.842421e-05       1.0
3          0.023438    0.000000     -0.091119    0.0  1.469855e-04       1.0
4          0.031250    0.000000     -0.091119    0.0  1.951154e-04       1.0
...             ...         ...           ...    ...           ...       ...
884962  6913.765625    3.616850      3.616850    0.0  3.616850e+00       0.0
884963  6913.773438    3.618315      3.618315    0.0  3.618315e+00       0.0
884964  6913.781250    3.618315      3.618315    0.0  3.618315e+00       0.0
884965  6913.789062    3.618315      3.618315    0.0  3.618315e+00       0.0
884966  6913.796875    3.618315      3.618315    0.0  3.618315e+00       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
884962                 0.0
884963                 0.0
884964                 0.0
884965                 0.0
884966                 0.0

[884967 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 01:37:37 to 1970-01-01 01:37:37.500000 for index 4514
calculating features from 93712 to 93719 for index 4514
processed hour 1 - start: 57600 | end: 93722
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.004144                0.008791
1970-01-01 01:00:00.500               0.005180                0.006593
1970-01-01 01:00:01.000               0.004144                0.007326
1970-01-01 01:00:01.500               0.002072                0.005128
1970-01-01 01:00:02.000               0.003108                0.007326
...                                        ...                     ...
1970-01-01 01:37:35.500               0.000000                0.000000
1970-01-01 01:37:36.000               0.000000                0.000000
1970-01-01 01:37:36.500               0.000000                0.000000
1970-01-01 01:37:37.000               0.000000                0.000000
1970-01-01 01:37:37.500               0.000000                0.000000

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.022275
1970-01-01 01:00:00.500               0.016059
1970-01-01 01:00:01.000               0.021239
1970-01-01 01:00:01.500               0.013469
1970-01-01 01:00:02.000               0.018649
...                                        ...
1970-01-01 01:37:35.500               0.000000
1970-01-01 01:37:36.000               0.000000
1970-01-01 01:37:36.500               0.000000
1970-01-01 01:37:37.000               0.000000
1970-01-01 01:37:37.500               0.000000

[4516 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.004144                0.008791
1970-01-01 01:00:00.250               0.003108                0.005128
1970-01-01 01:00:00.500               0.005180                0.004396
1970-01-01 01:00:00.750               0.002072                0.006593
1970-01-01 01:00:01.000               0.004144                0.007326
...                                        ...                     ...
1970-01-01 01:37:36.750               0.000000                0.000000
1970-01-01 01:37:37.000               0.000000                0.000000
1970-01-01 01:37:37.250               0.000000                0.000000
1970-01-01 01:37:37.500               0.000000                0.000000
1970-01-01 01:37:37.750               0.000000                0.000000

[9032 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label  auto_signal  pred_art  \
0          0.000000    0.054672      0.054672    0.0     0.054672       0.0
1          0.007812    0.054672      0.054672    0.0     0.054672       0.0
2          0.015625    0.054672      0.054672    0.0     0.054672       0.0
3          0.023438    0.054672      0.054672    0.0     0.054672       0.0
4          0.031250    0.054672      0.054672    0.0     0.054672       0.0
...             ...         ...           ...    ...          ...       ...
817321  6385.320312    9.804597      9.804597    0.0     9.804597       0.0
817322  6385.328125    9.799492      9.799492    0.0     9.799492       0.0
817323  6385.335938    9.794387      9.794387    0.0     9.794387       0.0
817324  6385.343750    9.794387      9.794387    0.0     9.794387       0.0
817325  6385.351562    9.789282      9.789282    0.0     9.789282       0.0

        post_proc_pred_art
0                      0.0
1                      0.0
2                      0.0
3                      0.0
4                      0.0
...                    ...
817321                 0.0
817322                 0.0
817323                 0.0
817324                 0.0
817325                 0.0

[817326 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 01:38:20 to 1970-01-01 01:38:20.500000 for index 4600
calculating features from 94400 to 94407 for index 4600
processed hour 1 - start: 57600 | end: 94414
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.040406                0.052747
1970-01-01 01:00:00.500               0.010361                0.012454
1970-01-01 01:00:01.000               0.036262                0.016850
1970-01-01 01:00:01.500               0.018649                0.016117
1970-01-01 01:00:02.000               0.004144                0.019780
...                                        ...                     ...
1970-01-01 01:38:18.500               0.007252                0.007326
1970-01-01 01:38:19.000               0.008288                0.008059
1970-01-01 01:38:19.500               0.006216                0.013919
1970-01-01 01:38:20.000               0.013469                0.015385
1970-01-01 01:38:20.500               0.009324                0.013187

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.078740
1970-01-01 01:00:00.500               0.004662
1970-01-01 01:00:01.000               0.047658
1970-01-01 01:00:01.500               0.050249
1970-01-01 01:00:02.000               0.006734
...                                        ...
1970-01-01 01:38:18.500               0.004662
1970-01-01 01:38:19.000               0.014505
1970-01-01 01:38:19.500               0.031082
1970-01-01 01:38:20.000               0.029010
1970-01-01 01:38:20.500               0.029010

[4602 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.040406                0.052747
1970-01-01 01:00:00.250               0.022793                0.013187
1970-01-01 01:00:00.500               0.009324                0.012454
1970-01-01 01:00:00.750               0.010361                0.001465
1970-01-01 01:00:01.000               0.017613                0.003663
...                                        ...                     ...
1970-01-01 01:38:19.750               0.006216                0.013919
1970-01-01 01:38:20.000               0.013469                0.015385
1970-01-01 01:38:20.250               0.006216                0.015385
1970-01-01 01:38:20.500               0.009324                0.013187
1970-01-01 01:38:20.750               0.008288                0.000000

[9204 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000    0.000000     -0.127567    0.0 -1.016440e-19       1.0
1          0.007812    0.000000     -0.127567    0.0 -2.841659e-06       1.0
2          0.015625    0.000000     -0.127567    0.0 -5.079070e-06       1.0
3          0.023438    0.000000     -0.127567    0.0 -6.735717e-06       1.0
4          0.031250    0.000000     -0.127567    0.0 -7.835085e-06       1.0
...             ...         ...           ...    ...           ...       ...
755305  5900.820312    0.650239      0.650239    0.0  6.502387e-01       0.0
755306  5900.828125    0.648019      0.648019    0.0  6.480186e-01       0.0
755307  5900.835938    0.648907      0.648907    0.0  6.489066e-01       0.0
755308  5900.843750    0.647131      0.647131    0.0  6.471306e-01       0.0
755309  5900.851562    0.650683      0.650683    0.0  6.506827e-01       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
755305                 0.0
755306                 0.0
755307                 0.0
755308                 0.0
755309                 0.0

[755310 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 01:40:21 to 1970-01-01 01:40:21.500000 for index 4842
calculating features from 96336 to 96343 for index 4842
processed hour 1 - start: 57600 | end: 96352
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.003108                0.003663
1970-01-01 01:00:00.500               0.003108                0.001465
1970-01-01 01:00:01.000               0.002072                0.005861
1970-01-01 01:00:01.500               0.004144                0.008059
1970-01-01 01:00:02.000               0.001036                0.002198
...                                        ...                     ...
1970-01-01 01:40:19.500               0.007220                0.020421
1970-01-01 01:40:20.000               0.018050                0.040842
1970-01-01 01:40:20.500               0.018050                0.056158
1970-01-01 01:40:21.000               0.014440                0.038289
1970-01-01 01:40:21.500               0.014440                0.033184

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.011397
1970-01-01 01:00:00.500               0.003626
1970-01-01 01:00:01.000               0.014505
1970-01-01 01:00:01.500               0.015023
1970-01-01 01:00:02.000               0.006216
...                                        ...
1970-01-01 01:40:19.500               0.032489
1970-01-01 01:40:20.000               0.102883
1970-01-01 01:40:20.500               0.146203
1970-01-01 01:40:21.000               0.102883
1970-01-01 01:40:21.500               0.090249

[4844 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.002072                0.003663
1970-01-01 01:00:00.250               0.003108                0.002198
1970-01-01 01:00:00.500               0.003108                0.000733
1970-01-01 01:00:00.750               0.001036                0.001465
1970-01-01 01:00:01.000               0.002072                0.002930
...                                        ...                     ...
1970-01-01 01:40:20.750               0.018050                0.048500
1970-01-01 01:40:21.000               0.014440                0.038289
1970-01-01 01:40:21.250               0.014440                0.035737
1970-01-01 01:40:21.500               0.014440                0.033184
1970-01-01 01:40:21.750               0.014440                0.028079

[9688 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000    0.000000     -0.091119    0.0  1.734723e-18       1.0
1          0.007812    0.000000     -0.091119    0.0  1.188918e-04       1.0
2          0.015625    0.000000     -0.091119    0.0  2.358200e-04       1.0
3          0.023438    0.000000     -0.091119    0.0  3.508022e-04       1.0
4          0.031250    0.000000     -0.091119    0.0  4.638558e-04       1.0
...             ...         ...           ...    ...           ...       ...
751970  5874.765625    0.011322      0.011322    0.0  1.132201e-02       0.0
751971  5874.773438    0.011322      0.011322    0.0  1.132201e-02       0.0
751972  5874.781250    0.011322      0.011322    0.0  1.132201e-02       0.0
751973  5874.789062    0.011766      0.011766    0.0  1.176601e-02       0.0
751974  5874.796875    0.011766      0.011766    0.0  1.176601e-02       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
751970                 0.0
751971                 0.0
751972                 0.0
751973                 0.0
751974                 0.0

[751975 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 01:41:50 to 1970-01-01 01:41:50.500000 for index 5020
calculating features from 97760 to 97767 for index 5020
processed hour 1 - start: 57600 | end: 97773
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.010830                0.033184
1970-01-01 01:00:00.500               0.003610                0.010210
1970-01-01 01:00:01.000               0.007220                0.010210
1970-01-01 01:00:01.500               0.003610                0.010210
1970-01-01 01:00:02.000               0.007220                0.015316
...                                        ...                     ...
1970-01-01 01:41:48.500               0.000000                0.000000
1970-01-01 01:41:49.000               0.000000                0.000000
1970-01-01 01:41:49.500               0.000000                0.000000
1970-01-01 01:41:50.000               0.000314                0.000222
1970-01-01 01:41:50.500               0.000000                0.000000

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.081224
1970-01-01 01:00:00.500               0.016245
1970-01-01 01:00:01.000               0.023465
1970-01-01 01:00:01.500               0.028880
1970-01-01 01:00:02.000               0.034294
...                                        ...
1970-01-01 01:41:48.500               0.000000
1970-01-01 01:41:49.000               0.000000
1970-01-01 01:41:49.500               0.000000
1970-01-01 01:41:50.000               0.000314
1970-01-01 01:41:50.500               0.000000

[5022 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.010830                0.033184
1970-01-01 01:00:00.250               0.007220                0.020421
1970-01-01 01:00:00.500               0.000000                0.010210
1970-01-01 01:00:00.750               0.003610                0.002553
1970-01-01 01:00:01.000               0.007220                0.007658
...                                        ...                     ...
1970-01-01 01:41:49.750               0.000000                0.000000
1970-01-01 01:41:50.000               0.000314                0.000222
1970-01-01 01:41:50.250               0.000314                0.000222
1970-01-01 01:41:50.500               0.000000                0.000000
1970-01-01 01:41:50.750               0.000000                0.000000

[10044 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label  auto_signal  pred_art  \
0          0.000000    0.000000     -0.091119    0.0     0.000000       0.0
1          0.007812    0.000000     -0.091119    0.0     0.000000       0.0
2          0.015625    0.000000     -0.091119    0.0     0.000000       0.0
3          0.023438    0.000000     -0.091119    0.0     0.000000       0.0
4          0.031250    0.000000     -0.091119    0.0     0.000000       0.0
...             ...         ...           ...    ...          ...       ...
819270  6400.546875    6.537249      6.537249    0.0     6.537249       0.0
819271  6400.554688    6.537249      6.537249    0.0     6.537249       0.0
819272  6400.562500    6.537249      6.537249    0.0     6.537249       0.0
819273  6400.570312    6.537249      6.537249    0.0     6.537249       0.0
819274  6400.578125    6.542354      6.542354    0.0     6.542354       0.0

        post_proc_pred_art
0                      0.0
1                      0.0
2                      0.0
3                      0.0
4                      0.0
...                    ...
819270                 0.0
819271                 0.0
819272                 0.0
819273                 0.0
819274                 0.0

[819275 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 01:44:23.500000 to 1970-01-01 01:44:24 for index 5327
calculating features from 100216 to 100223 for index 5327
processed hour 1 - start: 57600 | end: 100228
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.001036                0.004396
1970-01-01 01:00:00.500               0.001036                0.002930
1970-01-01 01:00:01.000               0.003108                0.004396
1970-01-01 01:00:01.500               0.002072                0.005861
1970-01-01 01:00:02.000               0.003108                0.008059
...                                        ...                     ...
1970-01-01 01:44:22.000               0.044550                0.035165
1970-01-01 01:44:22.500               0.016577                0.068864
1970-01-01 01:44:23.000               0.007252                0.028571
1970-01-01 01:44:23.500               0.031082                0.038828
1970-01-01 01:44:24.000               0.003108                0.005861

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.002590
1970-01-01 01:00:00.500               0.007770
1970-01-01 01:00:01.000               0.014505
1970-01-01 01:00:01.500               0.011397
1970-01-01 01:00:02.000               0.016577
...                                        ...
1970-01-01 01:44:22.000               0.187008
1970-01-01 01:44:22.500               0.042478
1970-01-01 01:44:23.000               0.016577
1970-01-01 01:44:23.500               0.012433
1970-01-01 01:44:24.000               0.000000

[5329 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.001036                0.004396
1970-01-01 01:00:00.250               0.001036                0.000733
1970-01-01 01:00:00.500               0.001036                0.002198
1970-01-01 01:00:00.750               0.001036                0.002930
1970-01-01 01:00:01.000               0.003108                0.004396
...                                        ...                     ...
1970-01-01 01:44:23.250               0.007252                0.028571
1970-01-01 01:44:23.500               0.031082                0.034432
1970-01-01 01:44:23.750               0.010361                0.038828
1970-01-01 01:44:24.000               0.003108                0.005861
1970-01-01 01:44:24.250               0.000000                0.000000

[10658 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label  auto_signal  pred_art  \
0          0.000000    0.000000     -0.200463    0.0     0.000000       0.0
1          0.007812    0.000000     -0.200463    0.0     0.000000       0.0
2          0.015625    0.000000     -0.200463    0.0     0.000000       0.0
3          0.023438    0.000000     -0.200463    0.0     0.000000       0.0
4          0.031250    0.000000     -0.200463    0.0     0.000000       0.0
...             ...         ...           ...    ...          ...       ...
809569  6324.757812    4.066667      4.066667    0.0     4.066667       0.0
809570  6324.765625    4.084249      4.084249    0.0     4.084249       0.0
809571  6324.773438    4.087179      4.087179    0.0     4.087179       0.0
809572  6324.781250    4.059341      4.059341    0.0     4.059341       0.0
809573  6324.789062    4.066667      4.066667    0.0     4.066667       0.0

        post_proc_pred_art
0                      0.0
1                      0.0
2                      0.0
3                      0.0
4                      0.0
...                    ...
809569                 0.0
809570                 0.0
809571                 0.0
809572                 0.0
809573                 0.0

[809574 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 01:45:24 to 1970-01-01 01:45:24.500000 for index 5448
calculating features from 101184 to 101191 for index 5448
processed hour 1 - start: 57600 | end: 101197
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.008288                0.014652
1970-01-01 01:00:00.500               0.008288                0.005861
1970-01-01 01:00:01.000               0.010361                0.019780
1970-01-01 01:00:01.500               0.003108                0.002198
1970-01-01 01:00:02.000               0.008288                0.000733
...                                        ...                     ...
1970-01-01 01:45:22.500               0.001036                0.001465
1970-01-01 01:45:23.000               0.007252                0.005128
1970-01-01 01:45:23.500               0.006216                0.002198
1970-01-01 01:45:24.000               0.002072                0.004396
1970-01-01 01:45:24.500               0.001036                0.002198

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.020721
1970-01-01 01:00:00.500               0.017095
1970-01-01 01:00:01.000               0.019167
1970-01-01 01:00:01.500               0.007252
1970-01-01 01:00:02.000               0.013987
...                                        ...
1970-01-01 01:45:22.500               0.000518
1970-01-01 01:45:23.000               0.008288
1970-01-01 01:45:23.500               0.007252
1970-01-01 01:45:24.000               0.010361
1970-01-01 01:45:24.500               0.010879

[5450 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.008288                0.014652
1970-01-01 01:00:00.250               0.002072                0.002930
1970-01-01 01:00:00.500               0.003108                0.002198
1970-01-01 01:00:00.750               0.008288                0.005861
1970-01-01 01:00:01.000               0.010361                0.019780
...                                        ...                     ...
1970-01-01 01:45:23.750               0.001036                0.002198
1970-01-01 01:45:24.000               0.002072                0.002930
1970-01-01 01:45:24.250               0.001036                0.004396
1970-01-01 01:45:24.500               0.001036                0.002198
1970-01-01 01:45:24.750               0.000000                0.000000

[10900 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000    0.000000     -0.273358    0.0  2.106994e-20       1.0
1          0.007812    0.000000     -0.273358    0.0  1.879714e-06       1.0
2          0.015625    0.000000     -0.273358    0.0  3.656027e-06       1.0
3          0.023438    0.000000     -0.273358    0.0  5.370973e-06       1.0
4          0.031250    0.000000     -0.273358    0.0  7.062509e-06       1.0
...             ...         ...           ...    ...           ...       ...
825073  6445.882812    0.000222      5.282191    1.0  2.220002e-04       0.0
825074  6445.890625    0.000222      5.284306    1.0  2.220002e-04       0.0
825075  6445.898438    0.000222      5.286426    1.0  2.220002e-04       0.0
825076  6445.906250    0.000222      5.288552    0.0  2.220002e-04       0.0
825077  6445.914062    0.000222      5.290683    0.0  2.220002e-04       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
825073                 0.0
825074                 0.0
825075                 0.0
825076                 0.0
825077                 0.0

[825078 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 01:48:34.500000 to 1970-01-01 01:48:35 for index 5829
calculating features from 104232 to 104239 for index 5829
processed hour 1 - start: 57600 | end: 104242
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.126348                0.119973
1970-01-01 01:00:00.500               0.039709                0.079131
1970-01-01 01:00:01.000               0.028880                0.022974
1970-01-01 01:00:01.500               0.003610                0.025526
1970-01-01 01:00:02.000               0.010830                0.025526
...                                        ...                     ...
1970-01-01 01:48:33.000               0.010830                0.007658
1970-01-01 01:48:33.500               0.407924                0.564128
1970-01-01 01:48:34.000               0.064979                0.058710
1970-01-01 01:48:34.500               0.036099                0.109762
1970-01-01 01:48:35.000               0.007220                0.000000

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.400704
1970-01-01 01:00:00.500               0.205767
1970-01-01 01:00:01.000               0.039709
1970-01-01 01:00:01.500               0.059564
1970-01-01 01:00:02.000               0.077614
...                                        ...
1970-01-01 01:48:33.000               0.050539
1970-01-01 01:48:33.500               1.546861
1970-01-01 01:48:34.000               0.072199
1970-01-01 01:48:34.500               0.220207
1970-01-01 01:48:35.000               0.000000

[5831 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.079419                0.119973
1970-01-01 01:00:00.250               0.126348                0.109762
1970-01-01 01:00:00.500               0.036099                0.079131
1970-01-01 01:00:00.750               0.039709                0.033184
1970-01-01 01:00:01.000               0.028880                0.022974
...                                        ...                     ...
1970-01-01 01:48:34.250               0.018050                0.058710
1970-01-01 01:48:34.500               0.036099                0.048500
1970-01-01 01:48:34.750               0.025270                0.109762
1970-01-01 01:48:35.000               0.007220                0.000000
1970-01-01 01:48:35.250               0.000000                0.000000

[11662 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label  auto_signal  pred_art  \
0          0.000000    0.000000     -0.236911    0.0     0.000000       0.0
1          0.007812    0.000000     -0.236911    0.0     0.000000       0.0
2          0.015625    0.000000     -0.236911    0.0     0.000000       0.0
3          0.023438    0.000000     -0.236911    0.0     0.000000       0.0
4          0.031250    0.000000     -0.236911    0.0     0.000000       0.0
...             ...         ...           ...    ...          ...       ...
794065  6203.632812    0.574315      0.574315    0.0     0.574315       0.0
794066  6203.640625    0.579643      0.579643    0.0     0.579643       0.0
794067  6203.648438    0.575647      0.575647    0.0     0.575647       0.0
794068  6203.656250    0.580531      0.580531    0.0     0.580531       0.0
794069  6203.664062    0.580087      0.580087    0.0     0.580087       0.0

        post_proc_pred_art
0                      0.0
1                      0.0
2                      0.0
3                      0.0
4                      0.0
...                    ...
794065                 0.0
794066                 0.0
794067                 0.0
794068                 0.0
794069                 0.0

[794070 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 01:48:25.500000 to 1970-01-01 01:48:26 for index 5811
calculating features from 104088 to 104095 for index 5811
processed hour 1 - start: 57600 | end: 104104
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.003108                0.002198
1970-01-01 01:00:00.500               0.003108                0.000733
1970-01-01 01:00:01.000               0.003108                0.000000
1970-01-01 01:00:01.500               0.005180                0.004396
1970-01-01 01:00:02.000               0.001036                0.000733
...                                        ...                     ...
1970-01-01 01:48:24.000               0.003108                0.004396
1970-01-01 01:48:24.500               0.004144                0.009524
1970-01-01 01:48:25.000               0.034190                0.025641
1970-01-01 01:48:25.500               0.018649                0.045421
1970-01-01 01:48:26.000               0.027973                0.016117

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.001554
1970-01-01 01:00:00.500               0.002072
1970-01-01 01:00:01.000               0.002072
1970-01-01 01:00:01.500               0.002072
1970-01-01 01:00:02.000               0.000518
...                                        ...
1970-01-01 01:48:24.000               0.013987
1970-01-01 01:48:24.500               0.018649
1970-01-01 01:48:25.000               0.017613
1970-01-01 01:48:25.500               0.066825
1970-01-01 01:48:26.000               0.026419

[5813 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.003108                0.002198
1970-01-01 01:00:00.250               0.003108                0.000000
1970-01-01 01:00:00.500               0.003108                0.000733
1970-01-01 01:00:00.750               0.001036                0.000733
1970-01-01 01:00:01.000               0.003108                0.000000
...                                        ...                     ...
1970-01-01 01:48:25.250               0.034190                0.025641
1970-01-01 01:48:25.500               0.018649                0.045421
1970-01-01 01:48:25.750               0.005180                0.010989
1970-01-01 01:48:26.000               0.008288                0.016117
1970-01-01 01:48:26.250               0.027973                0.010989

[11626 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label  auto_signal  pred_art  \
0          0.000000    0.127567      0.127567    0.0     0.127567       0.0
1          0.007812    0.127567      0.127567    0.0     0.127567       0.0
2          0.015625    0.127567      0.127567    0.0     0.127567       0.0
3          0.023438    0.127567      0.127567    0.0     0.127567       0.0
4          0.031250    0.127567      0.127567    0.0     0.127567       0.0
...             ...         ...           ...    ...          ...       ...
750514  5863.390625    1.627106      1.627106    0.0     1.627106       0.0
750515  5863.398438    1.638828      1.638828    0.0     1.638828       0.0
750516  5863.406250    1.635897      1.635897    0.0     1.635897       0.0
750517  5863.414062    1.634432      1.634432    0.0     1.634432       0.0
750518  5863.421875    1.635897      1.635897    0.0     1.635897       0.0

        post_proc_pred_art
0                      0.0
1                      0.0
2                      0.0
3                      0.0
4                      0.0
...                    ...
750514                 0.0
750515                 0.0
750516                 0.0
750517                 0.0
750518                 0.0

[750519 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 01:57:31 to 1970-01-01 01:57:31.500000 for index 6902
calculating features from 112816 to 112823 for index 6902
processed hour 1 - start: 57600 | end: 112825
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.001036                0.001465
1970-01-01 01:00:00.500               0.008288                0.005861
1970-01-01 01:00:01.000               0.009324                0.007326
1970-01-01 01:00:01.500               0.013469                0.005861
1970-01-01 01:00:02.000               0.006216                0.004396
...                                        ...                     ...
1970-01-01 01:57:29.500               1.046414                1.269164
1970-01-01 01:57:30.000               0.000628                0.004662
1970-01-01 01:57:30.500               0.003140                0.005772
1970-01-01 01:57:31.000               0.000942                0.004884
1970-01-01 01:57:31.500               0.000000                0.000000

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.001554
1970-01-01 01:00:00.500               0.007252
1970-01-01 01:00:01.000               0.002590
1970-01-01 01:00:01.500               0.005698
1970-01-01 01:00:02.000               0.000000
...                                        ...
1970-01-01 01:57:29.500               1.942813
1970-01-01 01:57:30.000               0.002041
1970-01-01 01:57:30.500               0.000628
1970-01-01 01:57:31.000               0.002041
1970-01-01 01:57:31.500               0.000000

[6904 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.000000                0.001465
1970-01-01 01:00:00.250               0.001036                0.000733
1970-01-01 01:00:00.500               0.000000                0.001465
1970-01-01 01:00:00.750               0.008288                0.005861
1970-01-01 01:00:01.000               0.009324                0.007326
...                                        ...                     ...
1970-01-01 01:57:30.750               0.003140                0.005772
1970-01-01 01:57:31.000               0.000628                0.004884
1970-01-01 01:57:31.250               0.000942                0.001998
1970-01-01 01:57:31.500               0.000000                0.000000
1970-01-01 01:57:31.750               0.000000                0.000000

[13808 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000    0.000000     -0.127567    0.0  2.106994e-20       1.0
1          0.007812    0.000000     -0.127567    0.0  1.879714e-06       1.0
2          0.015625    0.000000     -0.127567    0.0  3.656027e-06       1.0
3          0.023438    0.000000     -0.127567    0.0  5.370973e-06       1.0
4          0.031250    0.000000     -0.127567    0.0  7.062509e-06       1.0
...             ...         ...           ...    ...           ...       ...
786313  6143.070312    5.776570      5.776570    0.0  5.776570e+00       0.0
786314  6143.078125    5.776570      5.776570    0.0  5.776570e+00       0.0
786315  6143.085938    5.781675      5.781675    0.0  5.781675e+00       0.0
786316  6143.093750    5.761254      5.761254    0.0  5.761254e+00       0.0
786317  6143.101562    5.786780      5.786780    0.0  5.786780e+00       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
786313                 0.0
786314                 0.0
786315                 0.0
786316                 0.0
786317                 0.0

[786318 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
1970-01-01 00:00:00.187500                0.000000                 0.000222
1970-01-01 00:00:00.250000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.009324                 0.005861
1970-01-01 00:59:59.750000                0.004144                 0.006593
1970-01-01 00:59:59.812500                0.008288                 0.007326
1970-01-01 00:59:59.875000                0.006216                 0.008059
1970-01-01 00:59:59.937500                0.009324                 0.008059

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000157
1970-01-01 00:00:00.250000                0.000000
...                                            ...
1970-01-01 00:59:59.687500                0.002072
1970-01-01 00:59:59.750000                0.001036
1970-01-01 00:59:59.812500                0.001036
1970-01-01 00:59:59.875000                0.002072
1970-01-01 00:59:59.937500                0.000518

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.005180                 0.007326
1970-01-01 00:59:59.875000                0.004144                 0.008059
1970-01-01 00:59:59.906250                0.006216                 0.000733
1970-01-01 00:59:59.937500                0.004144                 0.008059
1970-01-01 00:59:59.968750                0.009324                 0.004396

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.002171                 0.001535
1970-01-01 00:00:00.187500                0.000314                 0.001399
1970-01-01 00:00:00.250000                0.000314                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.002072                 0.000733
1970-01-01 00:59:59.750000                0.001036                 0.000733
1970-01-01 00:59:59.812500                0.001036                 0.000733
1970-01-01 00:59:59.875000                0.001036                 0.002198
1970-01-01 00:59:59.937500                0.001036                 0.000733

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.003257
1970-01-01 00:00:00.187500                0.000989
1970-01-01 00:00:00.250000                0.000314
...                                            ...
1970-01-01 00:59:59.687500                0.001554
1970-01-01 00:59:59.750000                0.002072
1970-01-01 00:59:59.812500                0.002590
1970-01-01 00:59:59.875000                0.001554
1970-01-01 00:59:59.937500                0.001036

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.002171                 0.001535
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.000000                 0.000000
1970-01-01 00:59:59.875000                0.001036                 0.002198
1970-01-01 00:59:59.906250                0.000000                 0.001465
1970-01-01 00:59:59.937500                0.001036                 0.000733
1970-01-01 00:59:59.968750                0.001036                 0.000733

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.002590                 0.001832
1970-01-01 00:00:00.187500                0.000000                 0.004107
1970-01-01 00:00:00.250000                0.000314                 0.000222
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.001036                 0.000733
1970-01-01 00:59:59.750000                0.002072                 0.000733
1970-01-01 00:59:59.812500                0.002072                 0.000733
1970-01-01 00:59:59.875000                0.001036                 0.000733
1970-01-01 00:59:59.937500                0.002072                 0.000733

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.003885
1970-01-01 00:00:00.187500                0.002904
1970-01-01 00:00:00.250000                0.000471
...                                            ...
1970-01-01 00:59:59.687500                0.000000
1970-01-01 00:59:59.750000                0.000518
1970-01-01 00:59:59.812500                0.001554
1970-01-01 00:59:59.875000                0.001036
1970-01-01 00:59:59.937500                0.000518

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.002590                 0.001832
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.001036                 0.000733
1970-01-01 00:59:59.875000                0.001036                 0.000733
1970-01-01 00:59:59.906250                0.001036                 0.000733
1970-01-01 00:59:59.937500                0.001036                 0.000733
1970-01-01 00:59:59.968750                0.002072                 0.000000

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.003327                 0.002352
1970-01-01 00:00:00.187500                0.000000                 0.000733
1970-01-01 00:00:00.250000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.000000                 0.000000
1970-01-01 00:59:59.750000                0.003610                 0.002553
1970-01-01 00:59:59.812500                0.000000                 0.000000
1970-01-01 00:59:59.875000                0.000000                 0.000000
1970-01-01 00:59:59.937500                0.000000                 0.005105

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.004990
1970-01-01 00:00:00.187500                0.000518
1970-01-01 00:00:00.250000                0.000000
...                                            ...
1970-01-01 00:59:59.687500                0.000000
1970-01-01 00:59:59.750000                0.003610
1970-01-01 00:59:59.812500                0.000000
1970-01-01 00:59:59.875000                0.000000
1970-01-01 00:59:59.937500                0.003610

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.003327                 0.002352
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.000000                 0.000000
1970-01-01 00:59:59.875000                0.000000                 0.000000
1970-01-01 00:59:59.906250                0.000000                 0.000000
1970-01-01 00:59:59.937500                0.000000                 0.000000
1970-01-01 00:59:59.968750                0.000000                 0.005105

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
1970-01-01 00:00:00.187500                0.000000                 0.000222
1970-01-01 00:00:00.250000                0.000628                 0.000222
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.000942                 0.002220
1970-01-01 00:59:59.750000                0.002512                 0.001110
1970-01-01 00:59:59.812500                0.003140                 0.001332
1970-01-01 00:59:59.875000                0.002512                 0.000666
1970-01-01 00:59:59.937500                0.001256                 0.001110

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000157
1970-01-01 00:00:00.250000                0.000471
...                                            ...
1970-01-01 00:59:59.687500                0.000157
1970-01-01 00:59:59.750000                0.000942
1970-01-01 00:59:59.812500                0.000471
1970-01-01 00:59:59.875000                0.000471
1970-01-01 00:59:59.937500                0.000157

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.003140                 0.001110
1970-01-01 00:59:59.875000                0.001884                 0.000666
1970-01-01 00:59:59.906250                0.002512                 0.000000
1970-01-01 00:59:59.937500                0.001256                 0.000000
1970-01-01 00:59:59.968750                0.000942                 0.001110

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.004662                 0.003297
1970-01-01 00:00:00.187500                0.000000                 0.002065
1970-01-01 00:00:00.250000                0.000314                 0.000444
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.000000                 0.000000
1970-01-01 00:59:59.750000                0.003610                 0.002553
1970-01-01 00:59:59.812500                0.003610                 0.002553
1970-01-01 00:59:59.875000                0.003610                 0.002553
1970-01-01 00:59:59.937500                0.003610                 0.005105

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.006993
1970-01-01 00:00:00.187500                0.001460
1970-01-01 00:00:00.250000                0.000157
...                                            ...
1970-01-01 00:59:59.687500                0.000000
1970-01-01 00:59:59.750000                0.001805
1970-01-01 00:59:59.812500                0.000000
1970-01-01 00:59:59.875000                0.001805
1970-01-01 00:59:59.937500                0.001805

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.004662                 0.003297
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.003610                 0.002553
1970-01-01 00:59:59.875000                0.003610                 0.002553
1970-01-01 00:59:59.906250                0.000000                 0.000000
1970-01-01 00:59:59.937500                0.003610                 0.002553
1970-01-01 00:59:59.968750                0.000000                 0.005105

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.005698                 0.004029
1970-01-01 00:00:00.187500                0.000628                 0.000289
1970-01-01 00:00:00.250000                0.000628                 0.000888
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.001036                 0.002198
1970-01-01 00:59:59.750000                0.001036                 0.002198
1970-01-01 00:59:59.812500                0.001036                 0.002198
1970-01-01 00:59:59.875000                0.001036                 0.002198
1970-01-01 00:59:59.937500                0.001036                 0.002930

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.008547
1970-01-01 00:00:00.187500                0.000204
1970-01-01 00:00:00.250000                0.001256
...                                            ...
1970-01-01 00:59:59.687500                0.005698
1970-01-01 00:59:59.750000                0.007252
1970-01-01 00:59:59.812500                0.007770
1970-01-01 00:59:59.875000                0.006734
1970-01-01 00:59:59.937500                0.005698

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.005698                 0.004029
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.000000                 0.001465
1970-01-01 00:59:59.875000                0.001036                 0.002198
1970-01-01 00:59:59.906250                0.001036                 0.001465
1970-01-01 00:59:59.937500                0.001036                 0.002930
1970-01-01 00:59:59.968750                0.001036                 0.000733

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
1970-01-01 00:00:00.187500                0.001570                 0.001332
1970-01-01 00:00:00.250000                0.001256                 0.001998
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.005180                 0.005861
1970-01-01 00:59:59.750000                0.003108                 0.003663
1970-01-01 00:59:59.812500                0.007252                 0.002930
1970-01-01 00:59:59.875000                0.003108                 0.003663
1970-01-01 00:59:59.937500                0.005180                 0.002930

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000            0.000000e+00
1970-01-01 00:00:00.062500            0.000000e+00
1970-01-01 00:00:00.125000            0.000000e+00
1970-01-01 00:00:00.187500            9.418672e-04
1970-01-01 00:00:00.250000            1.726756e-03
...                                            ...
1970-01-01 00:59:59.687500            2.072108e-03
1970-01-01 00:59:59.750000            1.554081e-03
1970-01-01 00:59:59.812500            7.252377e-03
1970-01-01 00:59:59.875000            8.881784e-16
1970-01-01 00:59:59.937500            2.072108e-03

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.004144                 0.002930
1970-01-01 00:59:59.875000                0.003108                 0.003663
1970-01-01 00:59:59.906250                0.003108                 0.000733
1970-01-01 00:59:59.937500                0.002072                 0.002930
1970-01-01 00:59:59.968750                0.005180                 0.001465

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                 0.00000                 0.000000
1970-01-01 00:00:00.062500                 0.00000                 0.000000
1970-01-01 00:00:00.125000                 0.00000                 0.000000
1970-01-01 00:00:00.187500                 0.00000                 0.000222
1970-01-01 00:00:00.250000                 0.00000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                 0.00722                 0.020421
1970-01-01 00:59:59.750000                 0.01083                 0.017868
1970-01-01 00:59:59.812500                 0.01083                 0.017868
1970-01-01 00:59:59.875000                 0.01083                 0.020421
1970-01-01 00:59:59.937500                 0.01083                 0.012763

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000157
1970-01-01 00:00:00.250000                0.000000
...                                            ...
1970-01-01 00:59:59.687500                0.003610
1970-01-01 00:59:59.750000                0.009025
1970-01-01 00:59:59.812500                0.007220
1970-01-01 00:59:59.875000                0.003610
1970-01-01 00:59:59.937500                0.003610

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                 0.00000                 0.000000
1970-01-01 00:00:00.031250                 0.00000                 0.000000
1970-01-01 00:00:00.062500                 0.00000                 0.000000
1970-01-01 00:00:00.093750                 0.00000                 0.000000
1970-01-01 00:00:00.125000                 0.00000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                 0.00361                 0.017868
1970-01-01 00:59:59.875000                 0.00722                 0.020421
1970-01-01 00:59:59.906250                 0.01083                 0.020421
1970-01-01 00:59:59.937500                 0.01083                 0.012763
1970-01-01 00:59:59.968750                 0.01083                 0.012763

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
1970-01-01 00:00:00.187500                0.000000                 0.000222
1970-01-01 00:00:00.250000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.002826                 0.000888
1970-01-01 00:59:59.750000                0.002512                 0.001332
1970-01-01 00:59:59.812500                0.003454                 0.001554
1970-01-01 00:59:59.875000                0.002826                 0.000888
1970-01-01 00:59:59.937500                0.001884                 0.001332

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000157
1970-01-01 00:00:00.250000                0.000000
...                                            ...
1970-01-01 00:59:59.687500                0.001099
1970-01-01 00:59:59.750000                0.000785
1970-01-01 00:59:59.812500                0.001256
1970-01-01 00:59:59.875000                0.001099
1970-01-01 00:59:59.937500                0.000157

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.001256                 0.001554
1970-01-01 00:59:59.875000                0.000942                 0.000888
1970-01-01 00:59:59.906250                0.002826                 0.000222
1970-01-01 00:59:59.937500                0.001570                 0.001332
1970-01-01 00:59:59.968750                0.001884                 0.001110

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.012929                 0.009142
1970-01-01 00:00:00.187500                0.000000                 0.006061
1970-01-01 00:00:00.250000                0.000942                 0.000666
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.005965                 0.005550
1970-01-01 00:59:59.750000                0.005023                 0.005106
1970-01-01 00:59:59.812500                0.005965                 0.004662
1970-01-01 00:59:59.875000                0.006593                 0.004440
1970-01-01 00:59:59.937500                0.005337                 0.005328

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.019394
1970-01-01 00:00:00.187500                0.004285
1970-01-01 00:00:00.250000                0.001413
...                                            ...
1970-01-01 00:59:59.687500                0.002041
1970-01-01 00:59:59.750000                0.000314
1970-01-01 00:59:59.812500                0.000157
1970-01-01 00:59:59.875000                0.002983
1970-01-01 00:59:59.937500                0.001099

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.012929                 0.009142
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.005651                 0.004440
1970-01-01 00:59:59.875000                0.003767                 0.002442
1970-01-01 00:59:59.906250                0.006593                 0.004440
1970-01-01 00:59:59.937500                0.003767                 0.002442
1970-01-01 00:59:59.968750                0.005337                 0.005328

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 01:41:21 to 1970-01-01 01:41:21.500000 for index 4962
calculating features from 778368 to 778431 for index 4962
processed hour 1 - start: 460800 | end: 778464
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.005180                 0.008791
1970-01-01 01:00:00.062500                0.005180                 0.009524
1970-01-01 01:00:00.125000                0.010361                 0.007326
1970-01-01 01:00:00.187500                0.005180                 0.010989
1970-01-01 01:00:00.250000                0.009324                 0.005861
...                                            ...                      ...
1970-01-01 01:41:21.437500                0.010361                 0.002930
1970-01-01 01:41:21.500000                0.005180                 0.003663
1970-01-01 01:41:21.562500                0.009324                 0.004396
1970-01-01 01:41:21.625000                0.008288                 0.007326
1970-01-01 01:41:21.687500                0.005180                 0.008791

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.000518
1970-01-01 01:00:00.062500                0.002590
1970-01-01 01:00:00.125000                0.001554
1970-01-01 01:00:00.187500                0.001554
1970-01-01 01:00:00.250000                0.001554
...                                            ...
1970-01-01 01:41:21.437500                0.001554
1970-01-01 01:41:21.500000                0.006216
1970-01-01 01:41:21.562500                0.005698
1970-01-01 01:41:21.625000                0.013987
1970-01-01 01:41:21.687500                0.008806

[39708 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.005180                 0.008059
1970-01-01 01:00:00.031250                0.005180                 0.008791
1970-01-01 01:00:00.062500                0.003108                 0.009524
1970-01-01 01:00:00.093750                0.005180                 0.007326
1970-01-01 01:00:00.125000                0.005180                 0.007326
...                                            ...                      ...
1970-01-01 01:41:21.593750                0.004144                 0.000733
1970-01-01 01:41:21.625000                0.001036                 0.000733
1970-01-01 01:41:21.656250                0.008288                 0.007326
1970-01-01 01:41:21.687500                0.005180                 0.002198
1970-01-01 01:41:21.718750                0.004144                 0.008791

[79416 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:38:29 to 1970-01-01 01:38:29.500000 for index 4618
calculating features from 756352 to 756415 for index 4618
processed hour 1 - start: 460800 | end: 756471
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.001036                 0.000733
1970-01-01 01:00:00.062500                0.002072                 0.000733
1970-01-01 01:00:00.125000                0.002072                 0.000733
1970-01-01 01:00:00.187500                0.002072                 0.002198
1970-01-01 01:00:00.250000                0.002072                 0.001465
...                                            ...                      ...
1970-01-01 01:38:29.625000                0.003610                 0.002553
1970-01-01 01:38:29.687500                0.003610                 0.002553
1970-01-01 01:38:29.750000                0.003610                 0.002553
1970-01-01 01:38:29.812500                0.003610                 0.002553
1970-01-01 01:38:29.875000                0.000000                 0.005105

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.002072
1970-01-01 01:00:00.062500                0.001554
1970-01-01 01:00:00.125000                0.002590
1970-01-01 01:00:00.187500                0.002072
1970-01-01 01:00:00.250000                0.003108
...                                            ...
1970-01-01 01:38:29.625000                0.001805
1970-01-01 01:38:29.687500                0.001805
1970-01-01 01:38:29.750000                0.000000
1970-01-01 01:38:29.812500                0.000000
1970-01-01 01:38:29.875000                0.000000

[36959 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.001036                 0.000733
1970-01-01 01:00:00.031250                0.001036                 0.000733
1970-01-01 01:00:00.062500                0.002072                 0.000733
1970-01-01 01:00:00.093750                0.002072                 0.000000
1970-01-01 01:00:00.125000                0.001036                 0.000733
...                                            ...                      ...
1970-01-01 01:38:29.781250                0.003610                 0.002553
1970-01-01 01:38:29.812500                0.003610                 0.002553
1970-01-01 01:38:29.843750                0.003610                 0.002553
1970-01-01 01:38:29.875000                0.000000                 0.005105
1970-01-01 01:38:29.906250                0.000000                 0.005105

[73918 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                 0.00000                 0.000000
1970-01-01 00:00:00.062500                 0.00000                 0.000000
1970-01-01 00:00:00.125000                 0.00000                 0.000000
1970-01-01 00:00:00.187500                 0.00000                 0.000222
1970-01-01 00:00:00.250000                 0.00000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                 0.01444                 0.007658
1970-01-01 00:59:59.750000                 0.01444                 0.010210
1970-01-01 00:59:59.812500                 0.01444                 0.010210
1970-01-01 00:59:59.875000                 0.01805                 0.010210
1970-01-01 00:59:59.937500                 0.01444                 0.012763

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000157
1970-01-01 00:00:00.250000                0.000000
...                                            ...
1970-01-01 00:59:59.687500                0.003610
1970-01-01 00:59:59.750000                0.007220
1970-01-01 00:59:59.812500                0.005415
1970-01-01 00:59:59.875000                0.000000
1970-01-01 00:59:59.937500                0.005415

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                 0.00000                 0.000000
1970-01-01 00:00:00.031250                 0.00000                 0.000000
1970-01-01 00:00:00.062500                 0.00000                 0.000000
1970-01-01 00:00:00.093750                 0.00000                 0.000000
1970-01-01 00:00:00.125000                 0.00000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                 0.01083                 0.002553
1970-01-01 00:59:59.875000                 0.01805                 0.005105
1970-01-01 00:59:59.906250                 0.01444                 0.010210
1970-01-01 00:59:59.937500                 0.01444                 0.005105
1970-01-01 00:59:59.968750                 0.01444                 0.012763

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 01:38:20 to 1970-01-01 01:38:20.500000 for index 4600
calculating features from 755200 to 755263 for index 4600
processed hour 1 - start: 460800 | end: 755310
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.002826                 0.001332
1970-01-01 01:00:00.062500                0.001884                 0.000888
1970-01-01 01:00:00.125000                0.002198                 0.001776
1970-01-01 01:00:00.187500                0.001884                 0.000222
1970-01-01 01:00:00.250000                0.002512                 0.002442
...                                            ...                      ...
1970-01-01 01:38:20.562500                0.002512                 0.001776
1970-01-01 01:38:20.625000                0.002512                 0.001332
1970-01-01 01:38:20.687500                0.001256                 0.001998
1970-01-01 01:38:20.750000                0.002198                 0.000666
1970-01-01 01:38:20.812500                0.002512                 0.000888

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.001099
1970-01-01 01:00:00.062500                0.000628
1970-01-01 01:00:00.125000                0.000471
1970-01-01 01:00:00.187500                0.000000
1970-01-01 01:00:00.250000                0.001413
...                                            ...
1970-01-01 01:38:20.562500                0.000785
1970-01-01 01:38:20.625000                0.001570
1970-01-01 01:38:20.687500                0.000471
1970-01-01 01:38:20.750000                0.000785
1970-01-01 01:38:20.812500                0.000000

[36814 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.002826                 0.000222
1970-01-01 01:00:00.031250                0.001570                 0.001332
1970-01-01 01:00:00.062500                0.000942                 0.000888
1970-01-01 01:00:00.093750                0.001884                 0.000444
1970-01-01 01:00:00.125000                0.002198                 0.001776
...                                            ...                      ...
1970-01-01 01:38:20.718750                0.000314                 0.001998
1970-01-01 01:38:20.750000                0.002198                 0.000444
1970-01-01 01:38:20.781250                0.001884                 0.000666
1970-01-01 01:38:20.812500                0.001256                 0.000888
1970-01-01 01:38:20.843750                0.002512                 0.000000

[73628 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:37:54 to 1970-01-01 01:37:54.500000 for index 4548
calculating features from 751872 to 751935 for index 4548
processed hour 1 - start: 460800 | end: 751975
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.003610                 0.002553
1970-01-01 01:00:00.062500                0.000000                 0.000000
1970-01-01 01:00:00.125000                0.000000                 0.000000
1970-01-01 01:00:00.187500                0.003610                 0.002553
1970-01-01 01:00:00.250000                0.003610                 0.002553
...                                            ...                      ...
1970-01-01 01:37:54.500000                0.000314                 0.000222
1970-01-01 01:37:54.562500                0.000314                 0.000222
1970-01-01 01:37:54.625000                0.000314                 0.000222
1970-01-01 01:37:54.687500                0.000000                 0.000444
1970-01-01 01:37:54.750000                0.000314                 0.000666

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000            3.609944e-03
1970-01-01 01:00:00.062500            0.000000e+00
1970-01-01 01:00:00.125000            0.000000e+00
1970-01-01 01:00:00.187500            1.804972e-03
1970-01-01 01:00:00.250000            5.414916e-03
...                                            ...
1970-01-01 01:37:54.500000            0.000000e+00
1970-01-01 01:37:54.562500            0.000000e+00
1970-01-01 01:37:54.625000            3.139557e-04
1970-01-01 01:37:54.687500            0.000000e+00
1970-01-01 01:37:54.750000            3.469447e-17

[36397 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.003610                 0.002553
1970-01-01 01:00:00.031250                0.003610                 0.002553
1970-01-01 01:00:00.062500                0.000000                 0.000000
1970-01-01 01:00:00.093750                0.000000                 0.000000
1970-01-01 01:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 01:37:54.656250                0.000314                 0.000222
1970-01-01 01:37:54.687500                0.000000                 0.000444
1970-01-01 01:37:54.718750                0.000000                 0.000444
1970-01-01 01:37:54.750000                0.000314                 0.000666
1970-01-01 01:37:54.781250                0.000314                 0.000222

[72794 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:46:24.500000 to 1970-01-01 01:46:25 for index 5569
calculating features from 817216 to 817279 for index 5569
processed hour 1 - start: 460800 | end: 817326
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                 0.00361                 0.005105
1970-01-01 01:00:00.062500                 0.00000                 0.000000
1970-01-01 01:00:00.125000                 0.00361                 0.002553
1970-01-01 01:00:00.187500                 0.00361                 0.002553
1970-01-01 01:00:00.250000                 0.00361                 0.002553
...                                            ...                      ...
1970-01-01 01:46:25.062500                 0.00361                 0.005105
1970-01-01 01:46:25.125000                 0.00361                 0.007658
1970-01-01 01:46:25.187500                 0.00361                 0.005105
1970-01-01 01:46:25.250000                 0.00361                 0.007658
1970-01-01 01:46:25.312500                 0.00361                 0.010210

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.001805
1970-01-01 01:00:00.062500                0.000000
1970-01-01 01:00:00.125000                0.001805
1970-01-01 01:00:00.187500                0.005415
1970-01-01 01:00:00.250000                0.001805
...                                            ...
1970-01-01 01:46:25.062500                0.012635
1970-01-01 01:46:25.125000                0.012635
1970-01-01 01:46:25.187500                0.018050
1970-01-01 01:46:25.250000                0.016245
1970-01-01 01:46:25.312500                0.014440

[44566 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                 0.00361                 0.002553
1970-01-01 01:00:00.031250                 0.00000                 0.005105
1970-01-01 01:00:00.062500                 0.00000                 0.000000
1970-01-01 01:00:00.093750                 0.00000                 0.000000
1970-01-01 01:00:00.125000                 0.00000                 0.000000
...                                            ...                      ...
1970-01-01 01:46:25.218750                 0.00361                 0.005105
1970-01-01 01:46:25.250000                 0.00000                 0.005105
1970-01-01 01:46:25.281250                 0.00361                 0.007658
1970-01-01 01:46:25.312500                 0.00361                 0.010210
1970-01-01 01:46:25.343750                 0.00361                 0.000000

[89132 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:55:13 to 1970-01-01 01:55:13.500000 for index 6626
calculating features from 884864 to 884927 for index 6626
processed hour 1 - start: 460800 | end: 884967
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.002072                 0.000733
1970-01-01 01:00:00.062500                0.001036                 0.002198
1970-01-01 01:00:00.125000                0.001036                 0.000733
1970-01-01 01:00:00.187500                0.002072                 0.002198
1970-01-01 01:00:00.250000                0.002072                 0.001465
...                                            ...                      ...
1970-01-01 01:55:13.500000                0.002072                 0.000733
1970-01-01 01:55:13.562500                0.001036                 0.001465
1970-01-01 01:55:13.625000                0.002072                 0.000733
1970-01-01 01:55:13.687500                0.002072                 0.000733
1970-01-01 01:55:13.750000                0.001036                 0.000000

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.000518
1970-01-01 01:00:00.062500                0.001036
1970-01-01 01:00:00.125000                0.000518
1970-01-01 01:00:00.187500                0.002072
1970-01-01 01:00:00.250000                0.001554
...                                            ...
1970-01-01 01:55:13.500000                0.001554
1970-01-01 01:55:13.562500                0.001036
1970-01-01 01:55:13.625000                0.000518
1970-01-01 01:55:13.687500                0.000000
1970-01-01 01:55:13.750000                0.001036

[53021 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.002072                 0.000733
1970-01-01 01:00:00.031250                0.002072                 0.000000
1970-01-01 01:00:00.062500                0.001036                 0.002198
1970-01-01 01:00:00.093750                0.001036                 0.000733
1970-01-01 01:00:00.125000                0.001036                 0.000000
...                                            ...                      ...
1970-01-01 01:55:13.656250                0.002072                 0.000000
1970-01-01 01:55:13.687500                0.001036                 0.000733
1970-01-01 01:55:13.718750                0.002072                 0.000733
1970-01-01 01:55:13.750000                0.001036                 0.000000
1970-01-01 01:55:13.781250                0.000000                 0.000000

[106042 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:46:40 to 1970-01-01 01:46:40.500000 for index 5600
calculating features from 819200 to 819263 for index 5600
processed hour 1 - start: 460800 | end: 819275
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.001036                 0.002198
1970-01-01 01:00:00.062500                0.001036                 0.001465
1970-01-01 01:00:00.125000                0.001036                 0.002198
1970-01-01 01:00:00.187500                0.001036                 0.001465
1970-01-01 01:00:00.250000                0.001036                 0.000733
...                                            ...                      ...
1970-01-01 01:46:40.312500                0.003610                 0.002553
1970-01-01 01:46:40.375000                0.003610                 0.000000
1970-01-01 01:46:40.437500                0.003610                 0.002553
1970-01-01 01:46:40.500000                0.003610                 0.002553
1970-01-01 01:46:40.562500                0.000000                 0.005105

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.005180
1970-01-01 01:00:00.062500                0.004662
1970-01-01 01:00:00.125000                0.005180
1970-01-01 01:00:00.187500                0.003626
1970-01-01 01:00:00.250000                0.002072
...                                            ...
1970-01-01 01:46:40.312500                0.007220
1970-01-01 01:46:40.375000                0.003610
1970-01-01 01:46:40.437500                0.005415
1970-01-01 01:46:40.500000                0.005415
1970-01-01 01:46:40.562500                0.000000

[44810 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.001036                 0.002198
1970-01-01 01:00:00.031250                0.001036                 0.002198
1970-01-01 01:00:00.062500                0.000000                 0.001465
1970-01-01 01:00:00.093750                0.001036                 0.000733
1970-01-01 01:00:00.125000                0.001036                 0.002198
...                                            ...                      ...
1970-01-01 01:46:40.468750                0.003610                 0.002553
1970-01-01 01:46:40.500000                0.000000                 0.000000
1970-01-01 01:46:40.531250                0.003610                 0.002553
1970-01-01 01:46:40.562500                0.000000                 0.005105
1970-01-01 01:46:40.593750                0.000000                 0.000000

[89620 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:45:24 to 1970-01-01 01:45:24.500000 for index 5448
calculating features from 809472 to 809535 for index 5448
processed hour 1 - start: 460800 | end: 809574
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.004144                 0.001465
1970-01-01 01:00:00.062500                0.009324                 0.013187
1970-01-01 01:00:00.125000                0.004144                 0.003663
1970-01-01 01:00:00.187500                0.007252                 0.002930
1970-01-01 01:00:00.250000                0.005180                 0.004396
...                                            ...                      ...
1970-01-01 01:45:24.500000                0.015541                 0.018315
1970-01-01 01:45:24.562500                0.015541                 0.003663
1970-01-01 01:45:24.625000                0.018649                 0.006593
1970-01-01 01:45:24.687500                0.018649                 0.006593
1970-01-01 01:45:24.750000                0.005180                 0.018315

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.005180
1970-01-01 01:00:00.062500                0.001036
1970-01-01 01:00:00.125000                0.002590
1970-01-01 01:00:00.187500                0.007770
1970-01-01 01:00:00.250000                0.000000
...                                            ...
1970-01-01 01:45:24.500000                0.019685
1970-01-01 01:45:24.562500                0.018131
1970-01-01 01:45:24.625000                0.007770
1970-01-01 01:45:24.687500                0.008288
1970-01-01 01:45:24.750000                0.019167

[43597 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.002072                 0.000000
1970-01-01 01:00:00.031250                0.004144                 0.001465
1970-01-01 01:00:00.062500                0.007252                 0.002930
1970-01-01 01:00:00.093750                0.009324                 0.013187
1970-01-01 01:00:00.125000                0.003108                 0.003663
...                                            ...                      ...
1970-01-01 01:45:24.656250                0.018649                 0.004396
1970-01-01 01:45:24.687500                0.008288                 0.006593
1970-01-01 01:45:24.718750                0.018649                 0.002198
1970-01-01 01:45:24.750000                0.002072                 0.018315
1970-01-01 01:45:24.781250                0.005180                 0.000000

[87194 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:37:42.500000 to 1970-01-01 01:37:43 for index 4525
calculating features from 750400 to 750463 for index 4525
processed hour 1 - start: 460800 | end: 750519
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.005965                 0.006438
1970-01-01 01:00:00.062500                0.004709                 0.005328
1970-01-01 01:00:00.125000                0.005023                 0.006216
1970-01-01 01:00:00.187500                0.005651                 0.004884
1970-01-01 01:00:00.250000                0.004081                 0.004440
...                                            ...                      ...
1970-01-01 01:37:43.125000                0.004144                 0.008791
1970-01-01 01:37:43.187500                0.008288                 0.007326
1970-01-01 01:37:43.250000                0.004144                 0.005861
1970-01-01 01:37:43.312500                0.008288                 0.004396
1970-01-01 01:37:43.375000                0.008288                 0.000733

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.002355
1970-01-01 01:00:00.062500                0.004709
1970-01-01 01:00:00.125000                0.001570
1970-01-01 01:00:00.187500                0.000314
1970-01-01 01:00:00.250000                0.002355
...                                            ...
1970-01-01 01:37:43.125000                0.015023
1970-01-01 01:37:43.187500                0.014505
1970-01-01 01:37:43.250000                0.005698
1970-01-01 01:37:43.312500                0.009843
1970-01-01 01:37:43.375000                0.003626

[36215 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.005023                 0.006438
1970-01-01 01:00:00.031250                0.005965                 0.005772
1970-01-01 01:00:00.062500                0.004709                 0.005328
1970-01-01 01:00:00.093750                0.003767                 0.002664
1970-01-01 01:00:00.125000                0.004081                 0.006216
...                                            ...                      ...
1970-01-01 01:37:43.281250                0.003108                 0.005861
1970-01-01 01:37:43.312500                0.008288                 0.000733
1970-01-01 01:37:43.343750                0.004144                 0.004396
1970-01-01 01:37:43.375000                0.008288                 0.000000
1970-01-01 01:37:43.406250                0.001036                 0.000733

[72430 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:43:23 to 1970-01-01 01:43:23.500000 for index 5206
calculating features from 793984 to 794047 for index 5206
processed hour 1 - start: 460800 | end: 794070
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.003140                 0.001554
1970-01-01 01:00:00.062500                0.005023                 0.000444
1970-01-01 01:00:00.125000                0.001884                 0.000444
1970-01-01 01:00:00.187500                0.002198                 0.001998
1970-01-01 01:00:00.250000                0.003140                 0.002442
...                                            ...                      ...
1970-01-01 01:43:23.375000                0.003454                 0.003330
1970-01-01 01:43:23.437500                0.002198                 0.002664
1970-01-01 01:43:23.500000                0.002198                 0.003774
1970-01-01 01:43:23.562500                0.001884                 0.002886
1970-01-01 01:43:23.625000                0.007849                 0.002220

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.000785
1970-01-01 01:00:00.062500                0.001099
1970-01-01 01:00:00.125000                0.000157
1970-01-01 01:00:00.187500                0.000785
1970-01-01 01:00:00.250000                0.001570
...                                            ...
1970-01-01 01:43:23.375000                0.000157
1970-01-01 01:43:23.437500                0.000314
1970-01-01 01:43:23.500000                0.002512
1970-01-01 01:43:23.562500                0.000628
1970-01-01 01:43:23.625000                0.002198

[41659 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.003140                 0.000444
1970-01-01 01:00:00.031250                0.001570                 0.001554
1970-01-01 01:00:00.062500                0.003454                 0.000222
1970-01-01 01:00:00.093750                0.005023                 0.000444
1970-01-01 01:00:00.125000                0.001884                 0.000444
...                                            ...                      ...
1970-01-01 01:43:23.531250                0.002198                 0.000666
1970-01-01 01:43:23.562500                0.000942                 0.002886
1970-01-01 01:43:23.593750                0.001884                 0.001110
1970-01-01 01:43:23.625000                0.007849                 0.002220
1970-01-01 01:43:23.656250                0.000314                 0.000000

[83318 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:47:25 to 1970-01-01 01:47:25.500000 for index 5690
calculating features from 824960 to 825023 for index 5690
processed hour 1 - start: 460800 | end: 825078
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.010830                 0.017868
1970-01-01 01:00:00.062500                0.010830                 0.015316
1970-01-01 01:00:00.125000                0.007220                 0.017868
1970-01-01 01:00:00.187500                0.007220                 0.012763
1970-01-01 01:00:00.250000                0.007220                 0.020421
...                                            ...                      ...
1970-01-01 01:47:25.625000                0.000628                 0.001532
1970-01-01 01:47:25.687500                0.001570                 0.001110
1970-01-01 01:47:25.750000                0.000314                 0.000222
1970-01-01 01:47:25.812500                0.000628                 0.000444
1970-01-01 01:47:25.875000                0.000000                 0.000000

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.007220
1970-01-01 01:00:00.062500                0.003610
1970-01-01 01:00:00.125000                0.000000
1970-01-01 01:00:00.187500                0.009025
1970-01-01 01:00:00.250000                0.010830
...                                            ...
1970-01-01 01:47:25.625000                0.001083
1970-01-01 01:47:25.687500                0.000471
1970-01-01 01:47:25.750000                0.000157
1970-01-01 01:47:25.812500                0.000314
1970-01-01 01:47:25.875000                0.000000

[45535 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.010830                 0.017868
1970-01-01 01:00:00.031250                0.003610                 0.012763
1970-01-01 01:00:00.062500                0.010830                 0.005105
1970-01-01 01:00:00.093750                0.007220                 0.015316
1970-01-01 01:00:00.125000                0.007220                 0.017868
...                                            ...                      ...
1970-01-01 01:47:25.781250                0.000000                 0.000000
1970-01-01 01:47:25.812500                0.000628                 0.000444
1970-01-01 01:47:25.843750                0.000000                 0.000000
1970-01-01 01:47:25.875000                0.000000                 0.000000
1970-01-01 01:47:25.906250                0.000000                 0.000000

[91070 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:42:22.500000 to 1970-01-01 01:42:23 for index 5085
calculating features from 786240 to 786303 for index 5085
processed hour 1 - start: 460800 | end: 786318
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                 0.01444                 0.025526
1970-01-01 01:00:00.062500                 0.01444                 0.012763
1970-01-01 01:00:00.125000                 0.01805                 0.012763
1970-01-01 01:00:00.187500                 0.01444                 0.010210
1970-01-01 01:00:00.250000                 0.00722                 0.020421
...                                            ...                      ...
1970-01-01 01:42:22.812500                 0.01083                 0.012763
1970-01-01 01:42:22.875000                 0.01444                 0.000000
1970-01-01 01:42:22.937500                 0.01805                 0.005105
1970-01-01 01:42:23.000000                 0.01805                 0.005105
1970-01-01 01:42:23.062500                 0.01805                 0.005105

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.014440
1970-01-01 01:00:00.062500                0.000000
1970-01-01 01:00:00.125000                0.007220
1970-01-01 01:00:00.187500                0.001805
1970-01-01 01:00:00.250000                0.016245
...                                            ...
1970-01-01 01:42:22.812500                0.000000
1970-01-01 01:42:22.875000                0.000000
1970-01-01 01:42:22.937500                0.001805
1970-01-01 01:42:23.000000                0.012635
1970-01-01 01:42:23.062500                0.003610

[40690 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                 0.01083                 0.025526
1970-01-01 01:00:00.031250                 0.01444                 0.010210
1970-01-01 01:00:00.062500                 0.01444                 0.012763
1970-01-01 01:00:00.093750                 0.01444                 0.012763
1970-01-01 01:00:00.125000                 0.00722                 0.012763
...                                            ...                      ...
1970-01-01 01:42:22.968750                 0.01805                 0.002553
1970-01-01 01:42:23.000000                 0.01444                 0.005105
1970-01-01 01:42:23.031250                 0.01805                 0.002553
1970-01-01 01:42:23.062500                 0.00361                 0.005105
1970-01-01 01:42:23.093750                 0.01805                 0.000000

[81380 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
1970-01-01 00:00:01.500               0.000000                0.000000
1970-01-01 00:00:02.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:57.500               0.005180                0.002198
1970-01-01 00:59:58.000               0.004144                0.001465
1970-01-01 00:59:58.500               0.006216                0.004396
1970-01-01 00:59:59.000               0.004144                0.004396
1970-01-01 00:59:59.500               0.004144                0.005128

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.000314
1970-01-01 00:00:00.500               0.000000
1970-01-01 00:00:01.000               0.000000
1970-01-01 00:00:01.500               0.000000
1970-01-01 00:00:02.000               0.000000
...                                        ...
1970-01-01 00:59:57.500               0.003108
1970-01-01 00:59:58.000               0.003626
1970-01-01 00:59:58.500               0.000518
1970-01-01 00:59:59.000               0.002590
1970-01-01 00:59:59.500               0.001036

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.250               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.003108                0.002198
1970-01-01 00:59:59.000               0.000000                0.004396
1970-01-01 00:59:59.250               0.004144                0.000733
1970-01-01 00:59:59.500               0.001036                0.005128
1970-01-01 00:59:59.750               0.004144                0.002198

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.182401                0.127442
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:01.000               0.000314                0.000444
1970-01-01 00:00:01.500               0.000314                0.000222
1970-01-01 00:00:02.000               0.000314                0.000222
...                                        ...                     ...
1970-01-01 00:59:57.500               0.001036                0.002930
1970-01-01 00:59:58.000               0.001036                0.002930
1970-01-01 00:59:58.500               0.001036                0.001465
1970-01-01 00:59:59.000               0.000000                0.000000
1970-01-01 00:59:59.500               0.003108                0.005128

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000           8.486663e-02
1970-01-01 00:00:00.500           6.279114e-04
1970-01-01 00:00:01.000           2.220446e-16
1970-01-01 00:00:01.500           1.569779e-04
1970-01-01 00:00:02.000           1.569779e-04
...                                        ...
1970-01-01 00:59:57.500           4.144216e-03
1970-01-01 00:59:58.000           5.180269e-03
1970-01-01 00:59:58.500           2.590135e-03
1970-01-01 00:59:59.000           0.000000e+00
1970-01-01 00:59:59.500           6.734350e-03

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.182401                0.127442
1970-01-01 00:00:00.250               0.000314                0.000666
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000314                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.001036                0.000733
1970-01-01 00:59:59.000               0.000000                0.000000
1970-01-01 00:59:59.250               0.000000                0.000000
1970-01-01 00:59:59.500               0.000000                0.001465
1970-01-01 00:59:59.750               0.003108                0.005128

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:01.000               0.000314                0.000222
1970-01-01 00:00:01.500               0.000000                0.000000
1970-01-01 00:00:02.000               0.000942                0.001998
...                                        ...                     ...
1970-01-01 00:59:57.500               0.000942                0.001332
1970-01-01 00:59:58.000               0.000942                0.000666
1970-01-01 00:59:58.500               0.001256                0.000666
1970-01-01 00:59:59.000               0.000942                0.000666
1970-01-01 00:59:59.500               0.000942                0.001554

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000           3.139557e-04
1970-01-01 00:00:00.500           0.000000e+00
1970-01-01 00:00:01.000           1.569779e-04
1970-01-01 00:00:01.500           0.000000e+00
1970-01-01 00:00:02.000           3.139557e-04
...                                        ...
1970-01-01 00:59:57.500           9.418672e-04
1970-01-01 00:59:58.000           2.220446e-16
1970-01-01 00:59:58.500           1.569779e-04
1970-01-01 00:59:59.000           0.000000e+00
1970-01-01 00:59:59.500           1.255823e-03

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.250               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000314                0.000222
...                                        ...                     ...
1970-01-01 00:59:58.750               0.001256                0.000666
1970-01-01 00:59:59.000               0.000942                0.000666
1970-01-01 00:59:59.250               0.000628                0.000222
1970-01-01 00:59:59.500               0.000942                0.001554
1970-01-01 00:59:59.750               0.000314                0.000222

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.004662                0.003297
1970-01-01 00:00:00.500               0.000628                0.001776
1970-01-01 00:00:01.000               0.000000                0.000444
1970-01-01 00:00:01.500               0.000314                0.000444
1970-01-01 00:00:02.000               0.000314                0.000222
...                                        ...                     ...
1970-01-01 00:59:57.500               0.000000                0.000000
1970-01-01 00:59:58.000               0.003610                0.002553
1970-01-01 00:59:58.500               0.003610                0.002553
1970-01-01 00:59:59.000               0.003610                0.002553
1970-01-01 00:59:59.500               0.003610                0.002553

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000           1.022711e-02
1970-01-01 00:00:00.500           7.848893e-04
1970-01-01 00:00:01.000           6.279114e-04
1970-01-01 00:00:01.500           3.469447e-18
1970-01-01 00:00:02.000           0.000000e+00
...                                        ...
1970-01-01 00:59:57.500           0.000000e+00
1970-01-01 00:59:58.000           5.414916e-03
1970-01-01 00:59:58.500           5.414916e-03
1970-01-01 00:59:59.000           1.804972e-03
1970-01-01 00:59:59.500           1.804972e-03

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.004662                0.003297
1970-01-01 00:00:00.250               0.000314                0.000000
1970-01-01 00:00:00.500               0.000628                0.000666
1970-01-01 00:00:00.750               0.000314                0.001776
1970-01-01 00:00:01.000               0.000000                0.000444
...                                        ...                     ...
1970-01-01 00:59:58.750               0.003610                0.002553
1970-01-01 00:59:59.000               0.000000                0.000000
1970-01-01 00:59:59.250               0.003610                0.002553
1970-01-01 00:59:59.500               0.000000                0.000000
1970-01-01 00:59:59.750               0.003610                0.002553

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.029634                0.023307
1970-01-01 00:00:00.500               0.000628                0.000444
1970-01-01 00:00:01.000               0.000314                0.000000
1970-01-01 00:00:01.500               0.000000                0.000000
1970-01-01 00:00:02.000               0.000314                0.000444
...                                        ...                     ...
1970-01-01 00:59:57.500               0.003610                0.005105
1970-01-01 00:59:58.000               0.003610                0.005105
1970-01-01 00:59:58.500               0.003610                0.002553
1970-01-01 00:59:59.000               0.003610                0.002553
1970-01-01 00:59:59.500               0.000000                0.000000

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.021000
1970-01-01 00:00:00.500               0.000628
1970-01-01 00:00:01.000               0.000314
1970-01-01 00:00:01.500               0.000000
1970-01-01 00:00:02.000               0.000157
...                                        ...
1970-01-01 00:59:57.500               0.005415
1970-01-01 00:59:58.000               0.009025
1970-01-01 00:59:58.500               0.003610
1970-01-01 00:59:59.000               0.010830
1970-01-01 00:59:59.500               0.007220

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.029634                0.023307
1970-01-01 00:00:00.250               0.001884                0.000666
1970-01-01 00:00:00.500               0.000314                0.000444
1970-01-01 00:00:00.750               0.000628                0.000000
1970-01-01 00:00:01.000               0.000314                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.003610                0.002553
1970-01-01 00:59:59.000               0.003610                0.002553
1970-01-01 00:59:59.250               0.003610                0.002553
1970-01-01 00:59:59.500               0.000000                0.000000
1970-01-01 00:59:59.750               0.000000                0.000000

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.002590                0.001832
1970-01-01 00:00:00.500               0.001256                0.003330
1970-01-01 00:00:01.000               0.000314                0.000666
1970-01-01 00:00:01.500               0.000314                0.000888
1970-01-01 00:00:02.000               0.000314                0.000444
...                                        ...                     ...
1970-01-01 00:59:57.500               0.001036                0.004396
1970-01-01 00:59:58.000               0.002072                0.001465
1970-01-01 00:59:58.500               0.001036                0.002198
1970-01-01 00:59:59.000               0.001036                0.002930
1970-01-01 00:59:59.500               0.001036                0.002198

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.007810
1970-01-01 00:00:00.500               0.000785
1970-01-01 00:00:01.000               0.002355
1970-01-01 00:00:01.500               0.000157
1970-01-01 00:00:02.000               0.000471
...                                        ...
1970-01-01 00:59:57.500               0.007252
1970-01-01 00:59:58.000               0.003108
1970-01-01 00:59:58.500               0.003108
1970-01-01 00:59:59.000               0.004662
1970-01-01 00:59:59.500               0.001036

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.002590                0.001832
1970-01-01 00:00:00.250               0.000942                0.001332
1970-01-01 00:00:00.500               0.000000                0.000888
1970-01-01 00:00:00.750               0.001256                0.003330
1970-01-01 00:00:01.000               0.000314                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.001036                0.002198
1970-01-01 00:59:59.000               0.000000                0.002930
1970-01-01 00:59:59.250               0.001036                0.002198
1970-01-01 00:59:59.500               0.001036                0.000733
1970-01-01 00:59:59.750               0.001036                0.002198

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.005698                0.004029
1970-01-01 00:00:00.500               0.002512                0.004218
1970-01-01 00:00:01.000               0.001256                0.000222
1970-01-01 00:00:01.500               0.010047                0.002664
1970-01-01 00:00:02.000               0.004709                0.004884
...                                        ...                     ...
1970-01-01 00:59:57.500               0.003108                0.005861
1970-01-01 00:59:58.000               0.002072                0.004396
1970-01-01 00:59:58.500               0.001036                0.001465
1970-01-01 00:59:59.000               0.004144                0.005861
1970-01-01 00:59:59.500               0.007252                0.018315

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.008296
1970-01-01 00:00:00.500               0.000314
1970-01-01 00:00:01.000               0.000314
1970-01-01 00:00:01.500               0.002983
1970-01-01 00:00:02.000               0.003610
...                                        ...
1970-01-01 00:59:57.500               0.013987
1970-01-01 00:59:58.000               0.008806
1970-01-01 00:59:58.500               0.002590
1970-01-01 00:59:59.000               0.011915
1970-01-01 00:59:59.500               0.052839

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.005698                0.004029
1970-01-01 00:00:00.250               0.000942                0.002442
1970-01-01 00:00:00.500               0.000942                0.000222
1970-01-01 00:00:00.750               0.002512                0.004218
1970-01-01 00:00:01.000               0.001256                0.000222
...                                        ...                     ...
1970-01-01 00:59:58.750               0.001036                0.001465
1970-01-01 00:59:59.000               0.001036                0.002198
1970-01-01 00:59:59.250               0.004144                0.005861
1970-01-01 00:59:59.500               0.007252                0.018315
1970-01-01 00:59:59.750               0.007252                0.018315

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.002198                0.001554
1970-01-01 00:00:00.500               0.000942                0.000666
1970-01-01 00:00:01.000               0.001256                0.000888
1970-01-01 00:00:01.500               0.004395                0.002664
1970-01-01 00:00:02.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:57.500               0.004144                0.003663
1970-01-01 00:59:58.000               0.011397                0.008059
1970-01-01 00:59:58.500               0.001036                0.002930
1970-01-01 00:59:59.000               0.012433                0.007326
1970-01-01 00:59:59.500               0.002072                0.005861

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.001413
1970-01-01 00:00:00.500               0.000471
1970-01-01 00:00:01.000               0.000628
1970-01-01 00:00:01.500               0.003140
1970-01-01 00:00:02.000               0.000000
...                                        ...
1970-01-01 00:59:57.500               0.007770
1970-01-01 00:59:58.000               0.003108
1970-01-01 00:59:58.500               0.005698
1970-01-01 00:59:59.000               0.001036
1970-01-01 00:59:59.500               0.013987

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.250               0.002198                0.001554
1970-01-01 00:00:00.500               0.000942                0.000666
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.001256                0.000888
...                                        ...                     ...
1970-01-01 00:59:58.750               0.001036                0.000733
1970-01-01 00:59:59.000               0.010361                0.005861
1970-01-01 00:59:59.250               0.012433                0.007326
1970-01-01 00:59:59.500               0.002072                0.003663
1970-01-01 00:59:59.750               0.002072                0.005861

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.077659                0.064055
1970-01-01 00:00:00.500               0.003140                0.005994
1970-01-01 00:00:01.000               0.001884                0.002442
1970-01-01 00:00:01.500               0.000942                0.001998
1970-01-01 00:00:02.000               0.000628                0.001332
...                                        ...                     ...
1970-01-01 00:59:57.500               0.002198                0.001998
1970-01-01 00:59:58.000               0.002198                0.004662
1970-01-01 00:59:58.500               0.010988                0.007548
1970-01-01 00:59:59.000               0.003767                0.003996
1970-01-01 00:59:59.500               0.000314                0.000444

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.070875
1970-01-01 00:00:00.500               0.010518
1970-01-01 00:00:01.000               0.006279
1970-01-01 00:00:01.500               0.005023
1970-01-01 00:00:02.000               0.003454
...                                        ...
1970-01-01 00:59:57.500               0.000785
1970-01-01 00:59:58.000               0.010988
1970-01-01 00:59:58.500               0.024018
1970-01-01 00:59:59.000               0.003767
1970-01-01 00:59:59.500               0.002826

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.077659            6.405518e-02
1970-01-01 00:00:00.250               0.001570            2.664003e-03
1970-01-01 00:00:00.500               0.002512            3.108003e-03
1970-01-01 00:00:00.750               0.003140            5.994006e-03
1970-01-01 00:00:01.000               0.001884            2.442002e-03
...                                        ...                     ...
1970-01-01 00:59:58.750               0.000942            1.110001e-03
1970-01-01 00:59:59.000               0.000942            1.110223e-16
1970-01-01 00:59:59.250               0.003767            3.996004e-03
1970-01-01 00:59:59.500               0.000314            0.000000e+00
1970-01-01 00:59:59.750               0.000314            4.440004e-04

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
1970-01-01 00:00:01.500               0.000000                0.003552
1970-01-01 00:00:02.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:57.500               0.001884                0.001332
1970-01-01 00:59:58.000               0.001570                0.002664
1970-01-01 00:59:58.500               0.001884                0.001998
1970-01-01 00:59:59.000               0.001884                0.000666
1970-01-01 00:59:59.500               0.001884                0.001332

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000           3.139557e-04
1970-01-01 00:00:00.500           0.000000e+00
1970-01-01 00:00:01.000           0.000000e+00
1970-01-01 00:00:01.500           2.511646e-03
1970-01-01 00:00:02.000           0.000000e+00
...                                        ...
1970-01-01 00:59:57.500           1.569779e-04
1970-01-01 00:59:58.000           9.418672e-04
1970-01-01 00:59:58.500           1.110223e-16
1970-01-01 00:59:59.000           7.848893e-04
1970-01-01 00:59:59.500           7.848893e-04

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.250               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.001884                0.001998
1970-01-01 00:59:59.000               0.001256                0.000444
1970-01-01 00:59:59.250               0.001884                0.000666
1970-01-01 00:59:59.500               0.001884                0.000222
1970-01-01 00:59:59.750               0.001884                0.001332

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 01:41:21 to 1970-01-01 01:41:21.500000 for index 4962
calculating features from 97296 to 97303 for index 4962
processed hour 1 - start: 57600 | end: 97308
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.006216                0.000733
1970-01-01 01:00:00.500               0.007252                0.002198
1970-01-01 01:00:01.000               0.007252                0.003663
1970-01-01 01:00:01.500               0.004144                0.002930
1970-01-01 01:00:02.000               0.004144                0.002930
...                                        ...                     ...
1970-01-01 01:41:19.500               0.018649                0.045421
1970-01-01 01:41:20.000               0.008288                0.051282
1970-01-01 01:41:20.500               0.020721                0.040293
1970-01-01 01:41:21.000               0.027973                0.060806
1970-01-01 01:41:21.500               0.011397                0.006593

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.003626
1970-01-01 01:00:00.500               0.000000
1970-01-01 01:00:01.000               0.000518
1970-01-01 01:00:01.500               0.003626
1970-01-01 01:00:02.000               0.003626
...                                        ...
1970-01-01 01:41:19.500               0.050249
1970-01-01 01:41:20.000               0.087547
1970-01-01 01:41:20.500               0.067344
1970-01-01 01:41:21.000               0.089619
1970-01-01 01:41:21.500               0.000000

[4964 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.003108                0.000733
1970-01-01 01:00:00.250               0.006216                0.000000
1970-01-01 01:00:00.500               0.007252                0.002198
1970-01-01 01:00:00.750               0.007252                0.002198
1970-01-01 01:00:01.000               0.007252                0.003663
...                                        ...                     ...
1970-01-01 01:41:20.750               0.020721                0.040293
1970-01-01 01:41:21.000               0.027973                0.060806
1970-01-01 01:41:21.250               0.007252                0.007326
1970-01-01 01:41:21.500               0.011397                0.006593
1970-01-01 01:41:21.750               0.000000                0.000000

[9928 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000    0.000000     -0.200463    0.0  2.106994e-20       1.0
1          0.007812    0.000000     -0.200463    0.0  1.879714e-06       1.0
2          0.015625    0.000000     -0.200463    0.0  3.656027e-06       1.0
3          0.023438    0.000000     -0.200463    0.0  5.370973e-06       1.0
4          0.031250    0.000000     -0.200463    0.0  7.062509e-06       1.0
...             ...         ...           ...    ...           ...       ...
755305  5900.820312    0.003330      0.003330    0.0  3.330003e-03       0.0
755306  5900.828125    0.000222      0.000222    0.0  2.220002e-04       0.0
755307  5900.835938    0.005994      0.005994    0.0  5.994006e-03       0.0
755308  5900.843750    0.000222      0.000222    0.0  2.220002e-04       0.0
755309  5900.851562    0.000222      0.000222    0.0  2.220002e-04       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
755305                 0.0
755306                 0.0
755307                 0.0
755308                 0.0
755309                 0.0

[755310 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000                0.00000                0.000000
1970-01-01 00:00:00.500                0.00000                0.000000
1970-01-01 00:00:01.000                0.00000                0.000000
1970-01-01 00:00:01.500                0.00000                0.000000
1970-01-01 00:00:02.000                0.00000                0.000000
...                                        ...                     ...
1970-01-01 00:59:57.500                0.01083                0.017868
1970-01-01 00:59:58.000                0.01444                0.015316
1970-01-01 00:59:58.500                0.00000                0.005105
1970-01-01 00:59:59.000                0.01444                0.007658
1970-01-01 00:59:59.500                0.00361                0.002553

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.000314
1970-01-01 00:00:00.500               0.000000
1970-01-01 00:00:01.000               0.000000
1970-01-01 00:00:01.500               0.000000
1970-01-01 00:00:02.000               0.000000
...                                        ...
1970-01-01 00:59:57.500               0.014440
1970-01-01 00:59:58.000               0.003610
1970-01-01 00:59:58.500               0.003610
1970-01-01 00:59:59.000               0.016245
1970-01-01 00:59:59.500               0.009025

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000                0.00000            0.000000e+00
1970-01-01 00:00:00.250                0.00000            0.000000e+00
1970-01-01 00:00:00.500                0.00000            0.000000e+00
1970-01-01 00:00:00.750                0.00000            0.000000e+00
1970-01-01 00:00:01.000                0.00000            0.000000e+00
...                                        ...                     ...
1970-01-01 00:59:58.750                0.00000            5.105232e-03
1970-01-01 00:59:59.000                0.00722            8.881784e-16
1970-01-01 00:59:59.250                0.01444            7.657847e-03
1970-01-01 00:59:59.500                0.00361            0.000000e+00
1970-01-01 00:59:59.750                0.00361            2.552616e-03

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 01:38:29 to 1970-01-01 01:38:29.500000 for index 4618
calculating features from 94544 to 94551 for index 4618
processed hour 1 - start: 57600 | end: 94559
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.002072                0.008059
1970-01-01 01:00:00.500               0.002072                0.008791
1970-01-01 01:00:01.000               0.003108                0.005128
1970-01-01 01:00:01.500               0.001036                0.003663
1970-01-01 01:00:02.000               0.001036                0.001465
...                                        ...                     ...
1970-01-01 01:38:27.500               0.007220                0.017868
1970-01-01 01:38:28.000               0.007220                0.015316
1970-01-01 01:38:28.500               0.014440                0.028079
1970-01-01 01:38:29.000               0.003610                0.010210
1970-01-01 01:38:29.500               0.003610                0.000000

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.017613
1970-01-01 01:00:00.500               0.021757
1970-01-01 01:00:01.000               0.012433
1970-01-01 01:00:01.500               0.008288
1970-01-01 01:00:02.000               0.003108
...                                        ...
1970-01-01 01:38:27.500               0.045124
1970-01-01 01:38:28.000               0.041514
1970-01-01 01:38:28.500               0.034294
1970-01-01 01:38:29.000               0.025270
1970-01-01 01:38:29.500               0.003610

[4620 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.002072                0.005128
1970-01-01 01:00:00.250               0.002072                0.008059
1970-01-01 01:00:00.500               0.002072                0.008791
1970-01-01 01:00:00.750               0.002072                0.007326
1970-01-01 01:00:01.000               0.003108                0.005128
...                                        ...                     ...
1970-01-01 01:38:28.750               0.007220                0.000000
1970-01-01 01:38:29.000               0.003610                0.010210
1970-01-01 01:38:29.250               0.003610                0.005105
1970-01-01 01:38:29.500               0.003610                0.000000
1970-01-01 01:38:29.750               0.000000                0.000000

[9240 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000    0.000000     -0.200463    0.0  2.106994e-20       1.0
1          0.007812    0.000000     -0.200463    0.0  1.879714e-06       1.0
2          0.015625    0.000000     -0.200463    0.0  3.656027e-06       1.0
3          0.023438    0.000000     -0.200463    0.0  5.370973e-06       1.0
4          0.031250    0.000000     -0.200463    0.0  7.062509e-06       1.0
...             ...         ...           ...    ...           ...       ...
925747  7232.398438    0.000222      0.000222    0.0  2.220002e-04       0.0
925748  7232.406250    0.000222      0.000222    0.0  2.220002e-04       0.0
925749  7232.414062    0.000222      0.000222    0.0  2.220002e-04       0.0
925750  7232.421875    0.000222      0.000222    0.0  2.220002e-04       0.0
925751  7232.429688    0.000222      0.000222    0.0  2.220002e-04       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
925747                 0.0
925748                 0.0
925749                 0.0
925750                 0.0
925751                 0.0

[925752 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000                0.00000                0.000000
1970-01-01 00:00:00.500                0.00000                0.000000
1970-01-01 00:00:01.000                0.00000                0.000000
1970-01-01 00:00:01.500                0.00000                0.000000
1970-01-01 00:00:02.000                0.00000                0.000000
...                                        ...                     ...
1970-01-01 00:59:57.500                0.01444                0.010210
1970-01-01 00:59:58.000                0.01083                0.010210
1970-01-01 00:59:58.500                0.00361                0.002553
1970-01-01 00:59:59.000                0.01083                0.022974
1970-01-01 00:59:59.500                0.00722                0.005105

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000           3.139557e-04
1970-01-01 00:00:00.500           0.000000e+00
1970-01-01 00:00:01.000           0.000000e+00
1970-01-01 00:00:01.500           0.000000e+00
1970-01-01 00:00:02.000           0.000000e+00
...                                        ...
1970-01-01 00:59:57.500           1.776357e-15
1970-01-01 00:59:58.000           1.804972e-03
1970-01-01 00:59:58.500           1.082983e-02
1970-01-01 00:59:59.000           5.414916e-03
1970-01-01 00:59:59.500           3.609944e-03

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000                0.00000                0.000000
1970-01-01 00:00:00.250                0.00000                0.000000
1970-01-01 00:00:00.500                0.00000                0.000000
1970-01-01 00:00:00.750                0.00000                0.000000
1970-01-01 00:00:01.000                0.00000                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750                0.00361                0.002553
1970-01-01 00:59:59.000                0.00722                0.000000
1970-01-01 00:59:59.250                0.01083                0.022974
1970-01-01 00:59:59.500                0.00361                0.005105
1970-01-01 00:59:59.750                0.00722                0.005105

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 01:38:20 to 1970-01-01 01:38:20.500000 for index 4600
calculating features from 94400 to 94407 for index 4600
processed hour 1 - start: 57600 | end: 94414
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.002512                0.000222
1970-01-01 01:00:00.500               0.001256                0.000888
1970-01-01 01:00:01.000               0.002826                0.001998
1970-01-01 01:00:01.500               0.001256                0.000444
1970-01-01 01:00:02.000               0.002512                0.002442
...                                        ...                     ...
1970-01-01 01:38:18.500               0.002512                0.003996
1970-01-01 01:38:19.000               0.001256                0.001776
1970-01-01 01:38:19.500               0.000628                0.001332
1970-01-01 01:38:20.000               0.000942                0.001110
1970-01-01 01:38:20.500               0.001570                0.001332

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.001256
1970-01-01 01:00:00.500               0.000942
1970-01-01 01:00:01.000               0.006279
1970-01-01 01:00:01.500               0.000314
1970-01-01 01:00:02.000               0.002355
...                                        ...
1970-01-01 01:38:18.500               0.011302
1970-01-01 01:38:19.000               0.001413
1970-01-01 01:38:19.500               0.001099
1970-01-01 01:38:20.000               0.000628
1970-01-01 01:38:20.500               0.002198

[4602 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.002512                0.000222
1970-01-01 01:00:00.250               0.001884                0.000222
1970-01-01 01:00:00.500               0.001256                0.000888
1970-01-01 01:00:00.750               0.000314                0.000000
1970-01-01 01:00:01.000               0.002826                0.001998
...                                        ...                     ...
1970-01-01 01:38:19.750               0.000628                0.001332
1970-01-01 01:38:20.000               0.000942                0.001110
1970-01-01 01:38:20.250               0.000942                0.000222
1970-01-01 01:38:20.500               0.000942                0.001332
1970-01-01 01:38:20.750               0.001570                0.000000

[9204 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000    0.000000     -0.200463    0.0  2.106994e-20       1.0
1          0.007812    0.000000     -0.200463    0.0  1.879714e-06       1.0
2          0.015625    0.000000     -0.200463    0.0  3.656027e-06       1.0
3          0.023438    0.000000     -0.200463    0.0  5.370973e-06       1.0
4          0.031250    0.000000     -0.200463    0.0  7.062509e-06       1.0
...             ...         ...           ...    ...           ...       ...
786313  6143.070312    4.898470      4.898470    0.0  4.898470e+00       0.0
786314  6143.078125    4.883154      4.883154    0.0  4.883154e+00       0.0
786315  6143.085938    4.903575      4.903575    0.0  4.903575e+00       0.0
786316  6143.093750    4.883154      4.883154    0.0  4.883154e+00       0.0
786317  6143.101562    4.888259      4.888259    0.0  4.888259e+00       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
786313                 0.0
786314                 0.0
786315                 0.0
786316                 0.0
786317                 0.0

[786318 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 01:37:54 to 1970-01-01 01:37:54.500000 for index 4548
calculating features from 93984 to 93991 for index 4548
processed hour 1 - start: 57600 | end: 93997
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.003610                0.005105
1970-01-01 01:00:00.500               0.003610                0.007658
1970-01-01 01:00:01.000               0.003610                0.020421
1970-01-01 01:00:01.500               0.083029                0.193999
1970-01-01 01:00:02.000               0.027973                0.053480
...                                        ...                     ...
1970-01-01 01:37:52.500               0.000314                0.000222
1970-01-01 01:37:53.000               0.000314                0.000222
1970-01-01 01:37:53.500               0.000314                0.000222
1970-01-01 01:37:54.000               0.000314                0.000222
1970-01-01 01:37:54.500               0.000314                0.000222

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.007220
1970-01-01 01:00:00.500               0.000000
1970-01-01 01:00:01.000               0.023465
1970-01-01 01:00:01.500               0.226545
1970-01-01 01:00:02.000               0.109822
...                                        ...
1970-01-01 01:37:52.500               0.000157
1970-01-01 01:37:53.000               0.000314
1970-01-01 01:37:53.500               0.000000
1970-01-01 01:37:54.000               0.000157
1970-01-01 01:37:54.500               0.000157

[4550 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.003610                0.005105
1970-01-01 01:00:00.250               0.000000                0.000000
1970-01-01 01:00:00.500               0.003610                0.002553
1970-01-01 01:00:00.750               0.003610                0.007658
1970-01-01 01:00:01.000               0.003610                0.002553
...                                        ...                     ...
1970-01-01 01:37:53.750               0.000314                0.000222
1970-01-01 01:37:54.000               0.000314                0.000000
1970-01-01 01:37:54.250               0.000314                0.000222
1970-01-01 01:37:54.500               0.000314                0.000222
1970-01-01 01:37:54.750               0.000000                0.000000

[9100 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label  auto_signal  pred_art  \
0          0.000000    0.000000     -0.236911    0.0     0.000000       0.0
1          0.007812    0.000000     -0.236911    0.0     0.000000       0.0
2          0.015625    0.000000     -0.236911    0.0     0.000000       0.0
3          0.023438    0.000000     -0.236911    0.0     0.000000       0.0
4          0.031250    0.000000     -0.236911    0.0     0.000000       0.0
...             ...         ...           ...    ...          ...       ...
685435  5354.960938    7.502138      7.502138    0.0     7.502138       0.0
685436  5354.968750    7.425559      7.425559    0.0     7.425559       0.0
685437  5354.976562    7.451085      7.451085    0.0     7.451085       0.0
685438  5354.984375    7.379612      7.379612    0.0     7.379612       0.0
685439  5354.992188    7.471506      7.471506    0.0     7.471506       0.0

        post_proc_pred_art
0                      0.0
1                      0.0
2                      0.0
3                      0.0
4                      0.0
...                    ...
685435                 0.0
685436                 0.0
685437                 0.0
685438                 0.0
685439                 0.0

[685440 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 01:46:24.500000 to 1970-01-01 01:46:25 for index 5569
calculating features from 102152 to 102159 for index 5569
processed hour 1 - start: 57600 | end: 102166
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.003610                0.005105
1970-01-01 01:00:00.500               0.000000                0.000000
1970-01-01 01:00:01.000               0.003610                0.005105
1970-01-01 01:00:01.500               0.003610                0.010210
1970-01-01 01:00:02.000               0.003610                0.007658
...                                        ...                     ...
1970-01-01 01:46:23.000               0.007220                0.015316
1970-01-01 01:46:23.500               0.039709                0.099552
1970-01-01 01:46:24.000               0.050539                0.140394
1970-01-01 01:46:24.500               0.021660                0.040842
1970-01-01 01:46:25.000               0.014440                0.022974

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.012635
1970-01-01 01:00:00.500               0.007220
1970-01-01 01:00:01.000               0.012635
1970-01-01 01:00:01.500               0.028880
1970-01-01 01:00:02.000               0.018050
...                                        ...
1970-01-01 01:46:23.000               0.019855
1970-01-01 01:46:23.500               0.211182
1970-01-01 01:46:24.000               0.346555
1970-01-01 01:46:24.500               0.057759
1970-01-01 01:46:25.000               0.081224

[5571 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.003610                0.002553
1970-01-01 01:00:00.250               0.000000                0.005105
1970-01-01 01:00:00.500               0.000000                0.000000
1970-01-01 01:00:00.750               0.000000                0.000000
1970-01-01 01:00:01.000               0.003610                0.002553
...                                        ...                     ...
1970-01-01 01:46:24.250               0.043319                0.109762
1970-01-01 01:46:24.500               0.021660                0.040842
1970-01-01 01:46:24.750               0.003610                0.005105
1970-01-01 01:46:25.000               0.014440                0.022974
1970-01-01 01:46:25.250               0.014440                0.000000

[11142 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label  auto_signal  pred_art  \
0          0.000000    0.000000     -0.054672    0.0     0.000000       0.0
1          0.007812    0.000000     -0.054672    0.0     0.000000       0.0
2          0.015625    0.000000     -0.054672    0.0     0.000000       0.0
3          0.023438    0.000000     -0.054672    0.0     0.000000       0.0
4          0.031250    0.000000     -0.054672    0.0     0.000000       0.0
...             ...         ...           ...    ...          ...       ...
747553  5840.257812    5.169047      5.169047    0.0     5.169047       0.0
747554  5840.265625    5.230310      5.230310    0.0     5.230310       0.0
747555  5840.273438    5.199678      5.199678    0.0     5.199678       0.0
747556  5840.281250    5.169047      5.169047    0.0     5.169047       0.0
747557  5840.289062    5.169047      5.169047    0.0     5.169047       0.0

        post_proc_pred_art
0                      0.0
1                      0.0
2                      0.0
3                      0.0
4                      0.0
...                    ...
747553                 0.0
747554                 0.0
747555                 0.0
747556                 0.0
747557                 0.0

[747558 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 01:37:42.500000 to 1970-01-01 01:37:43 for index 4525
calculating features from 93800 to 93807 for index 4525
processed hour 1 - start: 57600 | end: 93815
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.002826                0.004884
1970-01-01 01:00:00.500               0.008163                0.012876
1970-01-01 01:00:01.000               0.025430                0.018426
1970-01-01 01:00:01.500               0.000628                0.000666
1970-01-01 01:00:02.000               0.001570                0.001776
...                                        ...                     ...
1970-01-01 01:37:41.000               0.013469                0.039560
1970-01-01 01:37:41.500               0.011397                0.008059
1970-01-01 01:37:42.000               0.007252                0.010989
1970-01-01 01:37:42.500               0.005180                0.013919
1970-01-01 01:37:43.000               0.015541                0.021978

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.003924
1970-01-01 01:00:00.500               0.020093
1970-01-01 01:00:01.000               0.018209
1970-01-01 01:00:01.500               0.000942
1970-01-01 01:00:02.000               0.006279
...                                        ...
1970-01-01 01:37:41.000               0.034190
1970-01-01 01:37:41.500               0.000518
1970-01-01 01:37:42.000               0.023829
1970-01-01 01:37:42.500               0.012433
1970-01-01 01:37:43.000               0.016577

[4527 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.002826                0.004884
1970-01-01 01:00:00.250               0.002512                0.000666
1970-01-01 01:00:00.500               0.008163                0.012876
1970-01-01 01:00:00.750               0.004395                0.002220
1970-01-01 01:00:01.000               0.025430                0.018426
...                                        ...                     ...
1970-01-01 01:37:42.250               0.006216                0.009524
1970-01-01 01:37:42.500               0.005180                0.013919
1970-01-01 01:37:42.750               0.004144                0.003663
1970-01-01 01:37:43.000               0.015541                0.021978
1970-01-01 01:37:43.250               0.010361                0.014652

[9054 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000    0.000000     -0.200463    0.0  2.106994e-20       1.0
1          0.007812    0.000000     -0.200463    0.0  1.879714e-06       1.0
2          0.015625    0.000000     -0.200463    0.0  3.656027e-06       1.0
3          0.023438    0.000000     -0.200463    0.0  5.370973e-06       1.0
4          0.031250    0.000000     -0.200463    0.0  7.062509e-06       1.0
...             ...         ...           ...    ...           ...       ...
794065  6203.632812    0.000222      0.000222    0.0  2.220002e-04       0.0
794066  6203.640625    0.000222      0.000222    0.0  2.220002e-04       0.0
794067  6203.648438    0.000222      0.000222    0.0  2.220002e-04       0.0
794068  6203.656250    0.000222      0.000222    0.0  2.220002e-04       0.0
794069  6203.664062    0.000222      0.000222    0.0  2.220002e-04       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
794065                 0.0
794066                 0.0
794067                 0.0
794068                 0.0
794069                 0.0

[794070 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 01:46:40 to 1970-01-01 01:46:40.500000 for index 5600
calculating features from 102400 to 102407 for index 5600
processed hour 1 - start: 57600 | end: 102410
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.005180                0.013187
1970-01-01 01:00:00.500               0.003108                0.002198
1970-01-01 01:00:01.000               0.003108                0.008059
1970-01-01 01:00:01.500               0.004144                0.008059
1970-01-01 01:00:02.000               0.003108                0.006593
...                                        ...                     ...
1970-01-01 01:46:38.500               0.000000                0.005105
1970-01-01 01:46:39.000               0.003610                0.007658
1970-01-01 01:46:39.500               0.003610                0.012763
1970-01-01 01:46:40.000               0.007220                0.020421
1970-01-01 01:46:40.500               0.003610                0.000000

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.026937
1970-01-01 01:00:00.500               0.001036
1970-01-01 01:00:01.000               0.019167
1970-01-01 01:00:01.500               0.024865
1970-01-01 01:00:02.000               0.017613
...                                        ...
1970-01-01 01:46:38.500               0.010830
1970-01-01 01:46:39.000               0.001805
1970-01-01 01:46:39.500               0.023465
1970-01-01 01:46:40.000               0.059564
1970-01-01 01:46:40.500               0.000000

[5602 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.005180                0.013187
1970-01-01 01:00:00.250               0.002072                0.005861
1970-01-01 01:00:00.500               0.003108                0.002198
1970-01-01 01:00:00.750               0.001036                0.000733
1970-01-01 01:00:01.000               0.002072                0.005861
...                                        ...                     ...
1970-01-01 01:46:39.750               0.003610                0.012763
1970-01-01 01:46:40.000               0.007220                0.012763
1970-01-01 01:46:40.250               0.007220                0.020421
1970-01-01 01:46:40.500               0.003610                0.000000
1970-01-01 01:46:40.750               0.000000                0.000000

[11204 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000    0.000000     -0.236911    0.0  2.106994e-20       1.0
1          0.007812    0.000000     -0.236911    0.0  1.879714e-06       1.0
2          0.015625    0.000000     -0.236911    0.0  3.656027e-06       1.0
3          0.023438    0.000000     -0.236911    0.0  5.370973e-06       1.0
4          0.031250    0.000000     -0.236911    0.0  7.062509e-06       1.0
...             ...         ...           ...    ...           ...       ...
871585  6809.257812    0.000222      0.000222    0.0  2.220002e-04       0.0
871586  6809.265625    0.000222      0.000222    0.0  2.220002e-04       0.0
871587  6809.273438    0.000222      0.000222    0.0  2.220002e-04       0.0
871588  6809.281250    0.000222      0.000222    0.0  2.220002e-04       0.0
871589  6809.289062    0.000222      0.000222    0.0  2.220002e-04       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
871585                 0.0
871586                 0.0
871587                 0.0
871588                 0.0
871589                 0.0

[871590 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 01:45:24 to 1970-01-01 01:45:24.500000 for index 5448
calculating features from 101184 to 101191 for index 5448
processed hour 1 - start: 57600 | end: 101197
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.004144                0.003663
1970-01-01 01:00:00.500               0.002072                0.002198
1970-01-01 01:00:01.000               0.003108                0.004396
1970-01-01 01:00:01.500               0.001036                0.004396
1970-01-01 01:00:02.000               0.005180                0.002930
...                                        ...                     ...
1970-01-01 01:45:22.500               0.014440                0.005105
1970-01-01 01:45:23.000               0.010830                0.017868
1970-01-01 01:45:23.500               0.003610                0.022974
1970-01-01 01:45:24.000               0.014440                0.005105
1970-01-01 01:45:24.500               0.010361                0.029304

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.008288
1970-01-01 01:00:00.500               0.003626
1970-01-01 01:00:01.000               0.011915
1970-01-01 01:00:01.500               0.010361
1970-01-01 01:00:02.000               0.001554
...                                        ...
1970-01-01 01:45:22.500               0.014440
1970-01-01 01:45:23.000               0.009025
1970-01-01 01:45:23.500               0.019855
1970-01-01 01:45:24.000               0.026587
1970-01-01 01:45:24.500               0.024865

[5450 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.003108            3.663004e-03
1970-01-01 01:00:00.250               0.004144            2.197802e-03
1970-01-01 01:00:00.500               0.002072            4.440892e-16
1970-01-01 01:00:00.750               0.002072            2.197802e-03
1970-01-01 01:00:01.000               0.002072            7.326007e-04
...                                        ...                     ...
1970-01-01 01:45:23.750               0.003610            2.297354e-02
1970-01-01 01:45:24.000               0.014440            5.105232e-03
1970-01-01 01:45:24.250               0.003108            1.465201e-03
1970-01-01 01:45:24.500               0.010361            2.930403e-02
1970-01-01 01:45:24.750               0.000000            0.000000e+00

[10900 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label   auto_signal  pred_art  \
0          0.000000     0.00000     -0.091119    0.0  3.577867e-18       1.0
1          0.007812     0.00000     -0.091119    0.0  3.224669e-05       1.0
2          0.015625     0.00000     -0.091119    0.0  6.430650e-05       1.0
3          0.023438     0.00000     -0.091119    0.0  9.618001e-05       1.0
4          0.031250     0.00000     -0.091119    0.0  1.278678e-04       1.0
...             ...         ...           ...    ...           ...       ...
758409  5925.070312     0.00999      0.009990    0.0  9.990010e-03       0.0
758410  5925.078125     0.00999      0.009990    0.0  9.990010e-03       0.0
758411  5925.085938     0.00999      0.009990    0.0  9.990010e-03       0.0
758412  5925.093750     0.00999      0.009990    0.0  9.990010e-03       0.0
758413  5925.101562     0.00999      0.009990    0.0  9.990010e-03       0.0

        post_proc_pred_art
0                      1.0
1                      1.0
2                      1.0
3                      1.0
4                      1.0
...                    ...
758409                 0.0
758410                 0.0
758411                 0.0
758412                 0.0
758413                 0.0

[758414 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 01:55:13 to 1970-01-01 01:55:13.500000 for index 6626
calculating features from 110608 to 110615 for index 6626
processed hour 1 - start: 57600 | end: 110621
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.002072                0.002198
1970-01-01 01:00:00.500               0.001036                0.002930
1970-01-01 01:00:01.000               0.003108                0.008059
1970-01-01 01:00:01.500               0.014505                0.057875
1970-01-01 01:00:02.000               0.081848                0.111355
...                                        ...                     ...
1970-01-01 01:55:11.500               0.006216                0.004396
1970-01-01 01:55:12.000               0.007252                0.014652
1970-01-01 01:55:12.500               0.005180                0.002198
1970-01-01 01:55:13.000               0.005180                0.010989
1970-01-01 01:55:13.500               0.001036                0.000733

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.010879
1970-01-01 01:00:00.500               0.004662
1970-01-01 01:00:01.000               0.021757
1970-01-01 01:00:01.500               0.089619
1970-01-01 01:00:02.000               0.109822
...                                        ...
1970-01-01 01:55:11.500               0.013987
1970-01-01 01:55:12.000               0.019685
1970-01-01 01:55:12.500               0.005698
1970-01-01 01:55:13.000               0.022793
1970-01-01 01:55:13.500               0.000518

[6628 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.000000                0.001465
1970-01-01 01:00:00.250               0.002072                0.002198
1970-01-01 01:00:00.500               0.001036                0.000733
1970-01-01 01:00:00.750               0.000000                0.002930
1970-01-01 01:00:01.000               0.001036                0.000733
...                                        ...                     ...
1970-01-01 01:55:12.750               0.005180                0.002198
1970-01-01 01:55:13.000               0.005180                0.010989
1970-01-01 01:55:13.250               0.003108                0.005128
1970-01-01 01:55:13.500               0.001036                0.000733
1970-01-01 01:55:13.750               0.000000                0.000000

[13256 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

               time  raw_signal  clean_signal  label  auto_signal  pred_art  \
0          0.000000    0.000000     -0.200463    0.0     0.000000       0.0
1          0.007812    0.000000     -0.200463    0.0     0.000000       0.0
2          0.015625    0.000000     -0.200463    0.0     0.000000       0.0
3          0.023438    0.000000     -0.200463    0.0     0.000000       0.0
4          0.031250    0.000000     -0.200463    0.0     0.000000       0.0
...             ...         ...           ...    ...          ...       ...
708691  5536.648438    4.462271      4.462271    0.0     4.462271       0.0
708692  5536.656250    4.462271      4.462271    0.0     4.462271       0.0
708693  5536.664062    4.462271      4.462271    0.0     4.462271       0.0
708694  5536.671875    4.462271      4.462271    0.0     4.462271       0.0
708695  5536.679688    4.462271      4.462271    0.0     4.462271       0.0

        post_proc_pred_art
0                      0.0
1                      0.0
2                      0.0
3                      0.0
4                      0.0
...                    ...
708691                 0.0
708692                 0.0
708693                 0.0
708694                 0.0
708695                 0.0

[708696 rows x 7 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:884: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eda_df_16hz['filtered_signal'] = butter_lowpass_filter(eda_df_16hz['raw_signal'], cutoff=1.0, samp_freq=16, order=6)
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 63 for index 0
calculating features from 1970-01-01 01:43:23 to 1970-01-01 01:43:23.500000 for index 5206
calculating features from 99248 to 99255 for index 5206
processed hour 1 - start: 57600 | end: 99259
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.001884                0.001998
1970-01-01 01:00:00.500               0.002198                0.001776
1970-01-01 01:00:01.000               0.003140                0.000666
1970-01-01 01:00:01.500               0.002512                0.000444
1970-01-01 01:00:02.000               0.001884                0.001998
...                                        ...                     ...
1970-01-01 01:43:21.500               0.003140                0.001998
1970-01-01 01:43:22.000               0.004709                0.069708
1970-01-01 01:43:22.500               0.000628                0.001776
1970-01-01 01:43:23.000               0.003140                0.002886
1970-01-01 01:43:23.500               0.000314                0.004662

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.000785
1970-01-01 01:00:00.500               0.000785
1970-01-01 01:00:01.000               0.001413
1970-01-01 01:00:01.500               0.000785
1970-01-01 01:00:02.000               0.000314
...                                        ...
1970-01-01 01:43:21.500               0.002355
1970-01-01 01:43:22.000               0.035477
1970-01-01 01:43:22.500               0.004395
1970-01-01 01:43:23.000               0.002041
1970-01-01 01:43:23.500               0.000000

[5208 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.000314                0.001998
1970-01-01 01:00:00.250               0.001884                0.001332
1970-01-01 01:00:00.500               0.002198                0.001554
1970-01-01 01:00:00.750               0.001570                0.001776
1970-01-01 01:00:01.000               0.001884                0.000666
...                                        ...                     ...
1970-01-01 01:43:22.750               0.000628                0.001332
1970-01-01 01:43:23.000               0.003140                0.000000
1970-01-01 01:43:23.250               0.001884                0.002886
1970-01-01 01:43:23.500               0.000314                0.004662
1970-01-01 01:43:23.750               0.000000                0.000000

[10416 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

calculating features from 1970-01-01 01:47:25 to 1970-01-01 01:47:25.500000 for index 5690
calculating features from 103120 to 103127 for index 5690
processed hour 1 - start: 57600 | end: 103135
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.007220                0.002553
1970-01-01 01:00:00.500               0.003610                0.002553
1970-01-01 01:00:01.000               0.003610                0.005105
1970-01-01 01:00:01.500               0.007220                0.007658
1970-01-01 01:00:02.000               0.003610                0.007658
...                                        ...                     ...
1970-01-01 01:47:23.500               0.010830                0.017868
1970-01-01 01:47:24.000               0.010830                0.012763
1970-01-01 01:47:24.500               0.036099                0.025526
1970-01-01 01:47:25.000               0.234646                0.546260
1970-01-01 01:47:25.500               0.000314                3.747473

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.005415
1970-01-01 01:00:00.500               0.019855
1970-01-01 01:00:01.000               0.016245
1970-01-01 01:00:01.500               0.014440
1970-01-01 01:00:02.000               0.010830
...                                        ...
1970-01-01 01:47:23.500               0.037904
1970-01-01 01:47:24.000               0.050539
1970-01-01 01:47:24.500               0.034294
1970-01-01 01:47:25.000               1.191281
1970-01-01 01:47:25.500               2.652359

[5692 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.007220            8.881784e-16
1970-01-01 01:00:00.250               0.003610            2.552616e-03
1970-01-01 01:00:00.500               0.003610            0.000000e+00
1970-01-01 01:00:00.750               0.003610            2.552616e-03
1970-01-01 01:00:01.000               0.000000            5.105232e-03
...                                        ...                     ...
1970-01-01 01:47:24.750               0.036099            2.552616e-02
1970-01-01 01:47:25.000               0.093859            1.633674e-01
1970-01-01 01:47:25.250               0.234646            5.462598e-01
1970-01-01 01:47:25.500               0.000173            3.747473e+00
1970-01-01 01:47:25.750               0.000314            6.660007e-04

[11384 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

calculating features from 1970-01-01 01:42:22.500000 to 1970-01-01 01:42:23 for index 5085
calculating features from 98280 to 98287 for index 5085
processed hour 1 - start: 57600 | end: 98290
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000                0.02888                0.028079
1970-01-01 01:00:00.500                0.01805                0.010210
1970-01-01 01:00:01.000                0.01444                0.015316
1970-01-01 01:00:01.500                0.00361                0.005105
1970-01-01 01:00:02.000                0.02166                0.022974
...                                        ...                     ...
1970-01-01 01:42:21.000                0.01805                0.020421
1970-01-01 01:42:21.500                0.00361                0.005105
1970-01-01 01:42:22.000                0.01444                0.007658
1970-01-01 01:42:22.500                0.00361                0.010210
1970-01-01 01:42:23.000                0.00361                0.000000

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.048734
1970-01-01 01:00:00.500               0.010830
1970-01-01 01:00:01.000               0.012635
1970-01-01 01:00:01.500               0.005415
1970-01-01 01:00:02.000               0.009025
...                                        ...
1970-01-01 01:42:21.000               0.009025
1970-01-01 01:42:21.500               0.014440
1970-01-01 01:42:22.000               0.027075
1970-01-01 01:42:22.500               0.016245
1970-01-01 01:42:23.000               0.000000

[5087 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000                0.00000                0.000000
1970-01-01 01:00:00.250                0.02888                0.028079
1970-01-01 01:00:00.500                0.01805                0.010210
1970-01-01 01:00:00.750                0.00000                0.000000
1970-01-01 01:00:01.000                0.01444                0.015316
...                                        ...                     ...
1970-01-01 01:42:22.250                0.00722                0.005105
1970-01-01 01:42:22.500                0.00361                0.007658
1970-01-01 01:42:22.750                0.00000                0.010210
1970-01-01 01:42:23.000                0.00361                0.000000
1970-01-01 01:42:23.250                0.00000                0.000000

[10174 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
1970-01-01 00:00:00.187500                0.000000                 0.000222
1970-01-01 00:00:00.250000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.006216                 0.008791
1970-01-01 00:59:59.750000                0.005180                 0.006593
1970-01-01 00:59:59.812500                0.005180                 0.004396
1970-01-01 00:59:59.875000                0.005180                 0.004396
1970-01-01 00:59:59.937500                0.007252                 0.006593

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000157
1970-01-01 00:00:00.250000                0.000000
...                                            ...
1970-01-01 00:59:59.687500                0.003108
1970-01-01 00:59:59.750000                0.001036
1970-01-01 00:59:59.812500                0.001554
1970-01-01 00:59:59.875000                0.003108
1970-01-01 00:59:59.937500                0.005180

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.005180                 0.004396
1970-01-01 00:59:59.875000                0.004144                 0.001465
1970-01-01 00:59:59.906250                0.005180                 0.004396
1970-01-01 00:59:59.937500                0.007252                 0.002198
1970-01-01 00:59:59.968750                0.004144                 0.006593

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
1970-01-01 00:00:00.187500                0.000000                 0.000222
1970-01-01 00:00:00.250000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.021660                 0.020421
1970-01-01 00:59:59.750000                0.050539                 0.025526
1970-01-01 00:59:59.812500                0.068589                 0.010210
1970-01-01 00:59:59.875000                0.039709                 0.030631
1970-01-01 00:59:59.937500                0.021660                 0.020421

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000157
1970-01-01 00:00:00.250000                0.000000
...                                            ...
1970-01-01 00:59:59.687500                0.007220
1970-01-01 00:59:59.750000                0.012635
1970-01-01 00:59:59.812500                0.009025
1970-01-01 00:59:59.875000                0.012635
1970-01-01 00:59:59.937500                0.014440

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.014440                 0.002553
1970-01-01 00:59:59.875000                0.028880                 0.012763
1970-01-01 00:59:59.906250                0.039709                 0.030631
1970-01-01 00:59:59.937500                0.014440                 0.000000
1970-01-01 00:59:59.968750                0.021660                 0.020421

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
1970-01-01 00:00:00.187500                0.000000                 0.000222
1970-01-01 00:00:00.250000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.043319                 0.025526
1970-01-01 00:59:59.750000                0.025270                 0.048500
1970-01-01 00:59:59.812500                0.025270                 0.030631
1970-01-01 00:59:59.875000                0.039709                 0.053605
1970-01-01 00:59:59.937500                0.039709                 0.028079

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000157
1970-01-01 00:00:00.250000                0.000000
...                                            ...
1970-01-01 00:59:59.687500                0.005415
1970-01-01 00:59:59.750000                0.016245
1970-01-01 00:59:59.812500                0.001805
1970-01-01 00:59:59.875000                0.016245
1970-01-01 00:59:59.937500                0.007220

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.025270                 0.030631
1970-01-01 00:59:59.875000                0.039709                 0.020421
1970-01-01 00:59:59.906250                0.007220                 0.053605
1970-01-01 00:59:59.937500                0.025270                 0.028079
1970-01-01 00:59:59.968750                0.039709                 0.012763

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
1970-01-01 00:00:00.187500                0.000000                 0.000222
1970-01-01 00:00:00.250000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.002072                 0.004396
1970-01-01 00:59:59.750000                0.008288                 0.010256
1970-01-01 00:59:59.812500                0.007252                 0.009524
1970-01-01 00:59:59.875000                0.003108                 0.005128
1970-01-01 00:59:59.937500                0.012433                 0.003663

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000157
1970-01-01 00:00:00.250000                0.000000
...                                            ...
1970-01-01 00:59:59.687500                0.000000
1970-01-01 00:59:59.750000                0.000518
1970-01-01 00:59:59.812500                0.009324
1970-01-01 00:59:59.875000                0.000518
1970-01-01 00:59:59.937500                0.004662

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.007252                 0.009524
1970-01-01 00:59:59.875000                0.003108                 0.005128
1970-01-01 00:59:59.906250                0.003108                 0.004396
1970-01-01 00:59:59.937500                0.012433                 0.003663
1970-01-01 00:59:59.968750                0.004144                 0.002930

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
1970-01-01 00:00:00.187500                0.000000                 0.000222
1970-01-01 00:00:00.250000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.050539                 0.030631
1970-01-01 00:59:59.750000                0.050539                 0.033184
1970-01-01 00:59:59.812500                0.057759                 0.017868
1970-01-01 00:59:59.875000                0.050539                 0.028079
1970-01-01 00:59:59.937500                0.061369                 0.025526

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000157
1970-01-01 00:00:00.250000                0.000000
...                                            ...
1970-01-01 00:59:59.687500                0.003610
1970-01-01 00:59:59.750000                0.007220
1970-01-01 00:59:59.812500                0.009025
1970-01-01 00:59:59.875000                0.001805
1970-01-01 00:59:59.937500                0.010830

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.057759                 0.017868
1970-01-01 00:59:59.875000                0.046929                 0.028079
1970-01-01 00:59:59.906250                0.050539                 0.025526
1970-01-01 00:59:59.937500                0.061369                 0.020421
1970-01-01 00:59:59.968750                0.061369                 0.025526

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                 0.00000                 0.000000
1970-01-01 00:00:00.062500                 0.00000                 0.000000
1970-01-01 00:00:00.125000                 0.00000                 0.000000
1970-01-01 00:00:00.187500                 0.00000                 0.000222
1970-01-01 00:00:00.250000                 0.00000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                 0.01444                 0.007658
1970-01-01 00:59:59.750000                 0.01444                 0.012763
1970-01-01 00:59:59.812500                 0.01444                 0.007658
1970-01-01 00:59:59.875000                 0.01805                 0.010210
1970-01-01 00:59:59.937500                 0.01805                 0.007658

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000157
1970-01-01 00:00:00.250000                0.000000
...                                            ...
1970-01-01 00:59:59.687500                0.000000
1970-01-01 00:59:59.750000                0.007220
1970-01-01 00:59:59.812500                0.001805
1970-01-01 00:59:59.875000                0.001805
1970-01-01 00:59:59.937500                0.005415

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                 0.00000                 0.000000
1970-01-01 00:00:00.031250                 0.00000                 0.000000
1970-01-01 00:00:00.062500                 0.00000                 0.000000
1970-01-01 00:00:00.093750                 0.00000                 0.000000
1970-01-01 00:00:00.125000                 0.00000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                 0.01444                 0.007658
1970-01-01 00:59:59.875000                 0.01805                 0.007658
1970-01-01 00:59:59.906250                 0.01444                 0.010210
1970-01-01 00:59:59.937500                 0.01805                 0.000000
1970-01-01 00:59:59.968750                 0.01805                 0.007658

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.006734                 0.004762
1970-01-01 00:00:00.187500                0.000628                 0.004018
1970-01-01 00:00:00.250000                0.000628                 0.001554
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.000314                 0.000222
1970-01-01 00:59:59.750000                0.000000                 0.000000
1970-01-01 00:59:59.812500                0.000628                 0.000444
1970-01-01 00:59:59.875000                0.000000                 0.000444
1970-01-01 00:59:59.937500                0.000628                 0.000666

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.010102
1970-01-01 00:00:00.187500                0.002841
1970-01-01 00:00:00.250000                0.001884
...                                            ...
1970-01-01 00:59:59.687500                0.000157
1970-01-01 00:59:59.750000                0.000000
1970-01-01 00:59:59.812500                0.001256
1970-01-01 00:59:59.875000                0.000628
1970-01-01 00:59:59.937500                0.000785

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.006734                 0.004762
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.000314                 0.000000
1970-01-01 00:59:59.875000                0.000000                 0.000444
1970-01-01 00:59:59.906250                0.000000                 0.000444
1970-01-01 00:59:59.937500                0.000000                 0.000000
1970-01-01 00:59:59.968750                0.000628                 0.000666

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
1970-01-01 00:00:00.187500                0.000000                 0.000222
1970-01-01 00:00:00.250000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.005180                 0.005128
1970-01-01 00:59:59.750000                0.009324                 0.010989
1970-01-01 00:59:59.812500                0.009324                 0.003663
1970-01-01 00:59:59.875000                0.008288                 0.010256
1970-01-01 00:59:59.937500                0.008288                 0.002930

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000157
1970-01-01 00:00:00.250000                0.000000
...                                            ...
1970-01-01 00:59:59.687500                0.003626
1970-01-01 00:59:59.750000                0.006734
1970-01-01 00:59:59.812500                0.002590
1970-01-01 00:59:59.875000                0.003626
1970-01-01 00:59:59.937500                0.001554

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.006216                 0.003663
1970-01-01 00:59:59.875000                0.008288                 0.002198
1970-01-01 00:59:59.906250                0.008288                 0.010256
1970-01-01 00:59:59.937500                0.007252                 0.000733
1970-01-01 00:59:59.968750                0.008288                 0.002930

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 460672 to 460735 for index 7198
processed hour 0 - start: 0 | end: 460800
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
1970-01-01 00:00:00.187500                0.000628                 0.000666
1970-01-01 00:00:00.250000                0.001256                 0.001332
...                                            ...                      ...
1970-01-01 00:59:59.687500                0.014505                 0.001465
1970-01-01 00:59:59.750000                0.013469                 0.004396
1970-01-01 00:59:59.812500                0.013469                 0.005128
1970-01-01 00:59:59.875000                0.013469                 0.004396
1970-01-01 00:59:59.937500                0.014505                 0.003663

                            third_16thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000
1970-01-01 00:00:00.062500                0.000000
1970-01-01 00:00:00.125000                0.000000
1970-01-01 00:00:00.187500                0.000471
1970-01-01 00:00:00.250000                0.000942
...                                            ...
1970-01-01 00:59:59.687500                0.000518
1970-01-01 00:59:59.750000                0.001554
1970-01-01 00:59:59.812500                0.002590
1970-01-01 00:59:59.875000                0.001554
1970-01-01 00:59:59.937500                0.004662

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 00:00:00.000000                0.000000                 0.000000
1970-01-01 00:00:00.031250                0.000000                 0.000000
1970-01-01 00:00:00.062500                0.000000                 0.000000
1970-01-01 00:00:00.093750                0.000000                 0.000000
1970-01-01 00:00:00.125000                0.000000                 0.000000
...                                            ...                      ...
1970-01-01 00:59:59.843750                0.013469                 0.005128
1970-01-01 00:59:59.875000                0.008288                 0.004396
1970-01-01 00:59:59.906250                0.013469                 0.000733
1970-01-01 00:59:59.937500                0.014505                 0.002930
1970-01-01 00:59:59.968750                0.014505                 0.003663

[115200 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 460800 to 460863 for index 0
calculating features from 1970-01-01 01:38:20 to 1970-01-01 01:38:20.500000 for index 4600
calculating features from 755200 to 755263 for index 4600
processed hour 1 - start: 460800 | end: 755310
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.005180                 0.004396
1970-01-01 01:00:00.062500                0.007252                 0.003663
1970-01-01 01:00:00.125000                0.005180                 0.002198
1970-01-01 01:00:00.187500                0.004144                 0.002198
1970-01-01 01:00:00.250000                0.006216                 0.008059
...                                            ...                      ...
1970-01-01 01:38:20.562500                0.001570                 0.001110
1970-01-01 01:38:20.625000                0.002198                 0.001554
1970-01-01 01:38:20.687500                0.000000                 0.000000
1970-01-01 01:38:20.750000                0.002198                 0.001554
1970-01-01 01:38:20.812500                0.004081                 0.001332

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.003108
1970-01-01 01:00:00.062500                0.000000
1970-01-01 01:00:00.125000                0.001036
1970-01-01 01:00:00.187500                0.003108
1970-01-01 01:00:00.250000                0.003108
...                                            ...
1970-01-01 01:38:20.562500                0.000785
1970-01-01 01:38:20.625000                0.001099
1970-01-01 01:38:20.687500                0.000000
1970-01-01 01:38:20.750000                0.000314
1970-01-01 01:38:20.812500                0.003140

[36814 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.005180                 0.004396
1970-01-01 01:00:00.031250                0.002072                 0.001465
1970-01-01 01:00:00.062500                0.004144                 0.003663
1970-01-01 01:00:00.093750                0.007252                 0.002198
1970-01-01 01:00:00.125000                0.005180                 0.002198
...                                            ...                      ...
1970-01-01 01:38:20.718750                0.000000                 0.000000
1970-01-01 01:38:20.750000                0.002198                 0.001554
1970-01-01 01:38:20.781250                0.001570                 0.001110
1970-01-01 01:38:20.812500                0.004081                 0.001332
1970-01-01 01:38:20.843750                0.000000                 0.000000

[73628 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:29:14 to 1970-01-01 01:29:14.500000 for index 3508
calculating features from 685312 to 685375 for index 3508
processed hour 1 - start: 460800 | end: 685440
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.025270                 0.017868
1970-01-01 01:00:00.062500                0.043319                 0.017868
1970-01-01 01:00:00.125000                0.043319                 0.020421
1970-01-01 01:00:00.187500                0.032489                 0.028079
1970-01-01 01:00:00.250000                0.039709                 0.030631
...                                            ...                      ...
1970-01-01 01:29:14.687500                0.075809                 0.010210
1970-01-01 01:29:14.750000                0.068589                 0.025526
1970-01-01 01:29:14.812500                0.061369                 0.058710
1970-01-01 01:29:14.875000                0.043319                 0.033184
1970-01-01 01:29:14.937500                0.072199                 0.022974

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.023465
1970-01-01 01:00:00.062500                0.028880
1970-01-01 01:00:00.125000                0.007220
1970-01-01 01:00:00.187500                0.009025
1970-01-01 01:00:00.250000                0.019855
...                                            ...
1970-01-01 01:29:14.687500                0.023465
1970-01-01 01:29:14.750000                0.025270
1970-01-01 01:29:14.812500                0.102883
1970-01-01 01:29:14.875000                0.054149
1970-01-01 01:29:14.937500                0.043319

[28080 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.025270                 0.017868
1970-01-01 01:00:00.031250                0.025270                 0.010210
1970-01-01 01:00:00.062500                0.043319                 0.017868
1970-01-01 01:00:00.093750                0.028880                 0.002553
1970-01-01 01:00:00.125000                0.010830                 0.020421
...                                            ...                      ...
1970-01-01 01:29:14.843750                0.032489                 0.058710
1970-01-01 01:29:14.875000                0.028880                 0.028079
1970-01-01 01:29:14.906250                0.043319                 0.033184
1970-01-01 01:29:14.937500                0.072199                 0.022974
1970-01-01 01:29:14.968750                0.064979                 0.012763

[56160 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:42:22.500000 to 1970-01-01 01:42:23 for index 5085
calculating features from 786240 to 786303 for index 5085
processed hour 1 - start: 460800 | end: 786318
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.015541                 0.008791
1970-01-01 01:00:00.062500                0.004144                 0.004396
1970-01-01 01:00:00.125000                0.007252                 0.008059
1970-01-01 01:00:00.187500                0.007252                 0.002198
1970-01-01 01:00:00.250000                0.004144                 0.003663
...                                            ...                      ...
1970-01-01 01:42:22.812500                0.014440                 0.002553
1970-01-01 01:42:22.875000                0.021660                 0.005105
1970-01-01 01:42:22.937500                0.021660                 0.005105
1970-01-01 01:42:23.000000                0.014440                 0.010210
1970-01-01 01:42:23.062500                0.014440                 0.002553

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.006216
1970-01-01 01:00:00.062500                0.001036
1970-01-01 01:00:00.125000                0.000518
1970-01-01 01:00:00.187500                0.000518
1970-01-01 01:00:00.250000                0.006734
...                                            ...
1970-01-01 01:42:22.812500                0.000000
1970-01-01 01:42:22.875000                0.001805
1970-01-01 01:42:22.937500                0.001805
1970-01-01 01:42:23.000000                0.003610
1970-01-01 01:42:23.062500                0.012635

[40690 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.002072                 0.004396
1970-01-01 01:00:00.031250                0.015541                 0.008791
1970-01-01 01:00:00.062500                0.003108                 0.004396
1970-01-01 01:00:00.093750                0.004144                 0.004396
1970-01-01 01:00:00.125000                0.007252                 0.008059
...                                            ...                      ...
1970-01-01 01:42:22.968750                0.018050                 0.005105
1970-01-01 01:42:23.000000                0.014440                 0.010210
1970-01-01 01:42:23.031250                0.010830                 0.010210
1970-01-01 01:42:23.062500                0.014440                 0.002553
1970-01-01 01:42:23.093750                0.003610                 0.000000

[81380 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:37:19.500000 to 1970-01-01 01:37:20 for index 4479
calculating features from 747456 to 747519 for index 4479
processed hour 1 - start: 460800 | end: 747558
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.057759                 0.030631
1970-01-01 01:00:00.062500                0.061369                 0.030631
1970-01-01 01:00:00.125000                0.064979                 0.022974
1970-01-01 01:00:00.187500                0.061369                 0.028079
1970-01-01 01:00:00.250000                0.064979                 0.038289
...                                            ...                      ...
1970-01-01 01:37:20.000000                0.036099                 0.015316
1970-01-01 01:37:20.062500                0.032489                 0.020421
1970-01-01 01:37:20.125000                0.036099                 0.017868
1970-01-01 01:37:20.187500                0.028880                 0.012763
1970-01-01 01:37:20.250000                0.021660                 0.045947

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.007220
1970-01-01 01:00:00.062500                0.014440
1970-01-01 01:00:00.125000                0.010830
1970-01-01 01:00:00.187500                0.007220
1970-01-01 01:00:00.250000                0.001805
...                                            ...
1970-01-01 01:37:20.000000                0.010830
1970-01-01 01:37:20.062500                0.016245
1970-01-01 01:37:20.125000                0.007220
1970-01-01 01:37:20.187500                0.003610
1970-01-01 01:37:20.250000                0.032489

[35845 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.057759                 0.030631
1970-01-01 01:00:00.031250                0.036099                 0.000000
1970-01-01 01:00:00.062500                0.039709                 0.010210
1970-01-01 01:00:00.093750                0.061369                 0.030631
1970-01-01 01:00:00.125000                0.064979                 0.017868
...                                            ...                      ...
1970-01-01 01:37:20.156250                0.021660                 0.017868
1970-01-01 01:37:20.187500                0.003610                 0.002553
1970-01-01 01:37:20.218750                0.028880                 0.012763
1970-01-01 01:37:20.250000                0.021660                 0.045947
1970-01-01 01:37:20.281250                0.000000                 0.000000

[71690 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:59:59 to 1970-01-01 01:59:59.500000 for index 7198
calculating features from 921472 to 921535 for index 7198
processed hour 1 - start: 460800 | end: 921600
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.021660                 0.012763
1970-01-01 01:00:00.062500                0.014440                 0.012763
1970-01-01 01:00:00.125000                0.050539                 0.002553
1970-01-01 01:00:00.187500                0.021660                 0.015316
1970-01-01 01:00:00.250000                0.061369                 0.002553
...                                            ...                      ...
1970-01-01 01:59:59.687500                0.000000                 0.000000
1970-01-01 01:59:59.750000                0.000000                 0.000000
1970-01-01 01:59:59.812500                0.000000                 0.000000
1970-01-01 01:59:59.875000                0.000000                 0.000000
1970-01-01 01:59:59.937500                0.000000                 0.000000

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.019855
1970-01-01 01:00:00.062500                0.007220
1970-01-01 01:00:00.125000                0.001805
1970-01-01 01:00:00.187500                0.018050
1970-01-01 01:00:00.250000                0.027075
...                                            ...
1970-01-01 01:59:59.687500                0.000000
1970-01-01 01:59:59.750000                0.000000
1970-01-01 01:59:59.812500                0.000000
1970-01-01 01:59:59.875000                0.000000
1970-01-01 01:59:59.937500                0.000000

[57600 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.021660                 0.012763
1970-01-01 01:00:00.031250                0.018050                 0.005105
1970-01-01 01:00:00.062500                0.014440                 0.012763
1970-01-01 01:00:00.093750                0.003610                 0.002553
1970-01-01 01:00:00.125000                0.050539                 0.002553
...                                            ...                      ...
1970-01-01 01:59:59.843750                0.000000                 0.000000
1970-01-01 01:59:59.875000                0.000000                 0.000000
1970-01-01 01:59:59.906250                0.000000                 0.000000
1970-01-01 01:59:59.937500                0.000000                 0.000000
1970-01-01 01:59:59.968750                0.000000                 0.000000

[115200 rows x 2 columns]
calculating features from 1970-01-01 02:00:00 to 1970-01-01 02:00:00.500000 for index 0
calculating features from 921600 to 921663 for index 0

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 02:00:31.500000 to 1970-01-01 02:00:32 for index 63
calculating features from 925632 to 925695 for index 63
processed hour 2 - start: 921600 | end: 925752
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 02:00:00.000000                     0.0                      0.0
1970-01-01 02:00:00.062500                     0.0                      0.0
1970-01-01 02:00:00.125000                     0.0                      0.0
1970-01-01 02:00:00.187500                     0.0                      0.0
1970-01-01 02:00:00.250000                     0.0                      0.0
...                                            ...                      ...
1970-01-01 02:00:32.125000                     0.0                      0.0
1970-01-01 02:00:32.187500                     0.0                      0.0
1970-01-01 02:00:32.250000                     0.0                      0.0
1970-01-01 02:00:32.312500                     0.0                      0.0
1970-01-01 02:00:32.375000                     0.0                      0.0

                            third_16thofa_sec_feat
1970-01-01 02:00:00.000000                     0.0
1970-01-01 02:00:00.062500                     0.0
1970-01-01 02:00:00.125000                     0.0
1970-01-01 02:00:00.187500                     0.0
1970-01-01 02:00:00.250000                     0.0
...                                            ...
1970-01-01 02:00:32.125000                     0.0
1970-01-01 02:00:32.187500                     0.0
1970-01-01 02:00:32.250000                     0.0
1970-01-01 02:00:32.312500                     0.0
1970-01-01 02:00:32.375000                     0.0

[519 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 02:00:00.000000                     0.0                      0.0
1970-01-01 02:00:00.031250                     0.0                      0.0
1970-01-01 02:00:00.062500                     0.0                      0.0
1970-01-01 02:00:00.093750                     0.0                      0.0
1970-01-01 02:00:00.125000                     0.0                      0.0
...                                            ...                      ...
1970-01-01 02:00:32.281250                     0.0                      0.0
1970-01-01 02:00:32.312500                     0.0                      0.0
1970-01-01 02:00:32.343750                     0.0                      0.0
1970-01-01 02:00:32.375000                     0.0                      0.0
1970-01-01 02:00:32.406250                     0.0                      0.0

[1038 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:32:16 to 1970-01-01 01:32:16.500000 for index 3872
calculating features from 708608 to 708671 for index 3872
processed hour 1 - start: 460800 | end: 708696
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.012433                 0.004396
1970-01-01 01:00:00.062500                0.014505                 0.014652
1970-01-01 01:00:00.125000                0.013469                 0.000733
1970-01-01 01:00:00.187500                0.015541                 0.003663
1970-01-01 01:00:00.250000                0.010361                 0.003663
...                                            ...                      ...
1970-01-01 01:32:16.375000                0.004144                 0.783395
1970-01-01 01:32:16.437500                0.008288                 0.021245
1970-01-01 01:32:16.500000                0.047658                 0.045421
1970-01-01 01:32:16.562500                0.368835                 0.487179
1970-01-01 01:32:16.625000                0.069416                 0.150183

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.000518
1970-01-01 01:00:00.062500                0.002590
1970-01-01 01:00:00.125000                0.003626
1970-01-01 01:00:00.187500                0.002590
1970-01-01 01:00:00.250000                0.003626
...                                            ...
1970-01-01 01:32:16.375000                0.553944
1970-01-01 01:32:16.437500                0.020721
1970-01-01 01:32:16.500000                0.041442
1970-01-01 01:32:16.562500                0.354848
1970-01-01 01:32:16.625000                0.106196

[30987 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.007252                 0.004396
1970-01-01 01:00:00.031250                0.012433                 0.002198
1970-01-01 01:00:00.062500                0.014505                 0.000733
1970-01-01 01:00:00.093750                0.013469                 0.014652
1970-01-01 01:00:00.125000                0.007252                 0.000733
...                                            ...                      ...
1970-01-01 01:32:16.531250                0.047658                 0.045421
1970-01-01 01:32:16.562500                0.368835                 0.487179
1970-01-01 01:32:16.593750                0.007252                 0.008791
1970-01-01 01:32:16.625000                0.069416                 0.150183
1970-01-01 01:32:16.656250                0.000000                 0.000000

[61974 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:38:44.500000 to 1970-01-01 01:38:45 for index 4649
calculating features from 758336 to 758399 for index 4649
processed hour 1 - start: 460800 | end: 758414
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.000314                 0.000000
1970-01-01 01:00:00.062500                0.000314                 0.000888
1970-01-01 01:00:00.125000                0.000314                 0.000222
1970-01-01 01:00:00.187500                0.000314                 0.000222
1970-01-01 01:00:00.250000                0.000314                 0.000222
...                                            ...                      ...
1970-01-01 01:38:44.812500                0.000000                 0.000000
1970-01-01 01:38:44.875000                0.000314                 0.000222
1970-01-01 01:38:44.937500                0.000000                 0.000000
1970-01-01 01:38:45.000000                0.000314                 0.000222
1970-01-01 01:38:45.062500                0.000000                 0.000000

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.000942
1970-01-01 01:00:00.062500                0.001099
1970-01-01 01:00:00.125000                0.000628
1970-01-01 01:00:00.187500                0.000628
1970-01-01 01:00:00.250000                0.000471
...                                            ...
1970-01-01 01:38:44.812500                0.000000
1970-01-01 01:38:44.875000                0.000000
1970-01-01 01:38:44.937500                0.000000
1970-01-01 01:38:45.000000                0.000157
1970-01-01 01:38:45.062500                0.000000

[37202 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.000314                 0.000000
1970-01-01 01:00:00.031250                0.000000                 0.000000
1970-01-01 01:00:00.062500                0.000314                 0.000222
1970-01-01 01:00:00.093750                0.000314                 0.000888
1970-01-01 01:00:00.125000                0.000314                 0.000222
...                                            ...                      ...
1970-01-01 01:38:44.968750                0.000000                 0.000000
1970-01-01 01:38:45.000000                0.000314                 0.000222
1970-01-01 01:38:45.031250                0.000000                 0.000000
1970-01-01 01:38:45.062500                0.000000                 0.000000
1970-01-01 01:38:45.093750                0.000000                 0.000000

[74404 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:43:23 to 1970-01-01 01:43:23.500000 for index 5206
calculating features from 793984 to 794047 for index 5206
processed hour 1 - start: 460800 | end: 794070
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                 0.01805                 0.015316
1970-01-01 01:00:00.062500                 0.01444                 0.010210
1970-01-01 01:00:00.125000                 0.01444                 0.017868
1970-01-01 01:00:00.187500                 0.01444                 0.015316
1970-01-01 01:00:00.250000                 0.01444                 0.015316
...                                            ...                      ...
1970-01-01 01:43:23.375000                 0.00000                 0.000000
1970-01-01 01:43:23.437500                 0.00000                 0.000000
1970-01-01 01:43:23.500000                 0.00000                 0.000000
1970-01-01 01:43:23.562500                 0.00000                 0.000000
1970-01-01 01:43:23.625000                 0.00000                 0.000000

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.009025
1970-01-01 01:00:00.062500                0.003610
1970-01-01 01:00:00.125000                0.001805
1970-01-01 01:00:00.187500                0.005415
1970-01-01 01:00:00.250000                0.001805
...                                            ...
1970-01-01 01:43:23.375000                0.000000
1970-01-01 01:43:23.437500                0.000000
1970-01-01 01:43:23.500000                0.000000
1970-01-01 01:43:23.562500                0.000000
1970-01-01 01:43:23.625000                0.000000

[41659 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                 0.01083                 0.015316
1970-01-01 01:00:00.031250                 0.01805                 0.012763
1970-01-01 01:00:00.062500                 0.01444                 0.000000
1970-01-01 01:00:00.093750                 0.01083                 0.010210
1970-01-01 01:00:00.125000                 0.00722                 0.017868
...                                            ...                      ...
1970-01-01 01:43:23.531250                 0.00000                 0.000000
1970-01-01 01:43:23.562500                 0.00000                 0.000000
1970-01-01 01:43:23.593750                 0.00000                 0.000000
1970-01-01 01:43:23.625000                 0.00000                 0.000000
1970-01-01 01:43:23.656250                 0.00000                 0.000000

[83318 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 01:53:28.500000 to 1970-01-01 01:53:29 for index 6417
calculating features from 871488 to 871551 for index 6417
processed hour 1 - start: 460800 | end: 871590
whole wave:
                            first_16thofa_sec_feat  second_16thofa_sec_feat  \
1970-01-01 01:00:00.000000                0.009324                 0.000733
1970-01-01 01:00:00.062500                0.009324                 0.002198
1970-01-01 01:00:00.125000                0.007252                 0.002198
1970-01-01 01:00:00.187500                0.009324                 0.000733
1970-01-01 01:00:00.250000                0.006216                 0.002930
...                                            ...                      ...
1970-01-01 01:53:29.000000                0.000000                 0.000000
1970-01-01 01:53:29.062500                0.000942                 0.000666
1970-01-01 01:53:29.125000                0.002512                 0.000888
1970-01-01 01:53:29.187500                0.005023                 0.008658
1970-01-01 01:53:29.250000                0.000000                 0.000000

                            third_16thofa_sec_feat
1970-01-01 01:00:00.000000                0.002072
1970-01-01 01:00:00.062500                0.000518
1970-01-01 01:00:00.125000                0.001554
1970-01-01 01:00:00.187500                0.000518
1970-01-01 01:00:00.250000                0.004144
...                                            ...
1970-01-01 01:53:29.000000                0.000000
1970-01-01 01:53:29.062500                0.000471
1970-01-01 01:53:29.125000                0.019465
1970-01-01 01:53:29.187500                0.009105
1970-01-01 01:53:29.250000                0.000000

[51349 rows x 3 columns]
half wave:
                            first_32thofa_sec_feat  second_32thofa_sec_feat
1970-01-01 01:00:00.000000                0.005180                 0.000733
1970-01-01 01:00:00.031250                0.009324                 0.000733
1970-01-01 01:00:00.062500                0.007252                 0.002198
1970-01-01 01:00:00.093750                0.009324                 0.001465
1970-01-01 01:00:00.125000                0.007252                 0.001465
...                                            ...                      ...
1970-01-01 01:53:29.156250                0.002512                 0.000888
1970-01-01 01:53:29.187500                0.001256                 0.000666
1970-01-01 01:53:29.218750                0.005023                 0.008658
1970-01-01 01:53:29.250000                0.000000                 0.000000
1970-01-01 01:53:29.281250                0.000000                 0.000000

[102698 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:00:00 to 1970-01-01 00:00:00.500000 for index 0
calculating features from 0 to 7 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
1970-01-01 00:00:01.500               0.000000                0.000000
1970-01-01 00:00:02.000               0.000314                0.000222
...                                        ...                     ...
1970-01-01 00:59:57.500               0.008288                0.006593
1970-01-01 00:59:58.000               0.002072                0.000733
1970-01-01 00:59:58.500               0.001036                0.003663
1970-01-01 00:59:59.000               0.002072                0.002930
1970-01-01 00:59:59.500               0.003108                0.002198

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.000314
1970-01-01 00:00:00.500               0.000000
1970-01-01 00:00:01.000               0.000000
1970-01-01 00:00:01.500               0.000000
1970-01-01 00:00:02.000               0.000157
...                                        ...
1970-01-01 00:59:57.500               0.005698
1970-01-01 00:59:58.000               0.002072
1970-01-01 00:59:58.500               0.000518
1970-01-01 00:59:59.000               0.001036
1970-01-01 00:59:59.500               0.001036

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.250               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.000000                0.001465
1970-01-01 00:59:59.000               0.002072                0.002930
1970-01-01 00:59:59.250               0.000000                0.001465
1970-01-01 00:59:59.500               0.003108                0.002198
1970-01-01 00:59:59.750               0.003108                0.000733

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.000628                0.000444
1970-01-01 00:00:00.500               0.000628                0.000444
1970-01-01 00:00:01.000               0.000942                0.000666
1970-01-01 00:00:01.500               0.000000                0.000000
1970-01-01 00:00:02.000               0.000942                0.000666
...                                        ...                     ...
1970-01-01 00:59:57.500               0.018050                0.012763
1970-01-01 00:59:58.000               0.010830                0.030631
1970-01-01 00:59:58.500               0.007220                0.020421
1970-01-01 00:59:59.000               0.003610                0.005105
1970-01-01 00:59:59.500               0.021660                0.020421

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.000628
1970-01-01 00:00:00.500               0.000314
1970-01-01 00:00:01.000               0.000471
1970-01-01 00:00:01.500               0.000000
1970-01-01 00:00:02.000               0.000157
...                                        ...
1970-01-01 00:59:57.500               0.019855
1970-01-01 00:59:58.000               0.070394
1970-01-01 00:59:58.500               0.039709
1970-01-01 00:59:59.000               0.014440
1970-01-01 00:59:59.500               0.019855

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.250               0.000628                0.000444
1970-01-01 00:00:00.500               0.000628                0.000444
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000942                0.000666
...                                        ...                     ...
1970-01-01 00:59:58.750               0.007220                0.005105
1970-01-01 00:59:59.000               0.003610                0.005105
1970-01-01 00:59:59.250               0.003610                0.005105
1970-01-01 00:59:59.500               0.021660                0.007658
1970-01-01 00:59:59.750               0.007220                0.020421

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
1970-01-01 00:00:01.500               0.000000                0.000000
1970-01-01 00:00:02.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:57.500               0.005180                0.009524
1970-01-01 00:59:58.000               0.003108                0.005128
1970-01-01 00:59:58.500               0.009324                0.005861
1970-01-01 00:59:59.000               0.004144                0.002930
1970-01-01 00:59:59.500               0.005180                0.003663

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.000314
1970-01-01 00:00:00.500               0.000000
1970-01-01 00:00:01.000               0.000000
1970-01-01 00:00:01.500               0.000000
1970-01-01 00:00:02.000               0.000000
...                                        ...
1970-01-01 00:59:57.500               0.015023
1970-01-01 00:59:58.000               0.013987
1970-01-01 00:59:58.500               0.008806
1970-01-01 00:59:59.000               0.008806
1970-01-01 00:59:59.500               0.002072

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.250               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.009324                0.000733
1970-01-01 00:59:59.000               0.004144                0.002930
1970-01-01 00:59:59.250               0.001036                0.002198
1970-01-01 00:59:59.500               0.002072                0.002198
1970-01-01 00:59:59.750               0.005180                0.003663

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000                0.00000                0.000000
1970-01-01 00:00:00.500                0.00000                0.000000
1970-01-01 00:00:01.000                0.00000                0.000000
1970-01-01 00:00:01.500                0.00000                0.000000
1970-01-01 00:00:02.000                0.00000                0.000000
...                                        ...                     ...
1970-01-01 00:59:57.500                0.00361                0.002553
1970-01-01 00:59:58.000                0.01805                0.010210
1970-01-01 00:59:58.500                0.01083                0.010210
1970-01-01 00:59:59.000                0.02527                0.010210
1970-01-01 00:59:59.500                0.01444                0.007658

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000           3.139557e-04
1970-01-01 00:00:00.500           0.000000e+00
1970-01-01 00:00:01.000           0.000000e+00
1970-01-01 00:00:01.500           0.000000e+00
1970-01-01 00:00:02.000           0.000000e+00
...                                        ...
1970-01-01 00:59:57.500           3.609944e-03
1970-01-01 00:59:58.000           7.219888e-03
1970-01-01 00:59:58.500           3.609944e-03
1970-01-01 00:59:59.000           0.000000e+00
1970-01-01 00:59:59.500           1.776357e-15

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000                0.00000                0.000000
1970-01-01 00:00:00.250                0.00000                0.000000
1970-01-01 00:00:00.500                0.00000                0.000000
1970-01-01 00:00:00.750                0.00000                0.000000
1970-01-01 00:00:01.000                0.00000                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750                0.00361                0.005105
1970-01-01 00:59:59.000                0.00722                0.010210
1970-01-01 00:59:59.250                0.02527                0.005105
1970-01-01 00:59:59.500                0.01444                0.007658
1970-01-01 00:59:59.750                0.00361                0.002553

[14400 rows x 2 columns]
calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
1970-01-01 00:00:01.500               0.000628                0.000444
1970-01-01 00:00:02.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:57.500               0.003610                0.002553
1970-01-01 00:59:58.000               0.018050                0.022974
1970-01-01 00:59:58.500               0.021660                0.015316
1970-01-01 00:59:59.000               0.014440                0.012763
1970-01-01 00:59:59.500               0.046929                0.022974

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.000314
1970-01-01 00:00:00.500               0.000000
1970-01-01 00:00:01.000               0.000000
1970-01-01 00:00:01.500               0.000314
1970-01-01 00:00:02.000               0.000000
...                                        ...
1970-01-01 00:59:57.500               0.003610
1970-01-01 00:59:58.000               0.009025
1970-01-01 00:59:58.500               0.010830
1970-01-01 00:59:59.000               0.010830
1970-01-01 00:59:59.500               0.041514

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.250               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.000000                0.000000
1970-01-01 00:59:59.000               0.014440                0.012763
1970-01-01 00:59:59.250               0.007220                0.007658
1970-01-01 00:59:59.500               0.003610                0.000000
1970-01-01 00:59:59.750               0.046929                0.022974

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 01:29:14 to 1970-01-01 01:29:14.500000 for index 3508
calculating features from 85664 to 85671 for index 3508
processed hour 1 - start: 57600 | end: 85680
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.028880                0.002553
1970-01-01 01:00:00.500               0.018050                0.007658
1970-01-01 01:00:01.000               0.050539                0.150604
1970-01-01 01:00:01.500               0.602861                0.306314
1970-01-01 01:00:02.000               0.151618                0.222078
...                                        ...                     ...
1970-01-01 01:29:12.500               0.043319                0.048500
1970-01-01 01:29:13.000               0.061369                0.061263
1970-01-01 01:29:13.500               0.046929                0.074026
1970-01-01 01:29:14.000               0.054149                0.063815
1970-01-01 01:29:14.500               0.050539                0.222078

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.050539
1970-01-01 01:00:00.500               0.041514
1970-01-01 01:00:01.000               0.164252
1970-01-01 01:00:01.500               1.008979
1970-01-01 01:00:02.000               0.570371
...                                        ...
1970-01-01 01:29:12.500               0.005415
1970-01-01 01:29:13.000               0.357384
1970-01-01 01:29:13.500               0.297820
1970-01-01 01:29:14.000               0.046929
1970-01-01 01:29:14.500               0.189522

[3510 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.025270                0.002553
1970-01-01 01:00:00.250               0.028880                0.002553
1970-01-01 01:00:00.500               0.014440                0.007658
1970-01-01 01:00:00.750               0.018050                0.000000
1970-01-01 01:00:01.000               0.018050                0.010210
...                                        ...                     ...
1970-01-01 01:29:13.750               0.018050                0.074026
1970-01-01 01:29:14.000               0.054149                0.063815
1970-01-01 01:29:14.250               0.036099                0.048500
1970-01-01 01:29:14.500               0.010830                0.005105
1970-01-01 01:29:14.750               0.050539                0.222078

[7020 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.001570                0.001110
1970-01-01 00:00:00.500               0.000314                0.000222
1970-01-01 00:00:01.000               0.000314                0.000222
1970-01-01 00:00:01.500               0.000000                0.000000
1970-01-01 00:00:02.000               0.040186                0.028194
...                                        ...                     ...
1970-01-01 00:59:57.500               0.002072                0.002198
1970-01-01 00:59:58.000               0.004144                0.001465
1970-01-01 00:59:58.500               0.002072                0.004396
1970-01-01 00:59:59.000               0.006216                0.004396
1970-01-01 00:59:59.500               0.002072                0.002198

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.001099
1970-01-01 00:00:00.500               0.000157
1970-01-01 00:00:01.000               0.000157
1970-01-01 00:00:01.500               0.000000
1970-01-01 00:00:02.000               0.020250
...                                        ...
1970-01-01 00:59:57.500               0.007252
1970-01-01 00:59:58.000               0.001036
1970-01-01 00:59:58.500               0.002072
1970-01-01 00:59:59.000               0.006216
1970-01-01 00:59:59.500               0.001036

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.250               0.001570                0.001110
1970-01-01 00:00:00.500               0.000314                0.000222
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.002072                0.004396
1970-01-01 00:59:59.000               0.006216                0.004396
1970-01-01 00:59:59.250               0.004144                0.004396
1970-01-01 00:59:59.500               0.002072                0.000733
1970-01-01 00:59:59.750               0.001036                0.002198

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.006734                0.006216
1970-01-01 00:00:00.500               0.002198                0.001776
1970-01-01 00:00:01.000               0.001256                0.000222
1970-01-01 00:00:01.500               0.001256                0.000888
1970-01-01 00:00:02.000               0.001570                0.003330
...                                        ...                     ...
1970-01-01 00:59:57.500               0.003454                0.002664
1970-01-01 00:59:58.000               0.001256                0.002442
1970-01-01 00:59:58.500               0.005965                0.004662
1970-01-01 00:59:59.000               0.001256                0.001332
1970-01-01 00:59:59.500               0.000942                0.001110

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.006993
1970-01-01 00:00:00.500               0.004709
1970-01-01 00:00:01.000               0.001099
1970-01-01 00:00:01.500               0.002198
1970-01-01 00:00:02.000               0.000314
...                                        ...
1970-01-01 00:59:57.500               0.003454
1970-01-01 00:59:58.000               0.000157
1970-01-01 00:59:58.500               0.018523
1970-01-01 00:59:59.000               0.006122
1970-01-01 00:59:59.500               0.001256

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.006734                0.004762
1970-01-01 00:00:00.250               0.002512                0.006216
1970-01-01 00:00:00.500               0.000942                0.001332
1970-01-01 00:00:00.750               0.002198                0.001776
1970-01-01 00:00:01.000               0.001256                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.000942                0.001998
1970-01-01 00:59:59.000               0.001256                0.001110
1970-01-01 00:59:59.250               0.001256                0.001332
1970-01-01 00:59:59.500               0.000314                0.000222
1970-01-01 00:59:59.750               0.000942                0.001110

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 01:38:20 to 1970-01-01 01:38:20.500000 for index 4600
calculating features from 94400 to 94407 for index 4600

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

processed hour 1 - start: 57600 | end: 94414
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.002072                0.001465
1970-01-01 01:00:00.500               0.004144                0.004396
1970-01-01 01:00:01.000               0.001036                0.000733
1970-01-01 01:00:01.500               0.005180                0.002930
1970-01-01 01:00:02.000               0.003108                0.001465
...                                        ...                     ...
1970-01-01 01:38:18.500               0.000000                0.000000
1970-01-01 01:38:19.000               0.000000                0.000000
1970-01-01 01:38:19.500               0.000000                0.000000
1970-01-01 01:38:20.000               0.000000                0.000000
1970-01-01 01:38:20.500               0.000000                0.000000

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.001554
1970-01-01 01:00:00.500               0.000518
1970-01-01 01:00:01.000               0.003108
1970-01-01 01:00:01.500               0.003108
1970-01-01 01:00:02.000               0.001036
...                                        ...
1970-01-01 01:38:18.500               0.000000
1970-01-01 01:38:19.000               0.000000
1970-01-01 01:38:19.500               0.000000
1970-01-01 01:38:20.000               0.000000
1970-01-01 01:38:20.500               0.000000

[4602 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.002072                0.001465
1970-01-01 01:00:00.250               0.002072                0.000733
1970-01-01 01:00:00.500               0.004144                0.004396
1970-01-01 01:00:00.750               0.003108                0.002198
1970-01-01 01:00:01.000               0.001036                0.000733
...                                        ...                     ...
1970-01-01 01:38:19.750               0.000000                0.000000
1970-01-01 01:38:20.000               0.000000                0.000000
1970-01-01 01:38:20.250               0.000000                0.000000
1970-01-01 01:38:20.500               0.000000                0.000000
1970-01-01 01:38:20.750               0.000000                0.000000

[9204 rows x 2 columns]
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
1970-01-01 00:00:01.500               0.000000                0.000000
1970-01-01 00:00:02.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:57.500               0.003610                0.005105
1970-01-01 00:59:58.000               0.036099                0.012763
1970-01-01 00:59:58.500               0.007220                0.010210
1970-01-01 00:59:59.000               0.014440                0.005105
1970-01-01 00:59:59.500               0.003610                0.005105

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.000314
1970-01-01 00:00:00.500               0.000000
1970-01-01 00:00:01.000               0.000000
1970-01-01 00:00:01.500               0.000000
1970-01-01 00:00:02.000               0.000000
...                                        ...
1970-01-01 00:59:57.500               0.016245
1970-01-01 00:59:58.000               0.016245
1970-01-01 00:59:58.500               0.001805
1970-01-01 00:59:59.000               0.001805
1970-01-01 00:59:59.500               0.019855

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000                0.00000                0.000000
1970-01-01 00:00:00.250                0.00000                0.000000
1970-01-01 00:00:00.500                0.00000                0.000000
1970-01-01 00:00:00.750                0.00000                0.000000
1970-01-01 00:00:01.000                0.00000                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750                0.00361                0.002553
1970-01-01 00:59:59.000                0.01444                0.005105
1970-01-01 00:59:59.250                0.00361                0.002553
1970-01-01 00:59:59.500                0.00361                0.002553
1970-01-01 00:59:59.750                0.00361                0.005105

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 00:59:59 to 1970-01-01 00:59:59.500000 for index 7198
calculating features from 57584 to 57591 for index 7198
processed hour 0 - start: 0 | end: 57600
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:01.000               0.000628                0.000444
1970-01-01 00:00:01.500               0.000000                0.000000
1970-01-01 00:00:02.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:57.500               0.003108                0.003663
1970-01-01 00:59:58.000               0.009324                0.006593
1970-01-01 00:59:58.500               0.007252                0.003663
1970-01-01 00:59:59.000               0.005180                0.004396
1970-01-01 00:59:59.500               0.003108                0.002198

                         third_2thofa_sec_feat
1970-01-01 00:00:00.000               0.000314
1970-01-01 00:00:00.500               0.000000
1970-01-01 00:00:01.000               0.000314
1970-01-01 00:00:01.500               0.000000
1970-01-01 00:00:02.000               0.000000
...                                        ...
1970-01-01 00:59:57.500               0.006734
1970-01-01 00:59:58.000               0.000518
1970-01-01 00:59:58.500               0.003108
1970-01-01 00:59:59.000               0.003108
1970-01-01 00:59:59.500               0.000518

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 00:00:00.000               0.000000                0.000000
1970-01-01 00:00:00.250               0.000000                0.000000
1970-01-01 00:00:00.500               0.000000                0.000000
1970-01-01 00:00:00.750               0.000000                0.000000
1970-01-01 00:00:01.000               0.000000                0.000000
...                                        ...                     ...
1970-01-01 00:59:58.750               0.002072                0.003663
1970-01-01 00:59:59.000               0.005180                0.004396
1970-01-01 00:59:59.250               0.004144                0.004396
1970-01-01 00:59:59.500               0.003108                0.002198
1970-01-01 00:59:59.750               0.002072                0.001465

[14400 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 01:00:00 to 1970-01-01 01:00:00.500000 for index 0
calculating features from 57600 to 57607 for index 0
calculating features from 1970-01-01 01:42:22.500000 to 1970-01-01 01:42:23 for index 5085
calculating features from 98280 to 98287 for index 5085
processed hour 1 - start: 57600 | end: 98290
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.003108                0.001465
1970-01-01 01:00:00.500               0.001036                0.002930
1970-01-01 01:00:01.000               0.008288                0.008059
1970-01-01 01:00:01.500               0.004144                0.003663
1970-01-01 01:00:02.000               0.001036                0.002930
...                                        ...                     ...
1970-01-01 01:42:21.000               0.018050                0.022974
1970-01-01 01:42:21.500               0.025270                0.012763
1970-01-01 01:42:22.000               0.003610                0.010210
1970-01-01 01:42:22.500               0.003610                0.002553
1970-01-01 01:42:23.000               0.014440                0.000000

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.009324
1970-01-01 01:00:00.500               0.007770
1970-01-01 01:00:01.000               0.007770
1970-01-01 01:00:01.500               0.004144
1970-01-01 01:00:02.000               0.006216
...                                        ...
1970-01-01 01:42:21.000               0.086639
1970-01-01 01:42:21.500               0.063174
1970-01-01 01:42:22.000               0.003610
1970-01-01 01:42:22.500               0.007220
1970-01-01 01:42:23.000               0.000000

[5087 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.001036            1.465201e-03
1970-01-01 01:00:00.250               0.003108            8.881784e-16
1970-01-01 01:00:00.500               0.001036            2.197802e-03
1970-01-01 01:00:00.750               0.001036            2.930403e-03
1970-01-01 01:00:01.000               0.008288            8.058608e-03
...                                        ...                     ...
1970-01-01 01:42:22.250               0.000000            0.000000e+00
1970-01-01 01:42:22.500               0.003610            2.552616e-03
1970-01-01 01:42:22.750               0.003610            2.552616e-03
1970-01-01 01:42:23.000               0.014440            0.000000e+00
1970-01-01 01:42:23.250               0.000000            0.000000e+00

[10174 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

calculating features from 1970-01-01 01:32:16 to 1970-01-01 01:32:16.500000 for index 3872
calculating features from 88576 to 88583 for index 3872
processed hour 1 - start: 57600 | end: 88587
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.001036                0.000733
1970-01-01 01:00:00.500               0.009324                0.008059
1970-01-01 01:00:01.000               0.009324                0.008059
1970-01-01 01:00:01.500               0.011397                0.007326
1970-01-01 01:00:02.000               0.009324                0.013919
...                                        ...                     ...
1970-01-01 01:32:14.500               0.015541                0.015385
1970-01-01 01:32:15.000               0.030046                0.042491
1970-01-01 01:32:15.500               0.087029                0.072527
1970-01-01 01:32:16.000               0.566377                0.482173
1970-01-01 01:32:16.500               0.124326                0.860073

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.001554
1970-01-01 01:00:00.500               0.003108
1970-01-01 01:00:01.000               0.002072
1970-01-01 01:00:01.500               0.001036
1970-01-01 01:00:02.000               0.001036
...                                        ...
1970-01-01 01:32:14.500               0.010361
1970-01-01 01:32:15.000               0.022793
1970-01-01 01:32:15.500               0.090137
1970-01-01 01:32:16.000               0.629148
1970-01-01 01:32:16.500               0.000000

[3874 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.001036                0.000000
1970-01-01 01:00:00.250               0.001036                0.000733
1970-01-01 01:00:00.500               0.001036                0.002198
1970-01-01 01:00:00.750               0.009324                0.008059
1970-01-01 01:00:01.000               0.004144                0.008059
...                                        ...                     ...
1970-01-01 01:32:15.750               0.087029                0.052015
1970-01-01 01:32:16.000               0.151618                0.162526
1970-01-01 01:32:16.250               0.566377                0.482173
1970-01-01 01:32:16.500               0.124326                0.860073
1970-01-01 01:32:16.750               0.000000                0.000000

[7748 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

calculating features from 1970-01-01 01:37:19.500000 to 1970-01-01 01:37:20 for index 4479
calculating features from 93432 to 93439 for index 4479
processed hour 1 - start: 57600 | end: 93445
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.007220                0.005105
1970-01-01 01:00:00.500               0.007220                0.005105
1970-01-01 01:00:01.000               0.003610                0.002553
1970-01-01 01:00:01.500               0.021660                0.020421
1970-01-01 01:00:02.000               0.028880                0.020421
...                                        ...                     ...
1970-01-01 01:37:18.000               0.003610                0.002553
1970-01-01 01:37:18.500               0.032489                0.022974
1970-01-01 01:37:19.000               0.003610                0.007658
1970-01-01 01:37:19.500               0.010830                0.005105
1970-01-01 01:37:20.000               0.032489                0.025526

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.007220
1970-01-01 01:00:00.500               0.007220
1970-01-01 01:00:01.000               0.005415
1970-01-01 01:00:01.500               0.001805
1970-01-01 01:00:02.000               0.023465
...                                        ...
1970-01-01 01:37:18.000               0.010830
1970-01-01 01:37:18.500               0.005415
1970-01-01 01:37:19.000               0.010830
1970-01-01 01:37:19.500               0.001805
1970-01-01 01:37:20.000               0.021660

[4481 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.007220                0.005105
1970-01-01 01:00:00.250               0.007220                0.005105
1970-01-01 01:00:00.500               0.003610                0.000000
1970-01-01 01:00:00.750               0.007220                0.005105
1970-01-01 01:00:01.000               0.003610                0.000000
...                                        ...                     ...
1970-01-01 01:37:19.250               0.003610                0.002553
1970-01-01 01:37:19.500               0.010830                0.005105
1970-01-01 01:37:19.750               0.007220                0.002553
1970-01-01 01:37:20.000               0.032489                0.025526
1970-01-01 01:37:20.250               0.000000                0.000000

[8962 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

calculating features from 1970-01-01 01:38:44.500000 to 1970-01-01 01:38:45 for index 4649
calculating features from 94792 to 94799 for index 4649
processed hour 1 - start: 57600 | end: 94802
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.000628                0.002220
1970-01-01 01:00:00.500               0.000314                0.001332
1970-01-01 01:00:01.000               0.005023                0.006660
1970-01-01 01:00:01.500               0.000942                0.001776
1970-01-01 01:00:02.000               0.005965                0.001110
...                                        ...                     ...
1970-01-01 01:38:43.000               0.000000                0.000444
1970-01-01 01:38:43.500               0.000628                0.000444
1970-01-01 01:38:44.000               0.000628                0.001332
1970-01-01 01:38:44.500               0.000314                0.000222
1970-01-01 01:38:45.000               0.000314                0.000000

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.004081
1970-01-01 01:00:00.500               0.000628
1970-01-01 01:00:01.000               0.007535
1970-01-01 01:00:01.500               0.002826
1970-01-01 01:00:02.000               0.021035
...                                        ...
1970-01-01 01:38:43.000               0.000314
1970-01-01 01:38:43.500               0.001570
1970-01-01 01:38:44.000               0.001099
1970-01-01 01:38:44.500               0.000785
1970-01-01 01:38:45.000               0.000000

[4651 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.000628                0.002220
1970-01-01 01:00:00.250               0.000314                0.000444
1970-01-01 01:00:00.500               0.000314                0.001332
1970-01-01 01:00:00.750               0.000000                0.000000
1970-01-01 01:00:01.000               0.000942                0.000888
...                                        ...                     ...
1970-01-01 01:38:44.250               0.000314                0.000222
1970-01-01 01:38:44.500               0.000314                0.000222
1970-01-01 01:38:44.750               0.000314                0.000000
1970-01-01 01:38:45.000               0.000314                0.000000
1970-01-01 01:38:45.250               0.000000                0.000000

[9302 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

calculating features from 1970-01-01 01:43:23 to 1970-01-01 01:43:23.500000 for index 5206
calculating features from 99248 to 99255 for index 5206
processed hour 1 - start: 57600 | end: 99259
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.003610                0.010210
1970-01-01 01:00:00.500               0.018050                0.005105
1970-01-01 01:00:01.000               0.010830                0.010210
1970-01-01 01:00:01.500               0.014440                0.005105
1970-01-01 01:00:02.000               0.007220                0.012763
...                                        ...                     ...
1970-01-01 01:43:21.500               0.001884                0.001776
1970-01-01 01:43:22.000               0.000000                0.000000
1970-01-01 01:43:22.500               0.000000                0.000000
1970-01-01 01:43:23.000               0.000628                0.000444
1970-01-01 01:43:23.500               0.000000                0.000000

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.019855
1970-01-01 01:00:00.500               0.000000
1970-01-01 01:00:01.000               0.027075
1970-01-01 01:00:01.500               0.023465
1970-01-01 01:00:02.000               0.005415
...                                        ...
1970-01-01 01:43:21.500               0.001256
1970-01-01 01:43:22.000               0.000000
1970-01-01 01:43:22.500               0.000000
1970-01-01 01:43:23.000               0.000314
1970-01-01 01:43:23.500               0.000000

[5208 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.003610                0.010210
1970-01-01 01:00:00.250               0.003610                0.007658
1970-01-01 01:00:00.500               0.010830                0.005105
1970-01-01 01:00:00.750               0.018050                0.005105
1970-01-01 01:00:01.000               0.010830                0.002553
...                                        ...                     ...
1970-01-01 01:43:22.750               0.000000                0.000000
1970-01-01 01:43:23.000               0.000628                0.000444
1970-01-01 01:43:23.250               0.000000                0.000000
1970-01-01 01:43:23.500               0.000000                0.000000
1970-01-01 01:43:23.750               0.000000                0.000000

[10416 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

calculating features from 1970-01-01 01:59:59 to 1970-01-01 01:59:59.500000 for index 7198
calculating features from 115184 to 115191 for index 7198
processed hour 1 - start: 57600 | end: 115200
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.043319                0.045947
1970-01-01 01:00:00.500               0.010830                0.020421
1970-01-01 01:00:01.000               0.018050                0.033184
1970-01-01 01:00:01.500               0.025270                0.012763
1970-01-01 01:00:02.000               0.007220                0.007658
...                                        ...                     ...
1970-01-01 01:59:57.500               0.000000                0.000000
1970-01-01 01:59:58.000               0.000000                0.000000
1970-01-01 01:59:58.500               0.000000                0.000000
1970-01-01 01:59:59.000               0.000000                0.000000
1970-01-01 01:59:59.500               0.000000                0.000000

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.009025
1970-01-01 01:00:00.500               0.005415
1970-01-01 01:00:01.000               0.034294
1970-01-01 01:00:01.500               0.027075
1970-01-01 01:00:02.000               0.003610
...                                        ...
1970-01-01 01:59:57.500               0.000000
1970-01-01 01:59:58.000               0.000000
1970-01-01 01:59:58.500               0.000000
1970-01-01 01:59:59.000               0.000000
1970-01-01 01:59:59.500               0.000000

[7200 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.003610                0.007658
1970-01-01 01:00:00.250               0.043319                0.045947
1970-01-01 01:00:00.500               0.010830                0.020421
1970-01-01 01:00:00.750               0.003610                0.002553
1970-01-01 01:00:01.000               0.010830                0.010210
...                                        ...                     ...
1970-01-01 01:59:58.750               0.000000                0.000000
1970-01-01 01:59:59.000               0.000000                0.000000
1970-01-01 01:59:59.250               0.000000                0.000000
1970-01-01 01:59:59.500               0.000000                0.000000
1970-01-01 01:59:59.750               0.000000                0.000000

[14400 rows x 2 columns]
calculating features from 1970-01-01 02:00:00 to 1970-01-01 02:00:00.500000 for index 0
calculating features from 115200 to 115207 for index 0

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:431: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  whole_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / whole_freq) * 1000)}ms')
d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:432: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  half_inc_ts = pd.date_range(start=timestamp_list[0], periods=data.shape[0], freq=f'{((1 / half_freq) * 1000)}ms')

calculating features from 1970-01-01 02:00:31.500000 to 1970-01-01 02:00:32 for index 63
calculating features from 115704 to 115711 for index 63
processed hour 2 - start: 115200 | end: 115719
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 02:00:00.000                    0.0                     0.0
1970-01-01 02:00:00.500                    0.0                     0.0
1970-01-01 02:00:01.000                    0.0                     0.0
1970-01-01 02:00:01.500                    0.0                     0.0
1970-01-01 02:00:02.000                    0.0                     0.0
...                                        ...                     ...
1970-01-01 02:00:30.000                    0.0                     0.0
1970-01-01 02:00:30.500                    0.0                     0.0
1970-01-01 02:00:31.000                    0.0                     0.0
1970-01-01 02:00:31.500                    0.0                     0.0
1970-01-01 02:00:32.000                    0.0                     0.0

                         third_2thofa_sec_feat
1970-01-01 02:00:00.000                    0.0
1970-01-01 02:00:00.500                    0.0
1970-01-01 02:00:01.000                    0.0
1970-01-01 02:00:01.500                    0.0
1970-01-01 02:00:02.000                    0.0
...                                        ...
1970-01-01 02:00:30.000                    0.0
1970-01-01 02:00:30.500                    0.0
1970-01-01 02:00:31.000                    0.0
1970-01-01 02:00:31.500                    0.0
1970-01-01 02:00:32.000                    0.0

[65 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 02:00:00.000                    0.0                     0.0
1970-01-01 02:00:00.250                    0.0                     0.0
1970-01-01 02:00:00.500                    0.0                     0.0
1970-01-01 02:00:00.750                    0.0                     0.0
1970-01-01 02:00:01.000                    0.0                     0.0
...                                        ...                     ...
1970-01-01 02:00:31.250                    0.0                     0.0
1970-01-01 02:00:31.500                    0.0                     0.0
1970-01-01 02:00:31.750                    0.0                     0.0
1970-01-01 02:00:32.000                    0.0                     0.0
1970-01-01 02:00:32.250                    0.0                     0.0

[130 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

calculating features from 1970-01-01 01:53:28.500000 to 1970-01-01 01:53:29 for index 6417
calculating features from 108936 to 108943 for index 6417
processed hour 1 - start: 57600 | end: 108949
whole wave:
                         first_2thofa_sec_feat  second_2thofa_sec_feat  \
1970-01-01 01:00:00.000               0.003108                0.002930
1970-01-01 01:00:00.500               0.002072                0.002198
1970-01-01 01:00:01.000               0.003108                0.001465
1970-01-01 01:00:01.500               0.001036                0.001465
1970-01-01 01:00:02.000               0.004144                0.001465
...                                        ...                     ...
1970-01-01 01:53:27.000               0.006216                0.013187
1970-01-01 01:53:27.500               0.002072                0.003663
1970-01-01 01:53:28.000               0.602983                0.279853
1970-01-01 01:53:28.500               0.891367                0.630292
1970-01-01 01:53:29.000               0.008477                0.005994

                         third_2thofa_sec_feat
1970-01-01 01:00:00.000               0.002590
1970-01-01 01:00:00.500               0.000000
1970-01-01 01:00:01.000               0.005698
1970-01-01 01:00:01.500               0.003626
1970-01-01 01:00:02.000               0.002072
...                                        ...
1970-01-01 01:53:27.000               0.021757
1970-01-01 01:53:27.500               0.007770
1970-01-01 01:53:28.000               0.227932
1970-01-01 01:53:28.500               0.444271
1970-01-01 01:53:29.000               0.004238

[6419 rows x 3 columns]
half wave:
                         first_4thofa_sec_feat  second_4thofa_sec_feat
1970-01-01 01:00:00.000               0.001036                0.002198
1970-01-01 01:00:00.250               0.003108                0.002930
1970-01-01 01:00:00.500               0.001036                0.000733
1970-01-01 01:00:00.750               0.002072                0.002198
1970-01-01 01:00:01.000               0.003108                0.000733
...                                        ...                     ...
1970-01-01 01:53:28.250               0.602983                0.279853
1970-01-01 01:53:28.500               0.891367                0.630292
1970-01-01 01:53:28.750               0.002826                0.001998
1970-01-01 01:53:29.000               0.008477                0.005994
1970-01-01 01:53:29.250               0.000000                0.000000

[12838 rows x 2 columns]

d:\Projects\To Github\thesis-writing-1\server-side\modelling\utilities\feature_extractors.py:167: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  eda_labels = pd.concat([eda_labels, features_per_hour_1[i][1]], ignore_index=True)

[('ahixac_expert1',
  (       raw_128hz_max  raw_128hz_min  raw_128hz_amp  raw_128hz_median  \
   0           0.000222       0.000000       0.000118          0.000222
   1           0.000222       0.000222       0.000222          0.000222
   2           0.000222       0.000222       0.000222          0.000222
   3           0.000222       0.000222       0.000222          0.000222
   4           0.000222       0.000222       0.000222          0.000222
   ...              ...            ...            ...               ...
   13008       2.726007       2.673260       2.695696          2.692308
   13009       2.733333       2.668864       2.698558          2.696703
   13010       2.714286       2.624908       2.664309          2.665201
   13011       2.693773       2.570696       2.616277          2.610256
   13012       0.000000       0.000000       0.000000          0.000000

          raw_128hz_std  raw_128hz_range  raw_128hz_shannon_entropy  \
   0       1.107831e-04         0.000222                   0.691193
   1       5.421011e-20         0.000000                   0.000000
   2       5.421011e-20         0.000000                   0.000000
   3       5.421011e-20         0.000000                   0.000000
   4       5.421011e-20         0.000000                   0.000000
   ...              ...              ...                        ...
   13008   1.377132e-02         0.052747                   3.285635
   13009   1.484814e-02         0.064469                   3.265055
   13010   1.988022e-02         0.089377                   3.503325
   13011   2.893902e-02         0.123077                   3.671302
   13012   0.000000e+00         0.000000                   0.000000

          raw_128hz_1d_max  raw_128hz_1d_min  raw_128hz_1d_amp  ...  \
   0              0.000111          0.000000          0.000059  ...
   1              0.000111          0.000111          0.000111  ...
   2              0.000111          0.000111          0.000111  ...
   3              0.000111          0.000111          0.000111  ...
   4              0.000111          0.000111          0.000111  ...
   ...                 ...               ...               ...  ...
   13008          1.363004          1.336630          1.347900  ...
   13009          1.366667          1.334432          1.349524  ...
   13010          1.357143          1.312454          1.331758  ...
   13011          1.346886          1.285348          1.307582  ...
   13012          0.000000          0.000000          0.000000  ...

          first_4thofa_sec_mean  second_4thofa_sec_mean  first_4thofa_sec_std  \
   0                   0.000000                0.000000              0.000000
   1                   0.000000                0.000000              0.000000
   2                   0.000000                0.000000              0.000000
   3                   0.000000                0.000000              0.000000
   4                   0.000000                0.000000              0.000000
   ...                      ...                     ...                   ...
   13008               0.002590                0.004029              0.000733
   13009               0.002590                0.005128              0.002198
   13010               0.020721                0.019780              0.019048
   13011               0.011915                0.028205              0.009524
   13012               0.000000                0.000000              0.000000

          second_4thofa_sec_std  first_4thofa_sec_median  \
   0                   0.000000                 0.000000
   1                   0.000000                 0.000000
   2                   0.000000                 0.000000
   3                   0.000000                 0.000000
   4                   0.000000                 0.000000
   ...                      ...                      ...
   13008               0.000518                 0.002590
   13009               0.006216                 0.002590
   13010               0.008288                 0.020721
   13011               0.024347                 0.011915
   13012               0.000000                 0.000000

          second_4thofa_sec_median  first_4thofa_sec_range  \
   0                      0.000000                0.000000
   1                      0.000000                0.000000
   2                      0.000000                0.000000
   3                      0.000000                0.000000
   4                      0.000000                0.000000
   ...                         ...                     ...
   13008                  0.004029                0.001036
   13009                  0.005128                0.003108
   13010                  0.019780                0.026937
   13011                  0.028205                0.013469
   13012                  0.000000                0.000000

          second_4thofa_sec_range  first_4thofa_sec_n_coeffs_above_zero  \
   0                     0.000000                                   0.0
   1                     0.000000                                   0.0
   2                     0.000000                                   0.0
   3                     0.000000                                   0.0
   4                     0.000000                                   0.0
   ...                        ...                                   ...
   13008                 0.000733                                   2.0
   13009                 0.008791                                   2.0
   13010                 0.011722                                   2.0
   13011                 0.034432                                   2.0
   13012                 0.000000                                   0.0

          second_4thofa_sec_n_coeffs_above_zero
   0                                        0.0
   1                                        0.0
   2                                        0.0
   3                                        0.0
   4                                        0.0
   ...                                      ...
   13008                                    2.0
   13009                                    2.0
   13010                                    2.0
   13011                                    2.0
   13012                                    0.0

   [13013 rows x 182 columns],
   0        0.0
   1        0.0
   2        0.0
   3        0.0
   4        0.0
           ...
   13008    0.0
   13009    0.0
   13010    0.0
   13011    0.0
   13012    0.0
   Length: 13013, dtype: float64)),
 ('akakip_expert2',
  (       raw_128hz_max  raw_128hz_min  raw_128hz_amp  raw_128hz_median  \
   0           0.000222       0.000000       0.000118          0.000222
   1           0.000222       0.000222       0.000222          0.000222
   2           0.000222       0.000222       0.000222          0.000222
   3           0.000222       0.000222       0.000222          0.000222
   4           0.000222       0.000222       0.000222          0.000222
   ...              ...            ...            ...               ...
   12039       5.848043       5.791885       5.825309          5.827622
   12040       5.822517       5.669360       5.755032          5.761254
   12041       5.669360       5.470256       5.564543          5.562150
   12042       5.470256       5.322204       5.395831          5.396230
   12043       0.000000       0.000000       0.000000          0.000000

          raw_128hz_std  raw_128hz_range  raw_128hz_shannon_entropy  \
   0       1.107831e-04         0.000222                   0.691193
   1       5.421011e-20         0.000000                   0.000000
   2       5.421011e-20         0.000000                   0.000000
   3       5.421011e-20         0.000000                   0.000000
   4       5.421011e-20         0.000000                   0.000000
   ...              ...              ...                        ...
   12039   1.365499e-02         0.056158                   2.137684
   12040   4.432730e-02         0.153157                   3.348832
   12041   5.891076e-02         0.199104                   3.592835
   12042   4.299666e-02         0.148052                   3.340657
   12043   0.000000e+00         0.000000                   0.000000

          raw_128hz_1d_max  raw_128hz_1d_min  raw_128hz_1d_amp  ...  \
   0              0.000111          0.000000          0.000059  ...
   1              0.000111          0.000111          0.000111  ...
   2              0.000111          0.000111          0.000111  ...
   3              0.000111          0.000111          0.000111  ...
   4              0.000111          0.000111          0.000111  ...
   ...                 ...               ...               ...  ...
   12039          2.924021          2.898495          2.913173  ...
   12040          2.908706          2.837232          2.877862  ...
   12041          2.829575          2.737680          2.782138  ...
   12042          2.735128          2.663655          2.697945  ...
   12043          0.000000          0.000000          0.000000  ...

          first_4thofa_sec_mean  second_4thofa_sec_mean  first_4thofa_sec_std  \
   0                   0.000000                0.000000          0.000000e+00
   1                   0.000000                0.000000          0.000000e+00
   2                   0.000000                0.000000          0.000000e+00
   3                   0.000000                0.000000          0.000000e+00
   4                   0.000000                0.000000          0.000000e+00
   ...                      ...                     ...                   ...
   12039               0.005415                0.010210          2.552616e-03
   12040               0.014440                0.034460          5.105232e-03
   12041               0.018050                0.052329          3.140185e-16
   12042               0.014440                0.037013          6.280370e-16
   12043               0.000000                0.000000          0.000000e+00

          second_4thofa_sec_std  first_4thofa_sec_median  \
   0                   0.000000                 0.000000
   1                   0.000000                 0.000000
   2                   0.000000                 0.000000
   3                   0.000000                 0.000000
   4                   0.000000                 0.000000
   ...                      ...                      ...
   12039               0.014440                 0.005415
   12040               0.009025                 0.014440
   12041               0.005415                 0.018050
   12042               0.001805                 0.014440
   12043               0.000000                 0.000000

          second_4thofa_sec_median  first_4thofa_sec_range  \
   0                      0.000000            0.000000e+00
   1                      0.000000            0.000000e+00
   2                      0.000000            0.000000e+00
   3                      0.000000            0.000000e+00
   4                      0.000000            0.000000e+00
   ...                         ...                     ...
   12039                  0.010210            3.609944e-03
   12040                  0.034460            7.219888e-03
   12041                  0.052329            4.440892e-16
   12042                  0.037013            8.881784e-16
   12043                  0.000000            0.000000e+00

          second_4thofa_sec_range  first_4thofa_sec_n_coeffs_above_zero  \
   0                     0.000000                                   0.0
   1                     0.000000                                   0.0
   2                     0.000000                                   0.0
   3                     0.000000                                   0.0
   4                     0.000000                                   0.0
   ...                        ...                                   ...
   12039                 0.020421                                   2.0
   12040                 0.012763                                   2.0
   12041                 0.007658                                   2.0
   12042                 0.002553                                   2.0
   12043                 0.000000                                   0.0

          second_4thofa_sec_n_coeffs_above_zero
   0                                        0.0
   1                                        0.0
   2                                        0.0
   3                                        0.0
   4                                        0.0
   ...                                      ...
   12039                                    1.0
   12040                                    2.0
   12041                                    2.0
   12042                                    2.0
   12043                                    0.0

   [12044 rows x 182 columns],
   0        0.0
   1        0.0
   2        0.0
   3        0.0
   4        0.0
           ...
   12039    0.0
   12040    0.0
   12041    0.0
   12042    0.0
   12043    0.0
   Length: 12044, dtype: float64)),
 ('aqamom_expert2',
  (       raw_128hz_max  raw_128hz_min  raw_128hz_amp  raw_128hz_median  \
   0           0.000222       0.000000       0.000118          0.000222
   1           0.000222       0.000222       0.000222          0.000222
   2           0.000222       0.000222       0.000222          0.000222
   3           0.000222       0.000222       0.000222          0.000222
   4           0.000222       0.000222       0.000222          0.000222
   ...              ...            ...            ...               ...
   11797       3.153846       3.130403       3.142903          3.142125
   11798       3.155311       3.127473       3.139240          3.139927
   11799       3.186081       3.140659       3.161195          3.161172
   11800       3.232967       3.175824       3.201648          3.200000
   11801       0.000000       0.000000       0.000000          0.000000

          raw_128hz_std  raw_128hz_range  raw_128hz_shannon_entropy  \
   0       1.107831e-04         0.000222                   0.691193
   1       5.421011e-20         0.000000                   0.000000
   2       5.421011e-20         0.000000                   0.000000
   3       5.421011e-20         0.000000                   0.000000
   4       5.421011e-20         0.000000                   0.000000
   ...              ...              ...                        ...
   11797   5.585142e-03         0.023443                   2.598985
   11798   6.954735e-03         0.027839                   2.805150
   11799   1.215569e-02         0.045421                   3.146412
   11800   1.537262e-02         0.057143                   3.381535
   11801   0.000000e+00         0.000000                   0.000000

          raw_128hz_1d_max  raw_128hz_1d_min  raw_128hz_1d_amp  ...  \
   0              0.000111          0.000000          0.000059  ...
   1              0.000111          0.000111          0.000111  ...
   2              0.000111          0.000111          0.000111  ...
   3              0.000111          0.000111          0.000111  ...
   4              0.000111          0.000111          0.000111  ...
   ...                 ...               ...               ...  ...
   11797          1.576923          1.565201          1.571404  ...
   11798          1.577656          1.563736          1.569609  ...
   11799          1.591575          1.570330          1.580549  ...
   11800          1.615751          1.587912          1.600745  ...
   11801          0.000000          0.000000          0.000000  ...

          first_4thofa_sec_mean  second_4thofa_sec_mean  first_4thofa_sec_std  \
   0                   0.000000                0.000000              0.000000
   1                   0.000000                0.000000              0.000000
   2                   0.000000                0.000000              0.000000
   3                   0.000000                0.000000              0.000000
   4                   0.000000                0.000000              0.000000
   ...                      ...                     ...                   ...
   11797               0.004662                0.005495              0.003663
   11798               0.004662                0.005128              0.005128
   11799               0.004662                0.011722              0.002198
   11800               0.009843                0.015385              0.005128
   11801               0.000000                0.000000              0.000000

          second_4thofa_sec_std  first_4thofa_sec_median  \
   0               0.000000e+00                 0.000000
   1               0.000000e+00                 0.000000
   2               0.000000e+00                 0.000000
   3               0.000000e+00                 0.000000
   4               0.000000e+00                 0.000000
   ...                      ...                      ...
   11797           2.590135e-03                 0.004662
   11798           4.144216e-03                 0.004662
   11799           3.108162e-03                 0.004662
   11800           9.420555e-16                 0.009843
   11801           0.000000e+00                 0.000000

          second_4thofa_sec_median  first_4thofa_sec_range  \
   0                      0.000000                0.000000
   1                      0.000000                0.000000
   2                      0.000000                0.000000
   3                      0.000000                0.000000
   4                      0.000000                0.000000
   ...                         ...                     ...
   11797                  0.005495                0.005180
   11798                  0.005128                0.007252
   11799                  0.011722                0.003108
   11800                  0.015385                0.007252
   11801                  0.000000                0.000000

          second_4thofa_sec_range  first_4thofa_sec_n_coeffs_above_zero  \
   0                 0.000000e+00                                   0.0
   1                 0.000000e+00                                   0.0
   2                 0.000000e+00                                   0.0
   3                 0.000000e+00                                   0.0
   4                 0.000000e+00                                   0.0
   ...                        ...                                   ...
   11797             3.663004e-03                                   2.0
   11798             5.860806e-03                                   2.0
   11799             4.395604e-03                                   2.0
   11800             1.332268e-15                                   2.0
   11801             0.000000e+00                                   0.0

          second_4thofa_sec_n_coeffs_above_zero
   0                                        0.0
   1                                        0.0
   2                                        0.0
   3                                        0.0
   4                                        0.0
   ...                                      ...
   11797                                    2.0
   11798                                    2.0
   11799                                    2.0
   11800                                    2.0
   11801                                    0.0

   [11802 rows x 182 columns],
   0        0.0
   1        0.0
   2        0.0
   3        0.0
   4        0.0
           ...
   11797    0.0
   11798    0.0
   11799    0.0
   11800    0.0
   11801    0.0
   Length: 11802, dtype: float64)),
 ('aretez_expert1',
  (       raw_128hz_max  raw_128hz_min  raw_128hz_amp  raw_128hz_median  \
   0           1.949957       1.794489       1.842088          1.835165
   1           1.838095       1.824908       1.831387          1.830769
   2           1.845421       1.824908       1.832349          1.832234

#### Above code takes about 204 minutes or 3 hrs and 20 minutes to run

In [30]:
# save each feature dataframe as a .csv file in the folder created earlier with the same names
for subject_name, (feature_segments, labels) in train_eda_data:
    feature_segments.to_csv(f'./data/Artifact Detection Data/train/{subject_name}_features.csv')
    labels.to_csv(f'./data/Artifact Detection Data/train/{subject_name}_labels.csv')

In [31]:
# test_files = os.listdir('./data/Electrodermal Activity artifact correction BEnchmark (EDABE)/Test/')
# test_files

In [32]:
# test_eda_data = concur_extract_features_from_all('./data/Electrodermal Activity artifact correction BEnchmark (EDABE)/Test/', test_files)
# test_eda_data

In [33]:
# # save each feature dataframe as a .csv file in the folder created earlier with the same names
# for subject_name, (feature_segments, labels)  in test_eda_data:
#     feature_segments.to_csv(f'./data/Artifact Detection Data/test/{subject_name}_features.csv')
#     labels.to_csv(f'./data/Artifact Detection Data/test/{subject_name}_labels.csv')

# testing outlier datapoint removal i.e. rows with purely zeros

In [34]:
ahixac_features = pd.read_csv(f'./data/Artifact Detection Data/train/ahixac_expert1_features.csv', index_col=0)
ahixac_features

,raw_128hz_max,raw_128hz_min,raw_128hz_amp,raw_128hz_median,raw_128hz_std,raw_128hz_range,raw_128hz_shannon_entropy,raw_128hz_1d_max,raw_128hz_1d_min,raw_128hz_1d_amp,...,first_4thofa_sec_mean,second_4thofa_sec_mean,first_4thofa_sec_std,second_4thofa_sec_std,first_4thofa_sec_median,second_4thofa_sec_median,first_4thofa_sec_range,second_4thofa_sec_range,first_4thofa_sec_n_coeffs_above_zero,second_4thofa_sec_n_coeffs_above_zero
0,0.000222,0.000000,0.000118,0.000222,1.107831e-04,0.000222,0.691193,0.000111,0.000000,0.000059,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
1,0.000222,0.000222,0.000222,0.000222,5.421011e-20,0.000000,0.000000,0.000111,0.000111,0.000111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
2,0.000222,0.000222,0.000222,0.000222,5.421011e-20,0.000000,0.000000,0.000111,0.000111,0.000111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
3,0.000222,0.000222,0.000222,0.000222,5.421011e-20,0.000000,0.000000,0.000111,0.000111,0.000111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
4,0.000222,0.000222,0.000222,0.000222,5.421011e-20,0.000000,0.000000,0.000111,0.000111,0.000111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13008,2.726007,2.673260,2.695696,2.692308,1.377132e-02,0.052747,3.285635,1.363004,1.336630,1.347900,...,0.002590,0.004029,0.000733,0.000518,0.002590,0.004029,0.001036,0.000733,2.0,2.0
13009,2.733333,2.668864,2.698558,2.696703,1.484814e-02,0.064469,3.265055,1.366667,1.334432,1.349524,...,0.002590,0.005128,0.002198,0.006216,0.002590,0.005128,0.003108,0.008791,2.0,2.0
13010,2.714286,2.624908,2.664309,2.665201,1.988022e-02,0.089377,3.503325,1.357143,1.312454,1.331758,...,0.020721,0.019780,0.019048,0.008288,0.020721,0.019780,0.026937,0.011722,2.0,2.0
13011,2.693773,2.570696,2.616277,2.610256,2.893902e-02,0.123077,3.671302,1.346886,1.285348,1.307582,...,0.011915,0.028205,0.009524,0.024347,0.011915,0.028205,0.013469,0.034432,2.0,2.0
13012,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0

#### recall axis 1 is the x axis and axis 0 is the y axis

In [35]:
non_zero_rows = (ahixac_features != 0).any(axis=1)
non_zero_rows

0         True
1         True
2         True
3         True
4         True
         ...
13008     True
13009     True
13010     True
13011     True
13012    False
Length: 13013, dtype: bool

In [36]:
ahixac_features.index[~non_zero_rows]

Index([7199, 13012], dtype='int64')

In [37]:
ahixac_features[non_zero_rows]

,raw_128hz_max,raw_128hz_min,raw_128hz_amp,raw_128hz_median,raw_128hz_std,raw_128hz_range,raw_128hz_shannon_entropy,raw_128hz_1d_max,raw_128hz_1d_min,raw_128hz_1d_amp,...,first_4thofa_sec_mean,second_4thofa_sec_mean,first_4thofa_sec_std,second_4thofa_sec_std,first_4thofa_sec_median,second_4thofa_sec_median,first_4thofa_sec_range,second_4thofa_sec_range,first_4thofa_sec_n_coeffs_above_zero,second_4thofa_sec_n_coeffs_above_zero
0,0.000222,0.000000,0.000118,0.000222,1.107831e-04,0.000222,0.691193,0.000111,0.000000,0.000059,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
1,0.000222,0.000222,0.000222,0.000222,5.421011e-20,0.000000,0.000000,0.000111,0.000111,0.000111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
2,0.000222,0.000222,0.000222,0.000222,5.421011e-20,0.000000,0.000000,0.000111,0.000111,0.000111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
3,0.000222,0.000222,0.000222,0.000222,5.421011e-20,0.000000,0.000000,0.000111,0.000111,0.000111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
4,0.000222,0.000222,0.000222,0.000222,5.421011e-20,0.000000,0.000000,0.000111,0.000111,0.000111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13007,2.708425,2.613187,2.656571,2.657875,2.243813e-02,0.095238,3.533161,1.353480,1.306593,1.328339,...,0.008806,0.017216,0.003663,0.001554,0.008806,0.017216,0.005180,0.002198,2.0,2.0
13008,2.726007,2.673260,2.695696,2.692308,1.377132e-02,0.052747,3.285635,1.363004,1.336630,1.347900,...,0.002590,0.004029,0.000733,0.000518,0.002590,0.004029,0.001036,0.000733,2.0,2.0
13009,2.733333,2.668864,2.698558,2.696703,1.484814e-02,0.064469,3.265055,1.366667,1.334432,1.349524,...,0.002590,0.005128,0.002198,0.006216,0.002590,0.005128,0.003108,0.008791,2.0,2.0
13010,2.714286,2.624908,2.664309,2.665201,1.988022e-02,0.089377,3.503325,1.357143,1.312454,1.331758,...,0.020721,0.019780,0.019048,0.008288,0.020721,0.019780,0.026937,0.011722,2.0,2.0
13011,2.693773,2.570696,2.616277,2.610256,2.893902e-02,0.123077,3.671302,1.346886,1.285348,1.307582,...,0.011915,0.028205,0.009524,0.024347,0.011915,0.028205,0.013469,0.034432,2.0,2.0

In [38]:
non_zero_rows_alt = ~(ahixac_features == 0).all(axis=1)
non_zero_rows_alt

0         True
1         True
2         True
3         True
4         True
         ...
13008     True
13009     True
13010     True
13011     True
13012    False
Length: 13013, dtype: bool

In [39]:
import re

# what I want is to individually open all the feature segment files as well as their corresponding label files
for train_subject_name in train_files:
    train_subject_name = re.sub(r".csv", "", train_subject_name)
    subject_features = pd.read_csv(f'./data/Artifact Detection Data/train/{train_subject_name}_features.csv', index_col=0)
    subject_labels = pd.read_csv(f'./data/Artifact Detection Data/train/{train_subject_name}_labels.csv', index_col=0)

    # allow modifications to the dataframe here i.e.
    # removing rows with purely 0.0 values for every feature/column
    # as these outliers can negatively impact the training of the 
    # ml model
    non_zero_rows = (subject_features != 0).any(axis=1)

    # keep only the rows that are non zero rows
    # this goes also for rows in the subjects labels
    subject_features[non_zero_rows].to_csv(f'./data/Artifact Detection Data/train/{train_subject_name}_features.csv')
    subject_labels[non_zero_rows].to_csv(f'./data/Artifact Detection Data/train/{train_subject_name}_labels.csv')

In [40]:
# # once notebook reaches end remove data to clear space
# os.remove('./data/EDABE dataset.zip')
# os.remove('./data/Electrodermal Activity artifact correction BEnchmark (EDABE)')